"""Schemas for browser-only utilities. These tools never receive user data server-side."""

from dataclasses import dataclass


@dataclass(frozen=True)
class BrowserTool:
    id: str
    collection: str
    name_ar: str
    name_en: str
    description_ar: str
    description_en: str
    icon: str
    fields: tuple[dict, ...]


def field(key, label_ar, label_en, kind="number", placeholder="", value="", choices=()):
    return {"key": key, "label_ar": label_ar, "label_en": label_en, "type": kind, "placeholder": placeholder, "value": value, "choices": choices}


TEXT = lambda key, ar, en, placeholder="": field(key, ar, en, "textarea", placeholder)
DATE = lambda key, ar, en: field(key, ar, en, "date")
SELECT = lambda key, ar, en, choices, value="": field(key, ar, en, "select", value=value, choices=choices)

BROWSER_TOOLS = (
    BrowserTool("gpa-calculator", "students", "حاسبة المعدل التراكمي", "GPA Calculator", "احسب معدلك من درجات الساعات المعتمدة.", "Calculate your GPA from course grades and credit hours.", "GPA", (TEXT("courses", "المقررات: الدرجة,الساعات لكل سطر", "Courses: grade,credits per line", "A,3\nB+,4"),)),
    BrowserTool("weighted-grade-calculator", "students", "حاسبة الدرجات الموزونة", "Weighted Grade Calculator", "احسب نتيجتك من الدرجات وأوزانها.", "Calculate a result from grades and their weights.", "%", (TEXT("items", "الدرجات: الدرجة,الوزن لكل سطر", "Grades: grade,weight per line", "85,40\n92,60"),)),
    BrowserTool("study-session-planner", "students", "مخطط جلسة المذاكرة", "Study Session Planner", "أنشئ خطة مذاكرة قصيرة بفواصل منتظمة.", "Create a focused study plan with regular breaks.", "PLAN", (field("minutes", "الدقائق المتاحة", "Minutes available", value="120"), field("topics", "عدد الموضوعات", "Topics", value="3"))),
    BrowserTool("focus-timer", "students", "مؤقت التركيز", "Focus Timer", "مؤقت تركيز بسيط يعمل داخل المتصفح.", "A simple focus timer that runs in your browser.", "25", (field("minutes", "دقائق التركيز", "Focus minutes", value="25"),)),
    BrowserTool("flashcard-maker", "students", "صانع البطاقات التعليمية", "Flashcard Maker", "حوّل أزواج السؤال والجواب إلى بطاقات قابلة للمراجعة.", "Turn question and answer pairs into reviewable cards.", "Q/A", (TEXT("cards", "سؤال | جواب لكل سطر", "Question | answer per line", "Capital of France | Paris"),)),
    BrowserTool("reading-time-estimator", "students", "مقدر وقت القراءة", "Reading Time Estimator", "قدّر وقت القراءة للنص الذي تكتبه.", "Estimate reading time for text you enter.", "READ", (TEXT("text", "النص", "Text"),)),
    BrowserTool("word-character-counter", "students", "عداد الكلمات والأحرف", "Word and Character Counter", "عد الكلمات والأحرف والأسطر في النص.", "Count words, characters, and lines in text.", "ABC", (TEXT("text", "النص", "Text"),)),
    BrowserTool("presentation-outline-builder", "students", "منشئ هيكل العرض", "Presentation Outline Builder", "أنشئ هيكل عرض من موضوعك والنقاط الأساسية محليًا.", "Build a presentation outline from a topic and key points locally.", "SLD", (field("topic", "موضوع العرض", "Presentation topic", "text", "Renewable energy", "Renewable energy"), TEXT("points", "نقطة رئيسية في كل سطر", "One key point per line", "Solar power\nWind power\nStorage"))),
    BrowserTool("slide-glossary-translator", "students", "مترجم مصطلحات العروض", "Slide Glossary Translator", "طبّق قاموس مصطلحاتك على نص الشرائح أو المستندات محليًا. لا يستخدم AI ولا يرسل النص.", "Apply your own glossary to pasted slide or document text locally. No AI and no text upload.", "A/B", (TEXT("text", "نص الشرائح أو المستند", "Slide or document text", "Renewable energy reduces carbon emissions."), TEXT("glossary", "قاموس المصطلحات: الأصل = الترجمة لكل سطر", "Glossary: source = translation per line", "Renewable energy = الطاقة المتجددة\ncarbon emissions = انبعاثات الكربون"))),
    BrowserTool("rubric-score-calculator", "educators", "حاسبة درجات التقييم", "Rubric Score Calculator", "احسب درجة تقييم موزونة بسرعة.", "Calculate a weighted rubric score quickly.", "RUB", (TEXT("items", "المعيار: الدرجة,الوزن لكل سطر", "Criterion: score,weight per line", "Research,4,30\nWriting,3,70"),)),
    BrowserTool("classroom-group-maker", "educators", "منشئ مجموعات الصف", "Classroom Group Maker", "وزع أسماء الطلاب عشوائيًا على مجموعات.", "Randomly distribute student names into groups.", "GRP", (TEXT("names", "الأسماء، اسم في كل سطر", "Names, one per line", "Amina\nOmar\nSara"), field("groups", "عدد المجموعات", "Number of groups", value="2"))),
    BrowserTool("random-name-picker", "educators", "اختيار اسم عشوائي", "Random Name Picker", "اختر اسمًا عشوائيًا من قائمتك.", "Pick a random name from your list.", "RND", (TEXT("names", "الأسماء، اسم في كل سطر", "Names, one per line"),)),
    BrowserTool("score-to-percentage", "educators", "تحويل الدرجة إلى نسبة", "Score-to-Percentage Converter", "حوّل الدرجة إلى نسبة مئوية.", "Convert a score into a percentage.", "%", (field("score", "الدرجة", "Score", value="18"), field("total", "الدرجة الكلية", "Total score", value="20"))),
    BrowserTool("lesson-timing-planner", "educators", "مخطط توقيت الدرس", "Lesson Timing Planner", "قسّم وقت الدرس إلى افتتاح ومحتوى ومراجعة.", "Split a lesson into opening, instruction, and review.", "TIME", (field("minutes", "مدة الدرس بالدقائق", "Lesson minutes", value="50"),)),
    BrowserTool("learning-objective-builder", "educators", "منشئ أهداف التعلم", "Learning Objective Builder", "أنشئ صياغة هدف تعلم واضحة.", "Build a clear learning-objective statement.", "OBJ", (field("verb", "الفعل", "Action verb", "text", "analyze", "Analyze"), field("topic", "الموضوع", "Topic", "text", "photosynthesis", "photosynthesis"), field("condition", "السياق أو الشرط", "Condition or context", "text", "after the lesson", "after the lesson"))),
    BrowserTool("seating-plan-generator", "educators", "مولد مخطط الجلوس", "Seating Plan Generator", "رتب أسماء الطلاب عشوائيًا في شبكة مقاعد.", "Arrange student names randomly in a seating grid.", "SEAT", (TEXT("names", "الأسماء، اسم في كل سطر", "Names, one per line"), field("columns", "عدد الأعمدة", "Columns", value="4"))),
    BrowserTool("text-similarity-checker", "educators", "فاحص تشابه النصوص", "Text Similarity Checker", "قارن نصين محليًا لمعرفة الكلمات المشتركة. ليس حكمًا أكاديميًا.", "Compare two texts locally for shared words. It is not an academic judgment.", "SIM", (TEXT("first", "النص الأول", "First text"), TEXT("second", "النص الثاني", "Second text"))),
    BrowserTool("jwt-decoder", "developers", "محلل JWT", "JWT Decoder", "يفك ترميز رأس وحمولة JWT محليًا فقط؛ التوقيع غير متحقق منه.", "Decode a JWT header and payload locally only; signature is unverified.", "JWT", (TEXT("token", "رمز JWT", "JWT token"),)),
    BrowserTool("query-string-parser-builder", "developers", "محلل وباني Query String", "Query String Parser/Builder", "حلل query string أو ابنها من أسطر مفتاح=قيمة.", "Parse a query string or build one from key=value lines.", "?=", (TEXT("query", "Query string أو key=value", "Query string or key=value", "name=Amina&role=editor"),)),
    BrowserTool("html-entity-converter", "developers", "تشفير وفك HTML Entities", "HTML Entity Encode/Decode", "شفّر أو فك HTML entities داخل المتصفح.", "Encode or decode HTML entities in your browser.", "&;", (TEXT("text", "النص", "Text", "<strong>Hello</strong>"),)),
    BrowserTool("unicode-inspector", "developers", "فاحص Unicode ومحوله", "Unicode Inspector/Escape Converter", "اعرض نقاط Unicode أو حوّل النص إلى escapes.", "Inspect Unicode code points or convert text to escapes.", "U+", (TEXT("text", "النص", "Text", "Hello مرحبا"),)),
    BrowserTool("cron-explainer", "developers", "شارح Cron", "Cron Expression Explainer", "اشرح تعبير cron القياسي ذي الحقول الخمسة.", "Explain a standard five-field cron expression.", "CRON", (field("expression", "تعبير Cron", "Cron expression", "text", "0 9 * * 1-5", "0 9 * * 1-5"),)),
    BrowserTool("color-contrast-checker", "developers", "فاحص تباين الألوان", "Color Contrast Checker", "تحقق من تباين لون النص والخلفية وفق WCAG.", "Check foreground and background contrast against WCAG.", "AA", (field("foreground", "لون النص", "Foreground color", "text", "#102019", "#102019"), field("background", "لون الخلفية", "Background color", "text", "#ffffff", "#ffffff"))),
    BrowserTool("semantic-version-comparator", "developers", "مقارن الإصدارات الدلالية", "Semantic Version Comparator", "قارن بين إصدارين دلاليين.", "Compare two semantic versions.", "SEM", (field("first", "الإصدار الأول", "First version", "text", "1.2.0", "1.2.0"), field("second", "الإصدار الثاني", "Second version", "text", "1.10.0", "1.10.0"))),
    BrowserTool("secret-redactor", "developers", "حاجب الأسرار النصية", "Text Secret Redactor", "أخف البريد والتوكنات والمفاتيح الظاهرة في النص محليًا قبل مشاركته.", "Hide visible emails, tokens, and keys locally before sharing text.", "SAFE", (TEXT("text", "النص", "Text"),)),
    BrowserTool("vat-calculator", "business", "حاسبة ضريبة القيمة المضافة", "VAT Calculator", "احسب ضريبة القيمة المضافة والإجمالي.", "Calculate VAT and the total amount.", "VAT", (field("amount", "المبلغ قبل الضريبة", "Amount before VAT", value="100"), field("rate", "نسبة الضريبة", "VAT rate (%)", value="15"))),
    BrowserTool("profit-margin-calculator", "business", "حاسبة هامش الربح", "Profit Margin Calculator", "احسب الربح وهامش الربح من التكلفة وسعر البيع.", "Calculate profit and profit margin from cost and sale price.", "MARGIN", (field("cost", "التكلفة", "Cost", value="80"), field("revenue", "سعر البيع", "Sale price", value="120"))),
    BrowserTool("break-even-calculator", "business", "حاسبة نقطة التعادل", "Break-Even Calculator", "احسب عدد الوحدات اللازمة لتغطية التكاليف.", "Calculate units needed to cover your costs.", "BE", (field("fixed", "التكاليف الثابتة", "Fixed costs", value="1000"), field("price", "سعر الوحدة", "Unit price", value="25"), field("variable", "تكلفة الوحدة المتغيرة", "Variable unit cost", value="10"))),
    BrowserTool("invoice-due-date", "business", "حاسبة استحقاق الفاتورة", "Invoice Due-Date Calculator", "احسب تاريخ استحقاق الفاتورة من تاريخها وشروط الدفع.", "Calculate an invoice due date from issue date and terms.", "DUE", (DATE("date", "تاريخ الفاتورة", "Invoice date"), field("days", "أيام الدفع", "Payment terms (days)", value="30"))),
    BrowserTool("timesheet-hours-calculator", "business", "حاسبة ساعات الدوام", "Timesheet Hours Calculator", "اجمع ساعات العمل من فترات البداية والنهاية.", "Add work hours from start and end time periods.", "HRS", (TEXT("entries", "بداية-نهاية لكل سطر", "Start-End per line", "09:00-17:30\n09:00-16:00"),)),
    BrowserTool("expense-splitter", "business", "مقسم المصروفات", "Expense Splitter", "قسّم إجمالي المصروفات بالتساوي بين المشاركين.", "Split a total expense evenly among participants.", "SPLIT", (field("amount", "إجمالي المصروف", "Total expense", value="250"), field("people", "عدد المشاركين", "Participants", value="5"))),
    BrowserTool("percentage-change", "business", "حاسبة التغير المئوي", "Percentage Change Calculator", "احسب الزيادة أو الانخفاض المئوي بين قيمتين.", "Calculate the percentage increase or decrease between values.", "%", (field("old", "القيمة الأصلية", "Original value", value="100"), field("new", "القيمة الجديدة", "New value", value="125"))),
    BrowserTool("document-key-points", "business", "مستخرج النقاط الأساسية", "Document Key Points", "استخرج أهم الجمل من النص محليًا حسب تكرار الكلمات.", "Extract key sentences from text locally using word frequency.", "KEY", (TEXT("text", "النص", "Text"),)),
    BrowserTool("unit-converter", "everyday", "محول الوحدات", "Unit Converter", "حوّل بين وحدات الطول والوزن الشائعة.", "Convert between common length and weight units.", "UNIT", (field("value", "القيمة", "Value", value="1"), field("from", "من: m, km, cm, in, ft, kg, lb", "From: m, km, cm, in, ft, kg, lb", "text", "km", "km"), field("to", "إلى", "To", "text", "mi", "mi"))),
    BrowserTool("cooking-measurement-converter", "everyday", "محول مقاييس الطبخ", "Cooking Measurement Converter", "حوّل بين المليلتر والأكواب والملاعق.", "Convert between milliliters, cups, tablespoons, and teaspoons.", "COOK", (field("value", "القيمة", "Value", value="1"), field("from", "من: ml, cup, tbsp, tsp", "From: ml, cup, tbsp, tsp", "text", "cup", "cup"), field("to", "إلى", "To", "text", "ml", "ml"))),
    BrowserTool("tip-calculator", "everyday", "حاسبة البقشيش", "Tip Calculator", "احسب البقشيش وحصة كل شخص.", "Calculate a tip and each person's share.", "TIP", (field("bill", "قيمة الفاتورة", "Bill amount", value="100"), field("rate", "البقشيش (%)", "Tip (%)", value="15"), field("people", "عدد الأشخاص", "People", value="2"))),
    BrowserTool("age-calculator", "everyday", "حاسبة العمر", "Age Calculator", "احسب العمر من تاريخ الميلاد.", "Calculate age from a birth date.", "AGE", (DATE("birth", "تاريخ الميلاد", "Birth date"),)),
    BrowserTool("date-difference", "everyday", "حاسبة فرق التاريخ", "Date Difference Calculator", "احسب الأيام بين تاريخين.", "Calculate the days between two dates.", "DATE", (DATE("start", "تاريخ البداية", "Start date"), DATE("end", "تاريخ النهاية", "End date"))),
    BrowserTool("time-zone-meeting-planner", "everyday", "مخطط اجتماع المناطق الزمنية", "Time Zone Meeting Planner", "اعرض وقت اجتماع في منطقتين زمنيتين.", "Show a meeting time in two time zones.", "TZ", (field("datetime", "وقت الاجتماع (UTC)", "Meeting time (UTC)", "datetime-local"), field("zone", "المنطقة الثانية (IANA)", "Second zone (IANA)", "text", "Asia/Riyadh", "Asia/Riyadh"))),
    BrowserTool("password-generator", "everyday", "مولد كلمات المرور", "Password Generator", "أنشئ كلمة مرور قوية محليًا.", "Generate a strong password locally.", "PASS", (field("length", "طول كلمة المرور", "Password length", value="16"),)),
    BrowserTool("light-background-cleanup", "everyday", "تنظيف الخلفية الفاتحة", "Light Background Cleanup", "اجعل الخلفيات البيضاء أو الفاتحة شفافة محليًا في متصفحك.", "Make white or light image backgrounds transparent locally in your browser.", "IMG", (field("image", "الصورة", "Image", "file", "image/png,image/jpeg,image/webp"),)),
    BrowserTool("citation-formatter", "students", "منسق الاقتباس المبسط", "Simple Citation Formatter", "نسّق بيانات مصدر في اقتباس مبسط محليًا.", "Format source details into a simple local citation.", "CITE", (field("author", "المؤلف", "Author", "text"), field("title", "العنوان", "Title", "text"), field("year", "السنة", "Year", "number"), field("source", "الناشر أو الموقع", "Publisher or site", "text"))),
    BrowserTool("grade-needed-calculator", "students", "حاسبة الدرجة المطلوبة", "Required Grade Calculator", "احسب الدرجة اللازمة في التقييم المتبقي للوصول إلى هدفك.", "Calculate the score needed on remaining work to reach a target.", "GOAL", (field("current", "درجتك الحالية (%)", "Current grade (%)", value="75"), field("completed", "الوزن المكتمل (%)", "Completed weight (%)", value="60"), field("target", "الدرجة المستهدفة (%)", "Target grade (%)", value="85"))),
    BrowserTool("deadline-countdown", "students", "عد تنازلي للموعد", "Assignment Deadline Countdown", "اعرض الوقت المتبقي حتى موعد تسليمك.", "Show the time remaining until an assignment deadline.", "DUE", (field("deadline", "الموعد النهائي", "Deadline", "datetime-local"),)),
    BrowserTool("exam-score-target", "students", "هدف درجة الاختبار", "Exam Score Target", "احسب نسبة الإجابات الصحيحة المطلوبة في الاختبار.", "Calculate the correct-answer percentage needed on an exam.", "EXAM", (field("questions", "عدد الأسئلة", "Question count", value="50"), field("target", "النتيجة المستهدفة (%)", "Target score (%)", value="80"))),
    BrowserTool("course-workload-estimator", "students", "مقدر عبء المقرر", "Course Workload Estimator", "قدّر ساعات الدراسة الأسبوعية من الساعات المعتمدة.", "Estimate weekly study hours from credit hours.", "HRS", (field("credits", "الساعات المعتمدة", "Credit hours", value="3"), field("weeks", "أسابيع الفصل", "Term weeks", value="15"))),
    BrowserTool("quiz-question-shuffler", "students", "خلاط أسئلة الاختبار", "Quiz Question Shuffler", "رتّب أسئلة المراجعة عشوائيًا محليًا.", "Randomize review questions locally.", "MIX", (TEXT("questions", "سؤال في كل سطر", "One question per line"),)),
    BrowserTool("note-outline-organizer", "students", "منظم ملاحظات إلى هيكل", "Notes to Outline Organizer", "حوّل سطور الملاحظات إلى هيكل مرقم.", "Turn note lines into a numbered outline.", "NOTE", (TEXT("notes", "ملاحظة في كل سطر", "One note per line"),)),
    BrowserTool("bibliography-alphabetizer", "students", "مرتب المراجع أبجديًا", "Bibliography Alphabetizer", "رتب قائمة مراجعك أبجديًا محليًا.", "Sort your bibliography entries alphabetically locally.", "A-Z", (TEXT("entries", "مرجع في كل سطر", "One reference per line"),)),
    BrowserTool("letter-grade-converter", "students", "محول النسبة إلى تقدير", "Percentage to Letter Grade", "حوّل النسبة إلى تقدير حرفي وفق مقياس شائع.", "Convert a percentage into a letter grade using a common scale.", "A+", (field("score", "النسبة المئوية", "Percentage", value="88"),)),
    BrowserTool("reading-list-planner", "students", "مخطط قائمة القراءة", "Reading List Planner", "قسّم صفحات القراءة على الأيام المتاحة.", "Split reading pages across the available days.", "BOOK", (field("pages", "إجمالي الصفحات", "Total pages", value="180"), field("days", "الأيام المتاحة", "Available days", value="7"))),
    BrowserTool("paragraph-counter", "students", "عداد الفقرات", "Paragraph Counter", "عد الفقرات والجمل في مسودتك.", "Count paragraphs and sentences in your draft.", "PARA", (TEXT("text", "المسودة", "Draft text"),)),
    BrowserTool("study-goal-checklist", "students", "قائمة أهداف المذاكرة", "Study Goal Checklist", "حوّل أهداف المذاكرة إلى قائمة تحقق قابلة للنسخ.", "Turn study goals into a copyable checklist.", "CHECK", (TEXT("goals", "هدف في كل سطر", "One goal per line"),)),
    BrowserTool("attendance-rate-calculator", "educators", "حاسبة نسبة الحضور", "Attendance Rate Calculator", "احسب نسبة الحضور للصف.", "Calculate a class attendance rate.", "ATT", (field("present", "الحاضرون", "Present", value="24"), field("total", "إجمالي الطلاب", "Total students", value="28"))),
    BrowserTool("grade-scale-builder", "educators", "منشئ مقياس التقديرات", "Grade Scale Builder", "أنشئ مقياس تقديرات من أعلى درجة وحدود النسب.", "Build a grade scale from a maximum score and percentage thresholds.", "SCALE", (field("total", "الدرجة الكلية", "Maximum score", value="100"), field("a", "حد A (%)", "A threshold (%)", value="90"), field("b", "حد B (%)", "B threshold (%)", value="80"), field("c", "حد C (%)", "C threshold (%)", value="70"))),
    BrowserTool("question-order-randomizer", "educators", "مرتب أسئلة عشوائي", "Question Order Randomizer", "اخلط ترتيب أسئلة ورقة العمل محليًا.", "Shuffle worksheet question order locally.", "Q?", (TEXT("questions", "سؤال في كل سطر", "One question per line"),)),
    BrowserTool("exit-ticket-builder", "educators", "منشئ بطاقة الخروج", "Exit Ticket Builder", "أنشئ ثلاث أسئلة قصيرة لبطاقة خروج.", "Build a three-question exit ticket.", "EXIT", (field("topic", "موضوع الدرس", "Lesson topic", "text"),)),
    BrowserTool("parent-message-template", "educators", "قالب رسالة لولي الأمر", "Parent Message Template", "أنشئ مسودة رسالة متابعة مهنية قابلة للتعديل.", "Create an editable professional follow-up message.", "MSG", (field("student", "اسم الطالب", "Student name", "text"), field("topic", "موضوع الرسالة", "Message topic", "text"), SELECT("tone", "النبرة", "Tone", (("positive", "إيجابية", "Positive"), ("concern", "ملاحظة داعمة", "Supportive concern")), "positive"))),
    BrowserTool("syllabus-date-planner", "educators", "مخطط تواريخ المنهج", "Syllabus Date Planner", "وزّع وحدات المنهج على أسابيع الفصل.", "Distribute syllabus units across term weeks.", "CAL", (field("units", "عدد الوحدات", "Number of units", value="8"), field("weeks", "أسابيع الفصل", "Term weeks", value="16"))),
    BrowserTool("duplicate-name-checker", "educators", "فاحص الأسماء المكررة", "Duplicate Name Checker", "اكتشف الأسماء المتكررة في قائمة صفك.", "Find repeated names in a class list.", "DUP", (TEXT("names", "اسم في كل سطر", "One name per line"),)),
    BrowserTool("reading-level-estimator", "educators", "مقدر مستوى القراءة", "Reading Level Estimator", "قدّر مستوى قراءة إنجليزي تقريبي من الجمل والكلمات.", "Estimate an approximate English reading level from sentences and words.", "READ", (TEXT("text", "النص الإنجليزي", "English text"),)),
    BrowserTool("participation-tracker", "educators", "ملخص المشاركة", "Participation Summary", "لخّص علامات المشاركة لكل طالب.", "Summarize participation marks for each student.", "TALLY", (TEXT("entries", "الاسم,عدد المشاركات لكل سطر", "Name,participation count per line"),)),
    BrowserTool("standards-checklist-builder", "educators", "منشئ قائمة معايير", "Standards Checklist Builder", "حوّل المعايير إلى قائمة تحقق قابلة للنسخ.", "Turn standards into a copyable checklist.", "CHECK", (TEXT("standards", "معيار في كل سطر", "One standard per line"),)),
    BrowserTool("quiz-time-estimator", "educators", "مقدر وقت الاختبار", "Quiz Time Estimator", "قدّر زمن الاختبار من عدد الأسئلة ووقت السؤال.", "Estimate quiz duration from question count and minutes per question.", "TIME", (field("questions", "عدد الأسئلة", "Questions", value="20"), field("minutes", "دقائق لكل سؤال", "Minutes per question", value="1.5"))),
    BrowserTool("class-list-numberer", "educators", "ترقيم قائمة الصف", "Class List Numberer", "رقّم أسماء قائمة الصف بالترتيب.", "Number a class list in order.", "#", (TEXT("names", "اسم في كل سطر", "One name per line"),)),
    BrowserTool("url-parser", "developers", "محلل الرابط", "URL Parser", "حلل مكونات الرابط محليًا.", "Parse URL components locally.", "URL", (field("url", "الرابط", "URL", "url", "https://example.com/path?x=1"),)),
    BrowserTool("regex-tester", "developers", "مختبر التعبير النمطي", "Regular Expression Tester", "اختبر تعبير JavaScript نمطيًا على نص محليًا.", "Test a JavaScript regular expression against text locally.", "REGEX", (field("pattern", "التعبير النمطي", "Pattern", "text", "\\d+"), TEXT("text", "النص", "Text"))),
    BrowserTool("http-status-lookup", "developers", "دليل حالة HTTP", "HTTP Status Lookup", "اعرض وصفًا مختصرًا لرمز حالة HTTP شائع.", "Show a short description for a common HTTP status code.", "HTTP", (field("code", "رمز الحالة", "Status code", value="404"),)),
    BrowserTool("css-unit-converter", "developers", "محول وحدات CSS", "CSS Unit Converter", "حوّل بين px وrem وفق حجم الجذر.", "Convert between px and rem using a root font size.", "CSS", (field("value", "القيمة", "Value", value="32"), SELECT("from", "من", "From", (("px", "px", "px"), ("rem", "rem", "rem")), "px"), SELECT("to", "إلى", "To", (("px", "px", "px"), ("rem", "rem", "rem")), "rem"), field("root", "حجم الجذر (px)", "Root size (px)", value="16"))),
    BrowserTool("text-diff", "developers", "مقارن النصوص", "Text Difference Checker", "اعرض الأسطر المضافة والمحذوفة بين نصين.", "Show added and removed lines between two texts.", "DIFF", (TEXT("first", "النص الأول", "First text"), TEXT("second", "النص الثاني", "Second text"))),
    BrowserTool("slug-generator", "developers", "مولد Slug", "Slug Generator", "أنشئ slug بسيطًا من عنوان.", "Create a simple slug from a title.", "SLUG", (field("text", "العنوان", "Title", "text"),)),
    BrowserTool("mime-type-lookup", "developers", "دليل نوع MIME", "MIME Type Lookup", "اعرض نوع MIME شائعًا لامتداد ملف.", "Look up a common MIME type for a file extension.", "MIME", (field("extension", "الامتداد", "Extension", "text", "json"),)),
    BrowserTool("ipv4-converter", "developers", "محول IPv4", "IPv4 Address Converter", "حوّل عنوان IPv4 إلى رقم عشري والعكس محليًا.", "Convert an IPv4 address to decimal and back locally.", "IP", (field("address", "IPv4 أو رقم عشري", "IPv4 or decimal number", "text", "192.168.1.1"),)),
    BrowserTool("line-ending-converter", "developers", "محول نهايات الأسطر", "Line Ending Converter", "حوّل نهايات أسطر النص إلى LF أو CRLF.", "Convert text line endings to LF or CRLF.", "LF", (TEXT("text", "النص", "Text"), SELECT("ending", "نهاية السطر", "Line ending", (("lf", "LF", "LF"), ("crlf", "CRLF", "CRLF")), "lf"))),
    BrowserTool("html-tag-stripper", "developers", "مزيل وسوم HTML", "HTML Tag Stripper", "استخرج النص من HTML محليًا.", "Extract text from HTML locally.", "HTML", (TEXT("text", "HTML", "HTML"),)),
    BrowserTool("case-converter", "developers", "محول حالة النص", "Text Case Converter", "حوّل النص إلى camelCase أو snake_case أو kebab-case.", "Convert text to camelCase, snake_case, or kebab-case.", "CASE", (TEXT("text", "النص", "Text"), SELECT("style", "النمط", "Style", (("camel", "camelCase", "camelCase"), ("snake", "snake_case", "snake_case"), ("kebab", "kebab-case", "kebab-case")), "camel"))),
    BrowserTool("duplicate-line-remover", "developers", "مزيل الأسطر المكررة", "Duplicate Line Remover", "احذف الأسطر المكررة مع الحفاظ على الترتيب.", "Remove duplicate lines while preserving order.", "UNIQ", (TEXT("text", "النص", "Text"),)),
    BrowserTool("discount-calculator", "business", "حاسبة الخصم", "Discount Calculator", "احسب قيمة الخصم والسعر النهائي.", "Calculate a discount amount and final price.", "OFF", (field("price", "السعر الأصلي", "Original price", value="100"), field("rate", "الخصم (%)", "Discount (%)", value="20"))),
    BrowserTool("commission-calculator", "business", "حاسبة العمولة", "Commission Calculator", "احسب العمولة من المبيعات والنسبة.", "Calculate commission from sales and a rate.", "COMM", (field("sales", "المبيعات", "Sales", value="5000"), field("rate", "العمولة (%)", "Commission (%)", value="5"))),
    BrowserTool("roi-calculator", "business", "حاسبة العائد على الاستثمار", "ROI Calculator", "احسب العائد على الاستثمار من التكلفة والعائد.", "Calculate return on investment from cost and return.", "ROI", (field("cost", "تكلفة الاستثمار", "Investment cost", value="1000"), field("return", "العائد", "Return value", value="1250"))),
    BrowserTool("cash-flow-summary", "business", "ملخص التدفق النقدي", "Cash Flow Summary", "لخّص التدفقات النقدية الداخلة والخارجة من أسطر مبسطة.", "Summarize incoming and outgoing cash from simple lines.", "CASH", (TEXT("entries", "وصف,مبلغ موجب أو سالب لكل سطر", "Description,positive or negative amount per line", "Sales,1200\nRent,-400"),)),
    BrowserTool("business-days-calculator", "business", "حاسبة أيام العمل", "Business Days Calculator", "احسب أيام العمل بين تاريخين دون عطلات نهاية الأسبوع.", "Count weekdays between two dates, excluding weekends.", "WORK", (DATE("start", "تاريخ البداية", "Start date"), DATE("end", "تاريخ النهاية", "End date"))),
    BrowserTool("meeting-agenda-builder", "business", "منشئ جدول الاجتماع", "Meeting Agenda Builder", "أنشئ جدول اجتماع مرقمًا من بنودك.", "Create a numbered meeting agenda from your items.", "AGENDA", (field("title", "عنوان الاجتماع", "Meeting title", "text"), TEXT("items", "بند في كل سطر", "One agenda item per line"))),
    BrowserTool("purchase-order-total", "business", "حاسبة إجمالي أمر الشراء", "Purchase Order Total", "اجمع بنود أمر الشراء مع الكميات والأسعار.", "Total purchase-order items with quantities and prices.", "PO", (TEXT("items", "الصنف,الكمية,السعر لكل سطر", "Item,quantity,price per line", "Paper,4,5.5"),)),
    BrowserTool("straight-line-depreciation", "business", "حاسبة الإهلاك الخطي", "Straight-Line Depreciation", "احسب الإهلاك السنوي للأصل.", "Calculate annual straight-line asset depreciation.", "DEP", (field("cost", "تكلفة الأصل", "Asset cost", value="10000"), field("salvage", "القيمة المتبقية", "Salvage value", value="1000"), field("years", "العمر بالسنوات", "Useful life (years)", value="5"))),
    BrowserTool("installment-calculator", "business", "حاسبة الأقساط", "Installment Calculator", "قسّم مبلغًا إلى أقساط متساوية.", "Split an amount into equal installments.", "PAY", (field("amount", "المبلغ", "Amount", value="1200"), field("payments", "عدد الأقساط", "Number of installments", value="12"))),
    BrowserTool("inventory-reorder-point", "business", "حاسبة نقطة إعادة الطلب", "Inventory Reorder Point", "احسب نقطة إعادة طلب المخزون من الطلب والمهلة ومخزون الأمان.", "Calculate an inventory reorder point from demand, lead time, and safety stock.", "STOCK", (field("daily", "الطلب اليومي", "Daily demand", value="12"), field("lead", "مهلة التوريد بالأيام", "Lead time (days)", value="7"), field("safety", "مخزون الأمان", "Safety stock", value="20"))),
    BrowserTool("invoice-number-generator", "business", "مولد رقم الفاتورة", "Invoice Number Generator", "أنشئ رقم فاتورة من بادئة وتاريخ وتسلسل.", "Create an invoice number from a prefix, date, and sequence.", "INV", (field("prefix", "البادئة", "Prefix", "text", "INV", "INV"), DATE("date", "التاريخ", "Date"), field("sequence", "التسلسل", "Sequence", value="1"))),
    BrowserTool("overtime-pay-calculator", "business", "حاسبة أجر العمل الإضافي", "Overtime Pay Calculator", "احسب الأجر العادي والإضافي من الساعات والأجر بالساعة.", "Calculate regular and overtime pay from hours and an hourly rate.", "OT", (field("hours", "إجمالي الساعات", "Total hours", value="45"), field("rate", "الأجر بالساعة", "Hourly rate", value="20"), field("threshold", "حد الساعات العادية", "Regular-hours threshold", value="40"))),
    BrowserTool("bmi-calculator", "everyday", "حاسبة مؤشر كتلة الجسم", "BMI Calculator", "احسب مؤشر كتلة الجسم من الطول والوزن.", "Calculate body mass index from height and weight.", "BMI", (field("weight", "الوزن (kg)", "Weight (kg)", value="70"), field("height", "الطول (cm)", "Height (cm)", value="175"))),
    BrowserTool("temperature-converter", "everyday", "محول الحرارة", "Temperature Converter", "حوّل بين Celsius وFahrenheit وKelvin.", "Convert between Celsius, Fahrenheit, and Kelvin.", "TEMP", (field("value", "القيمة", "Value", value="25"), SELECT("from", "من", "From", (("c", "Celsius", "Celsius"), ("f", "Fahrenheit", "Fahrenheit"), ("k", "Kelvin", "Kelvin")), "c"), SELECT("to", "إلى", "To", (("c", "Celsius", "Celsius"), ("f", "Fahrenheit", "Fahrenheit"), ("k", "Kelvin", "Kelvin")), "f"))),
    BrowserTool("pace-calculator", "everyday", "حاسبة الوتيرة", "Pace Calculator", "احسب وتيرة المشي أو الجري من المسافة والوقت.", "Calculate walking or running pace from distance and time.", "PACE", (field("distance", "المسافة (km)", "Distance (km)", value="5"), field("minutes", "الوقت بالدقائق", "Time (minutes)", value="30"))),
    BrowserTool("fuel-cost-calculator", "everyday", "حاسبة تكلفة الوقود", "Fuel Cost Calculator", "قدّر تكلفة الوقود لرحلة.", "Estimate fuel cost for a trip.", "FUEL", (field("distance", "المسافة (km)", "Distance (km)", value="250"), field("efficiency", "استهلاك الوقود (L/100km)", "Fuel use (L/100km)", value="8"), field("price", "سعر اللتر", "Price per liter", value="2"))),
    BrowserTool("loan-payment-estimator", "everyday", "مقدر القسط الشهري", "Loan Payment Estimator", "قدّر القسط الشهري لقرض بفائدة ثابتة.", "Estimate the monthly payment for a fixed-rate loan.", "LOAN", (field("principal", "مبلغ القرض", "Loan amount", value="10000"), field("rate", "الفائدة السنوية (%)", "Annual interest (%)", value="6"), field("months", "عدد الأشهر", "Months", value="36"))),
    BrowserTool("random-decision-picker", "everyday", "اختيار قرار عشوائي", "Random Decision Picker", "اختر قرارًا عشوائيًا من خياراتك.", "Pick one decision at random from your choices.", "PICK", (TEXT("choices", "خيار في كل سطر", "One choice per line"),)),
    BrowserTool("grocery-list-organizer", "everyday", "منظم قائمة التسوق", "Grocery List Organizer", "رتب قائمة التسوق أبجديًا مع حذف التكرار.", "Sort a grocery list alphabetically and remove duplicates.", "LIST", (TEXT("items", "صنف في كل سطر", "One item per line"),)),
    BrowserTool("chore-splitter", "everyday", "مقسم المهام المنزلية", "Chore Splitter", "وزع المهام المنزلية بالتساوي على المشاركين.", "Distribute household chores evenly among people.", "CHORE", (TEXT("chores", "مهمة في كل سطر", "One chore per line"), TEXT("people", "شخص في كل سطر", "One person per line"))),
    BrowserTool("sleep-time-planner", "everyday", "مخطط وقت النوم", "Sleep Time Planner", "اقترح وقت نوم تقريبي بناءً على وقت الاستيقاظ.", "Suggest approximate bedtimes from a wake-up time.", "SLEEP", (field("wake", "وقت الاستيقاظ", "Wake-up time", "time", "07:00", "07:00"),)),
    BrowserTool("water-intake-estimator", "everyday", "مقدر شرب الماء", "Water Intake Estimator", "قدّر كمية الماء اليومية التقريبية من الوزن.", "Estimate approximate daily water intake from weight.", "WATER", (field("weight", "الوزن (kg)", "Weight (kg)", value="70"),)),
    BrowserTool("random-number-generator", "everyday", "مولد رقم عشوائي", "Random Number Generator", "أنشئ رقمًا عشوائيًا ضمن نطاق تختاره.", "Generate a random number in a chosen range.", "RAND", (field("min", "الحد الأدنى", "Minimum", value="1"), field("max", "الحد الأعلى", "Maximum", value="100"))),
    BrowserTool("text-cleaner", "everyday", "منظف النص", "Text Cleaner", "نظّف المسافات الزائدة والأسطر الفارغة من النص.", "Clean extra spaces and blank lines from text.", "CLEAN", (TEXT("text", "النص", "Text"),)),
)

BROWSER_TOOL_MAP = {tool.id: tool for tool in BROWSER_TOOLS}


def get_browser_tool(tool_id: str) -> BrowserTool | None:
    return BROWSER_TOOL_MAP.get(tool_id)


def browser_collection_tools(collection_id: str) -> list[BrowserTool]:
    return [tool for tool in BROWSER_TOOLS if tool.collection == collection_id]