"""Infinity 8 knowledge clusters.

These guides are manually written, implementation-aware additions to the existing
bilingual Knowledge Center. They are installed before page blueprints import the
canonical blog registry.
"""
from __future__ import annotations

V8_BLOG_POSTS = [
    {
        "slug": "repair-pdf-before-converting",
        "title_ar": "متى تصلح PDF قبل ما تحوله؟",
        "title_en": "When should you repair a PDF before converting it?",
        "description_ar": "دليل عملي يوضح متى يفيد إصلاح بنية PDF قبل الضغط أو التحويل، ومتى لن يعالج الإصلاح محتوى مفقودًا أصلًا.",
        "description_en": "A practical guide to when structural PDF repair helps before compression or conversion, and what repair cannot recover.",
        "category_ar": "PDF",
        "category_en": "PDF",
        "minutes": 6,
        "tool": "/tools/pdf-repair",
        "tool_label_ar": "جرّب إصلاح PDF",
        "tool_label_en": "Try PDF Repair",
        "sections": [
            ("ابدأ بالإصلاح عندما يتصرف الملف بشكل غير طبيعي", "إذا كان PDF يفتح في برنامج ويرفضه برنامج آخر، أو يفشل التحويل رغم أن الصفحات تبدو موجودة، فقد تكون المشكلة في البنية الداخلية. إعادة كتابة الملف وتنظيف الكائنات الزائدة قد تجعل الحاوية أكثر اتساقًا قبل الخطوة التالية."),
            ("الإصلاح لا يعيد المحتوى المفقود", "إذا كانت صفحة ناقصة من المصدر أو stream تالفًا لدرجة لا يستطيع محرك PDF قراءته، فالإصلاح البنيوي لا يستطيع اختراع البيانات. احتفظ بالأصل وتعامل مع النسخة المصلحة كنسخة جديدة تحتاج مقارنة."),
            ("بعد الإصلاح اختبر أكثر من الشكل", "افتح أول صفحة ووسط الملف وآخره، ثم جرّب البحث وتحديد النص والروابط المهمة. نجاح الفتح وحده لا يثبت أن كل ميزة متقدمة بقيت كما كانت."),
            ("متى تضغط بعد الإصلاح؟", "إذا أصبح الملف سليمًا بصريًا ووظيفيًا، يمكن أن يكون الضغط خطوة تالية مفيدة للمشاركة. الأفضل أن تصلح أولًا ثم تضغط الناتج بدل محاولة ضغط ملف غير مستقر."),
        ],
        "section_en": [
            "Start with repair when the file behaves inconsistently",
            "Repair cannot recreate missing content",
            "Test more than appearance after repair",
            "When compression should come next",
        ],
        "paragraph_en": [
            "If a PDF opens in one application but fails in another, or conversion fails even though the pages look present, the internal structure may be messy. Rewriting the file and cleaning redundant objects can create a more consistent container before the next operation.",
            "If a page is already missing or a stream is damaged beyond what the PDF engine can read, structural repair cannot invent that data. Keep the original and treat the repaired output as a new copy that must be compared.",
            "Open the first, middle, and last pages, then test search, text selection, and any important links. A file opening successfully does not prove that every advanced document feature survived a structural rewrite.",
            "Once the repaired copy looks and behaves correctly, compression can be a useful sharing step. Repairing first and compressing the clean result is safer than trying to optimize a PDF that is already behaving unpredictably.",
        ],
    },
    {
        "slug": "searchable-pdf-vs-ocr-text",
        "title_ar": "PDF قابل للبحث أم ملف نص OCR؟ اختر الناتج المناسب",
        "title_en": "Searchable PDF or OCR text? Choose the right output",
        "description_ar": "افهم الفرق بين إضافة طبقة بحث داخل PDF وبين استخراج النص إلى TXT، وكيف تختار حسب هدفك الحقيقي.",
        "description_en": "Understand the difference between adding a searchable text layer to a PDF and exporting OCR text to TXT.",
        "category_ar": "OCR",
        "category_en": "OCR",
        "minutes": 6,
        "tool": "/tools/ocr-pdf-to-searchable",
        "tool_label_ar": "جرّب PDF قابل للبحث",
        "tool_label_en": "Try Searchable PDF OCR",
        "sections": [
            ("إذا يهمك شكل الصفحة فاختر PDF قابلًا للبحث", "المسار القابل للبحث يحافظ على صورة الصفحة كمرجع بصري ويضيف طبقة نص تساعد في البحث والنسخ. هذا مناسب للأرشفة والمستندات التي تريد أن تبقى مطابقة للمسح بصريًا."),
            ("إذا يهمك النص الخام فاختر استخراج OCR", "ملف TXT أخف وأسهل للنقل إلى محرر أو نظام آخر، لكنه لا يحافظ على أماكن العناصر أو شكل الصفحة. استخدمه عندما تكون الكلمات نفسها أهم من التصميم."),
            ("الاثنان يحتاجان مراجعة", "طبقة البحث وملف النص كلاهما ناتجان عن تعرف بصري احتمالي. راجع الأسماء والأرقام والتواريخ، ولا تعتبر نجاح البحث دليلًا على أن كل حرف صحيح."),
            ("اختبر صفحة صعبة قبل معالجة ملف طويل", "اختر صفحة فيها أرقام وخط صغير أو جدول. إذا كانت النتيجة مقبولة هناك، تكون لديك صورة أوضح عن جودة بقية المستند قبل تشغيل مئات الصفحات."),
        ],
        "section_en": [
            "Choose searchable PDF when page appearance matters",
            "Choose OCR text when raw words matter most",
            "Both outputs still need review",
            "Test a difficult page before a long run",
        ],
        "paragraph_en": [
            "A searchable-PDF workflow keeps the scanned page as the visual reference while adding a text layer for search and copying. That is useful for archives and documents that should continue to look like the original scan.",
            "A TXT export is lighter and easier to move into an editor or another system, but it does not preserve page layout or visual positioning. Use it when the words matter more than the original design.",
            "Both the searchable layer and a text export come from probabilistic optical recognition. Check names, numbers, and dates carefully; successful search does not prove that every recognized character is correct.",
            "Pick a page with small text, numbers, or a table and test it first. If recognition is acceptable on the difficult page, you have a better signal before committing to a long multi-page OCR job.",
        ],
    },
    {
        "slug": "remove-image-metadata-before-sharing",
        "title_ar": "هل تحذف بيانات الصورة الوصفية قبل المشاركة؟",
        "title_en": "Should you remove image metadata before sharing?",
        "description_ar": "متى تكون EXIF مفيدة، ومتى يفضل إنشاء نسخة مشاركة بدون بيانات وصفية شائعة مع الاحتفاظ بالأصل.",
        "description_en": "When EXIF is useful, when a metadata-clean sharing copy makes sense, and why the original should be kept.",
        "category_ar": "الخصوصية",
        "category_en": "Privacy",
        "minutes": 5,
        "tool": "/tools/image-strip-metadata",
        "tool_label_ar": "جرّب إزالة بيانات الصورة",
        "tool_label_en": "Try Remove Image Metadata",
        "sections": [
            ("البيانات الوصفية ليست دائمًا سيئة", "معلومات مثل وقت التصوير أو إعدادات الكاميرا قد تكون مفيدة للأرشفة والتصوير. لا تحذفها من النسخة الأصلية لمجرد أنها موجودة."),
            ("أنشئ نسخة مشاركة عندما لا تحتاج التفاصيل", "إذا كان هدفك إرسال صورة أو نشرها بدون الحاجة إلى EXIF، فالنسخة المنظفة تقلل البيانات المصاحبة غير الضرورية. هذا مفيد خصوصًا عندما تريد مشاركة المحتوى نفسه فقط."),
            ("الإزالة ليست ضمان إخفاء كل معلومة", "قد تكون معلومات حساسة ظاهرة داخل البكسلات نفسها مثل لوحة أو اسم أو مستند في الخلفية. تنظيف metadata لا يطمس ما يظهر بصريًا."),
            ("راجع الجودة والصيغة بعد التنظيف", "بعض مسارات إزالة البيانات تعيد ترميز الصورة. افتح الناتج وقارن الأبعاد والخلفية والشفافية عند الحاجة، واحتفظ بالأصل للأرشفة."),
        ],
        "section_en": [
            "Metadata is not always bad",
            "Create a sharing copy when details are unnecessary",
            "Metadata removal does not hide visible information",
            "Check quality and format after cleaning",
        ],
        "paragraph_en": [
            "Information such as capture time or camera settings can be useful for photography and archiving. Do not erase useful metadata from your only original just because it exists.",
            "If the goal is simply to send or publish an image and you do not need EXIF, a cleaned sharing copy can reduce unnecessary attached information. The content remains the focus instead of the capture details.",
            "Sensitive information may be visible in the pixels themselves, such as a badge, document, address, or screen in the background. Removing metadata does not redact anything that can be seen in the image.",
            "Some metadata-cleaning workflows re-encode the image. Open the result and check dimensions, background, and transparency when those matter, while retaining the original as the archival copy.",
        ],
    },
    {
        "slug": "xlsx-to-csv-without-surprises",
        "title_ar": "Excel إلى CSV بدون مفاجآت: وش الذي يبقى ووش الذي يختفي؟",
        "title_en": "Excel to CSV without surprises: what stays and what disappears?",
        "description_ar": "فهم الفرق بين Workbook وCSV قبل التصدير، خصوصًا الأوراق المتعددة والصيغ والتنسيق.",
        "description_en": "Understand what a CSV keeps and loses compared with an Excel workbook, especially sheets, formulas, and formatting.",
        "category_ar": "البيانات",
        "category_en": "Data",
        "minutes": 6,
        "tool": "/tools/xlsx-to-csv",
        "tool_label_ar": "جرّب Excel إلى CSV",
        "tool_label_en": "Try XLSX to CSV",
        "sections": [
            ("CSV جدول مسطح وليس Workbook", "ملف Excel يستطيع حمل أوراق متعددة وتنسيقات ومخططات، بينما CSV يمثل صفوفًا وأعمدة نصية في جدول واحد. لذلك لا تتوقع أن تنتقل كل خصائص المصنف."),
            ("راجع الورقة التي تريد تصديرها", "إذا كان الملف يحتوي أكثر من Sheet، تأكد من سياسة الأداة أو المصدر الذي تريد أخذه. التصدير الخاطئ لورقة غير مقصودة قد ينتج ملفًا صحيحًا تقنيًا لكنه غير مفيد."),
            ("انتبه للصيغ والقيم المعروضة", "في سير البيانات يهمك غالبًا الناتج أو القيمة أكثر من شكل الصيغة داخل Excel. افتح CSV الناتج وتأكد من الأعمدة المهمة والأرقام والتواريخ بدل الاعتماد على أن الملف تم تنزيله فقط."),
            ("اختبر الترميز مع العربية", "UTF-8 هو الخيار المناسب لمعظم التدفقات الحديثة. افتح عينة تحتوي عربيًا وإنجليزيًا في البرنامج الذي سيستهلك CSV وتأكد أن الحروف والفواصل تظهر بشكل صحيح."),
        ],
        "section_en": [
            "CSV is a flat table, not a workbook",
            "Check which sheet you intend to export",
            "Pay attention to formulas and displayed values",
            "Test encoding with Arabic text",
        ],
        "paragraph_en": [
            "An Excel workbook can contain multiple sheets, formatting, charts, and richer cell behavior. CSV represents rows and columns in one flat table, so it cannot preserve every workbook feature.",
            "If the file has multiple sheets, confirm which sheet the workflow exports or which source you intend to use. Exporting the wrong sheet can produce a technically valid file that is still useless for your task.",
            "For data exchange, the resulting value is often more important than how a formula looked inside Excel. Open the CSV and check key columns, numbers, and dates rather than assuming a completed download means the data is correct.",
            "UTF-8 is the practical default for modern workflows. Test a sample containing both Arabic and English in the application that will consume the CSV so you can confirm characters and delimiters are interpreted correctly.",
        ],
    },
    {
        "slug": "csv-to-json-for-apis",
        "title_ar": "متى تحول CSV إلى JSON قبل استخدام البيانات في API؟",
        "title_en": "When should you turn CSV into JSON for an API?",
        "description_ar": "دليل للمطورين يشرح متى يكون JSON أسهل للأنظمة، وما الذي يجب التحقق منه في أسماء الأعمدة والأنواع.",
        "description_en": "A developer-focused guide to when JSON is easier for systems and what to verify in headers and value types.",
        "category_ar": "المطورون",
        "category_en": "Developers",
        "minutes": 6,
        "tool": "/tools/csv-to-json",
        "tool_label_ar": "جرّب CSV إلى JSON",
        "tool_label_en": "Try CSV to JSON",
        "sections": [
            ("JSON أوضح عندما تتعامل مع كائنات", "إذا كان كل صف يمثل سجلًا له حقول معروفة، يمكن أن يكون JSON أسهل للقراءة من تطبيقات الويب والـAPIs. أسماء الأعمدة تتحول عادة إلى مفاتيح، لذلك جودة header مهمة."),
            ("النص لا يتحول تلقائيًا إلى نوع مثالي دائمًا", "القيمة 00123 قد تكون رقمًا أو معرفًا يجب أن يحتفظ بالأصفار. راجع الحقول التي تبدو رقمية قبل أن تبني عليها منطقًا يفترض نوع بيانات معينًا."),
            ("نظف أسماء الأعمدة قبل التكامل", "العناوين المكررة أو الفارغة أو التي تحتوي مسافات غريبة تسبب ارتباكًا في الأنظمة اللاحقة. اجعل أسماء الحقول واضحة وثابتة قبل نشر تنسيق تعتمد عليه تطبيقات أخرى."),
            ("تحقق بعينة صغيرة أولًا", "حوّل عشرة صفوف وافحص JSON يدويًا أو عبر parser قبل معالجة ملف ضخم. ستكتشف مشاكل الفواصل والاقتباسات والعناوين أسرع بكثير."),
        ],
        "section_en": [
            "JSON is clearer when rows represent objects",
            "Text values do not always become ideal types automatically",
            "Clean headers before integration",
            "Validate a small sample first",
        ],
        "paragraph_en": [
            "When each CSV row represents a record with known fields, JSON can be easier for web applications and APIs to consume. Column headers commonly become keys, so header quality matters.",
            "A value such as 00123 might be a number or an identifier that must preserve leading zeros. Review fields that look numeric before building application logic that assumes a specific data type.",
            "Duplicate, empty, or strangely spaced headers create ambiguity downstream. Use clear and stable field names before publishing a data shape that other applications will depend on.",
            "Convert a small set of rows and inspect the JSON manually or with a parser before processing a very large file. Delimiter, quoting, and header problems become much easier to spot early.",
        ],
    },
    {
        "slug": "favicon-pack-from-one-image",
        "title_ar": "كيف تجهز Favicon من صورة واحدة بدون ما يطلع مشوش؟",
        "title_en": "How to build a favicon pack from one image without blurry results",
        "description_ar": "نصائح لاختيار صورة المصدر، تبسيط التفاصيل، وفحص المقاسات الصغيرة قبل استخدام حزمة الأيقونات.",
        "description_en": "Tips for source artwork, simplifying detail, and checking tiny sizes before using a generated favicon pack.",
        "category_ar": "الصور",
        "category_en": "Images",
        "minutes": 5,
        "tool": "/tools/image-favicon-pack",
        "tool_label_ar": "جرّب حزمة Favicon",
        "tool_label_en": "Try Favicon Pack",
        "sections": [
            ("ابدأ بصورة مربعة وواضحة", "الأيقونة الصغيرة لا تتحمل تفاصيل كثيرة. استخدم شعارًا أو رمزًا يمكن فهمه حتى عند تصغيره، وابتعد عن نص طويل أو عناصر دقيقة جدًا."),
            ("الشفافية والحواف تحتاج فحصًا", "إذا كان المصدر يحتوي خلفية شفافة، افتح الأيقونات على خلفيات فاتحة وداكنة. قد تكون حافة جميلة على لون واحد ضعيفة على لون آخر."),
            ("لا تحكم من 512 بكسل فقط", "المشكلة الحقيقية تظهر عند 16 و32 بكسل. افتح المقاسات الصغيرة نفسها وتأكد أن الشكل ما زال واضحًا بدل الاعتماد على معاينة كبيرة."),
            ("اختبر الحزمة داخل المتصفح", "بعد إضافة الملفات للموقع امسح cache أو استخدم نافذة خاصة عند الحاجة، لأن favicons تُخزن مؤقتًا بقوة وقد تظن أن الملف الجديد لم يعمل."),
        ],
        "section_en": [
            "Start with clear square artwork",
            "Check transparency and edges",
            "Do not judge only at 512 pixels",
            "Test the pack in a real browser",
        ],
        "paragraph_en": [
            "Tiny icons cannot carry much detail. Use a mark or logo that remains understandable when reduced and avoid long text or very fine elements.",
            "If the source uses transparency, view the generated icons against both light and dark backgrounds. An edge that looks good on one color can disappear on another.",
            "The real challenge appears at 16 and 32 pixels. Inspect those actual sizes instead of judging only from a large preview where every detail still looks sharp.",
            "After installing the favicon files on a site, clear relevant cache or use a private window when testing. Browsers cache favicons aggressively, which can make a correct new file appear unchanged.",
        ],
    },
    {
        "slug": "reorder-and-number-pdf-pages",
        "title_ar": "إعادة ترتيب صفحات PDF ثم ترقيمها: أي خطوة أول؟",
        "title_en": "Reorder PDF pages, then number them: which step comes first?",
        "description_ar": "مسار بسيط يمنع أرقام الصفحات من أن تصبح غير منطقية بعد إعادة الترتيب أو حذف صفحات.",
        "description_en": "A simple workflow that keeps page numbers logical after rearranging or removing pages.",
        "category_ar": "PDF",
        "category_en": "PDF",
        "minutes": 5,
        "tool": "/tools/pdf-reorder-pages",
        "tool_label_ar": "جرّب إعادة ترتيب PDF",
        "tool_label_en": "Try Reorder PDF Pages",
        "sections": [
            ("رتب المحتوى قبل إضافة الأرقام", "إذا رقمت الصفحات أولًا ثم غيرت ترتيبها، ستنتقل الأرقام القديمة مع الصفحات وقد لا تعكس التسلسل الجديد. اجعل ترتيب المستند نهائيًا أولًا."),
            ("راجع الصفحات التي لها ترقيم مطبوع أصلًا", "قد يحتوي المصدر أرقامًا داخل التصميم نفسه. إضافة أرقام جديدة فوقها قد تربك القارئ، لذلك افحص الهامش العلوي والسفلي قبل الترقيم."),
            ("افحص البداية والنهاية ونقطة التغيير", "بعد إعادة الترتيب افتح الصفحة الأولى والأخيرة والصفحات حول أي نقل مهم. بعدها أضف الترقيم وافحص الموضع على صفحة مزدحمة."),
            ("احتفظ بنسخة قبل التعديل", "عمليات الترتيب والترقيم تنتج نسخًا جديدة، وهذا جيد. لا تحذف الأصل حتى تتأكد أن التسلسل والمراجع الداخلية ما زالت منطقية."),
        ],
        "section_en": [
            "Finalize order before adding numbers",
            "Check for numbers already printed in the design",
            "Inspect the beginning, end, and moved boundaries",
            "Keep a copy before editing",
        ],
        "paragraph_en": [
            "If you add page numbers first and rearrange pages later, those old numbers move with the pages and may no longer match the new sequence. Finalize document order first.",
            "A source PDF may already contain numbers as part of the page design. Adding a second numbering layer can confuse readers, so inspect the top and bottom margins before applying new numbers.",
            "After reordering, open the first and last pages plus the pages around every important move. Then add numbering and check its position on a visually busy page.",
            "Reordering and numbering produce new copies, which is useful. Keep the original until you have verified the new sequence and any internal references that depend on page numbers.",
        ],
    },
    {
        "slug": "safe-multi-step-file-workflows",
        "title_ar": "ليش كل خطوة في مسار الملفات لازم تعيد التحقق من الناتج؟",
        "title_en": "Why should every step in a file workflow re-validate its input?",
        "description_ar": "شرح مبسط لفكرة المسارات المتعددة ولماذا لا يجب أن تثق الخطوة التالية تلقائيًا في ملف أنتجته الخطوة السابقة.",
        "description_en": "A plain-language explanation of multi-step file workflows and why each handoff should be validated again.",
        "category_ar": "الأمان",
        "category_en": "Security",
        "minutes": 7,
        "tool": "/workflows",
        "tool_label_ar": "افتح مسارات Infinity",
        "tool_label_en": "Open Infinity Workflows",
        "sections": [
            ("الناتج الوسيط يصبح إدخالًا جديدًا", "إذا حوّلت Word إلى PDF ثم ضغطته، ملف PDF الناتج من الخطوة الأولى هو إدخال الخطوة الثانية. لذلك يجب أن يمر بفحص النوع والبنية كما لو أنه ملف جديد."),
            ("التوافق يمنع المسارات غير المنطقية", "ليس كل ناتج مناسبًا لكل أداة. معرفة امتداد ونوع الناتج تسمح ببناء سلسلة يمكن تنفيذها بدل قائمة أدوات تبدو ذكية لكنها لا تتصل ببعضها فعليًا."),
            ("المساحة المؤقتة تقلل البقايا", "كل خطوة تحتاج ملفات عمل مؤقتة. تنظيف المساحة السابقة بعد استلام الخطوة التالية للناتج يقلل مدة بقاء الملفات ويجعل حدود المعالجة أوضح."),
            ("الذكاء يقترح والخادم يتحقق", "حتى إذا اقترح AI مسارًا مناسبًا، التنفيذ الحقيقي يجب أن يتحقق من الأدوات والحدود والتوافق مرة ثانية على الخادم. الاقتراح ليس تصريحًا بتجاوز قواعد الأمان."),
        ],
        "section_en": [
            "An intermediate output becomes a new input",
            "Compatibility prevents impossible chains",
            "Temporary workspaces reduce leftovers",
            "AI can suggest; the server still verifies",
        ],
        "paragraph_en": [
            "If you convert Word to PDF and then compress it, the PDF created by the first step becomes the second step's input. It should therefore pass type and structural validation as if it were a new file.",
            "Not every output belongs in every tool. Knowing the output type lets the system build a chain that can actually execute instead of presenting a clever-looking list of unrelated actions.",
            "Each step needs temporary working files. Cleaning the previous workspace after the next step safely receives the artifact reduces how long files remain and makes processing boundaries easier to reason about.",
            "Even when AI proposes a sensible path, real execution should validate tools, limits, and compatibility again on the server. A recommendation is never permission to bypass security rules.",
        ],
    },
    {
        "slug": "browser-local-tools-and-privacy",
        "title_ar": "متى تكون الأداة التي تعمل داخل المتصفح أفضل للخصوصية؟",
        "title_en": "When is a browser-local tool better for privacy?",
        "description_ar": "فرق عملي بين الأدوات التي تحسب أو تنظف البيانات محليًا في المتصفح وبين مهام الملفات التي تحتاج معالجة خادمية.",
        "description_en": "A practical distinction between tools that can work locally in the browser and file tasks that require server-side processing.",
        "category_ar": "الخصوصية",
        "category_en": "Privacy",
        "minutes": 6,
        "tool": "/collections/developers",
        "tool_label_ar": "تصفح الأدوات المحلية",
        "tool_label_en": "Browse Local Tools",
        "sections": [
            ("بعض المهام لا تحتاج رفع ملف أصلًا", "تحويل حالة نص، حساب نسبة، تحليل URL أو تنظيف قائمة يمكن أن يتم داخل المتصفح. عندما لا توجد حاجة لمعالجة خادمية، إبقاء البيانات على الجهاز يبسط نموذج الخصوصية."),
            ("المعالجة المحلية لها حدود", "OCR وLibreOffice وتحويلات PDF الثقيلة تحتاج محركات لا يوفرها كل متصفح بشكل مناسب. عندها تصبح المعالجة الخادمية المؤقتة خيارًا عمليًا مع حدود واضحة."),
            ("لا تخلط نتيجة متصفح مع ملف خادمي تلقائيًا", "الأداة المحلية قد تنتج نصًا أو رقمًا في الواجهة وليس ملفًا محفوظًا. المسار الجيد لا يدعي أن هذه النتيجة انتقلت تلقائيًا إلى محول ملفات إذا لم يحدث ذلك فعلًا."),
            ("اختر أبسط مكان ينفذ المهمة", "إذا كان المتصفح يكفي فالمحلي ممتاز. وإذا احتجت محرك مستندات أو OCR، استخدم خدمة تشرح أين تتم المعالجة ومدة بقاء الملفات وما الذي يرسل للذكاء الاصطناعي."),
        ],
        "section_en": [
            "Some tasks do not need an upload at all",
            "Local processing has practical limits",
            "Do not pretend a browser result is automatically a server file",
            "Use the simplest place that can do the job",
        ],
        "paragraph_en": [
            "Changing text case, calculating a percentage, parsing a URL, or cleaning a list can happen entirely in the browser. When server processing is unnecessary, keeping the data on the device makes the privacy model simpler.",
            "OCR, LibreOffice rendering, and heavy PDF conversion depend on engines that are not practical in every browser. Temporary server processing can then be a sensible option when its limits and behavior are clearly explained.",
            "A local utility may produce text or a number in the interface rather than a saved file. A trustworthy workflow should not pretend that result automatically became input to a server file converter when no such handoff occurred.",
            "If the browser is enough, local execution is a strong choice. If a document engine or OCR is required, use a service that explains where processing happens, how long files remain, and what—if anything—is sent to an AI provider.",
        ],
    },
]


def install() -> None:
    from core import blog

    existing = {post["slug"] for post in blog.BLOG_POSTS}
    collisions = existing.intersection(post["slug"] for post in V8_BLOG_POSTS)
    if collisions:
        raise RuntimeError(f"Infinity 8 blog slugs already exist: {sorted(collisions)}")
    blog.BLOG_POSTS.extend(V8_BLOG_POSTS)
    blog.BLOG_BY_SLUG.clear()
    blog.BLOG_BY_SLUG.update({post["slug"]: post for post in blog.BLOG_POSTS})
