"""Implementation-reviewed search content added by the score-95 sprint.

These entries are deliberately limited to useful, distinct search intents.  They are
installed into the canonical editorial registry before page blueprints are imported,
so only pages with implementation-specific guidance become indexable/ad-eligible.
"""
from __future__ import annotations


SCORE95_TOOL_EDITORIAL = {
    "pdf-reorder-pages": {
        "processing": "server_local",
        "engine_ar": "إعادة ترتيب صفحات PDF محليًا باستخدام pypdf مع الحفاظ على ترتيب المستخدم",
        "engine_en": "Server-local PDF page permutation with pypdf while preserving the requested order",
        "sample_urls": ["/static/samples/sample-a.pdf"],
        "sample_names": ["sample-a.pdf"],
        "sample_param": "1",
        "best_for_ar": "إعادة ترتيب صفحات ملف PDF عندما تكون الصفحات صحيحة لكن تسلسلها غير مناسب، مثل تقرير صُدّر بصفحة غلاف في المكان الخطأ أو ملف ممسوح جُمعت صفحاته بترتيب غير صحيح. الأداة مناسبة عندما تريد تغيير التسلسل فقط من دون تحويل الصفحات إلى صور أو إعادة كتابة محتوى النص نفسه.",
        "best_for_en": "Use this when a PDF contains the right pages but they are in the wrong sequence, such as a scanned packet assembled out of order or a report whose cover ended up in the middle. It is a structural page-order operation: it does not rasterize pages, run OCR, or intentionally rewrite the visible page content.",
        "how_ar": "تقرأ الأداة قائمة الترتيب كأرقام صفحات صريحة مفصولة بفواصل، وتحولها إلى ترتيب جديد مع الحفاظ على التسلسل الذي كتبته أنت. يجب أن تظهر كل صفحة مرة واحدة بالضبط؛ بعدها ينسخ المحرك الصفحات إلى PDF جديد حسب هذا الترتيب. توجد حماية تمنع التكرار والصفحات خارج النطاق والقوائم الناقصة حتى لا ينتج ملف فقد بعض الصفحات دون قصد.",
        "how_en": "Infinity parses the comma-separated page numbers as an explicit permutation and preserves the exact sequence you entered. Every source page must appear exactly once. The engine then copies those pages into a new PDF in that order. Duplicate pages, out-of-range numbers, ranges, or incomplete permutations are rejected rather than silently producing a document that drops or duplicates content.",
        "limits_ar": "الأداة تغيّر ترتيب الصفحات ولا تعيد بناء الفهرس النصي أو أرقام الصفحات المطبوعة داخل المحتوى تلقائيًا. إذا كان المستند يحتوي روابط أو فهرسًا يعتمد على رقم صفحة قد تحتاج مراجعتها بعد العملية. كذلك لا يمكن استخدام نطاق مختصر مثل 1-3 هنا؛ المطلوب ترتيب صريح مثل 3,1,2 إذا كان الملف ثلاث صفحات.",
        "limits_en": "This changes physical page sequence only. Printed page numbers, a typed table of contents, bookmarks, and links that refer to old positions may need manual review afterward. The order field is intentionally strict and expects explicit comma-separated page numbers instead of shorthand ranges, because a reorder operation must describe one complete unambiguous permutation.",
        "check_ar": "بعد التنزيل افتح المصغرات الجانبية وراجع الصفحة الأولى والوسط والأخيرة، ثم تأكد أن عدد الصفحات مطابق للأصل. إذا كان الملف رسميًا راجع الفهرس وأرقام الصفحات المطبوعة قبل مشاركته.",
        "check_en": "After download, use the PDF thumbnail pane to inspect the first, middle, and last pages and confirm that the page count still matches the source. For formal documents, recheck any printed numbering, bookmarks, and table-of-contents references before sharing the reordered copy.",
        "faq_ar": [("هل أقدر أكرر نفس الصفحة مرتين؟", "لا. أداة إعادة الترتيب تتطلب ظهور كل صفحة مرة واحدة؛ إذا تحتاج تكرار صفحة فهذا مسار تحرير مختلف."), ("هل تتغير جودة الصفحات؟", "لا يُقصد إعادة تصيير الصفحات كصور؛ يتم نسخ صفحات PDF إلى مستند جديد حسب الترتيب المحدد.")],
        "faq_en": [("Can I repeat the same page twice?", "No. Reordering requires each source page exactly once; duplicating a page is a different editing operation."), ("Does page quality change?", "The workflow copies PDF pages into a new document rather than deliberately rendering every page as an image.")],
    },
    "pdf-page-numbers": {
        "processing": "server_local",
        "engine_ar": "إضافة أرقام صفحات محليًا باستخدام PyMuPDF",
        "engine_en": "Server-local page numbering with PyMuPDF",
        "sample_urls": ["/static/samples/sample-multipage.pdf"],
        "sample_names": ["sample-multipage.pdf"],
        "best_for_ar": "إضافة ترقيم مرئي بسيط إلى ملف PDF قبل التسليم أو الطباعة أو المشاركة، خصوصًا عندما تكون الصفحات نفسها بلا أرقام أو تحتاج نسخة مريحة للمراجعة. تستطيع اختيار موضع أعلى أو أسفل الصفحة، في المنتصف أو جهة اليمين، من دون الحاجة إلى فتح برنامج تحرير مكتبي كامل.",
        "best_for_en": "Use this to add simple visible page numbers before submitting, printing, or reviewing a PDF that has no numbering of its own. You can choose a top or bottom position, centered or right-aligned by the tool's supported presets, without converting the document into Word or rebuilding the underlying page content.",
        "how_ar": "يفتح المحرك PDF ويزور كل صفحة بالتسلسل من 1 حتى آخر صفحة، ثم يضيف رقمًا نصيًا صغيرًا داخل منطقة محددة قرب الحافة حسب الموضع المختار. بعد ذلك يحفظ نسخة PDF جديدة مع تنظيف وضغط بنيوي. الرقم المضاف عنصر فوق الصفحة ولا يغيّر النص الأصلي أو يعيد OCR للمحتوى.",
        "how_en": "The engine opens the PDF, walks the pages from one through the final page, and inserts a small text number into a bounded area near the selected edge. It then saves a new cleaned PDF. The number is an overlay added to the page; the workflow does not run OCR, rewrite existing body text, or renumber a typed table of contents for you.",
        "limits_ar": "الترقيم يبدأ من 1 دائمًا في التنفيذ الحالي ولا توجد بادئة أو نمط أرقام روماني. إذا كانت الصفحة تحتوي محتوى ملاصقًا جدًا للحافة قد يتداخل الرقم بصريًا معه، لذلك راجع الصفحات ذات الهوامش الضيقة. كذلك لن تتغير أرقام الصفحات المكتوبة أصلًا داخل المستند أو مراجع الفهرس تلقائيًا.",
        "limits_en": "The current implementation starts at 1 and does not offer Roman numerals, prefixes, or a custom starting number. Very tight page margins can place the overlay near existing content, so visually inspect edge-heavy layouts. Existing printed numbers and table-of-contents references are not detected or replaced automatically.",
        "check_ar": "راجع صفحة من البداية وواحدة من الوسط وآخر صفحة، وتأكد أن الرقم ظاهر في الموضع المطلوب ولا يغطي نصًا أو توقيعًا. قارن عدد الصفحات مع الأصل قبل الاعتماد على النسخة الجديدة.",
        "check_en": "Inspect an early page, a middle page, and the last page to confirm the number is readable and does not cover text, signatures, or footer content. Verify that the page count remains identical to the original before using the numbered copy as the final document.",
        "faq_ar": [("هل أقدر أختار مكان الرقم؟", "نعم، الخيارات الحالية تشمل مواضع محددة أعلى أو أسفل الصفحة في المنتصف أو جهة اليمين."), ("هل يغيّر ترقيم الفهرس تلقائيًا؟", "لا. الأداة تضيف أرقامًا مرئية للصفحات ولا تعيد كتابة فهرس موجود داخل المحتوى.")],
        "faq_en": [("Can I choose where the number appears?", "Yes. The current presets cover selected top or bottom positions, centered or right-side."), ("Will it update my table of contents?", "No. It adds visible page-number overlays and does not rewrite a table of contents embedded in the document.")],
    },
    "pdf-watermark-text": {
        "processing": "server_local",
        "engine_ar": "إضافة علامة مائية نصية محليًا باستخدام PyMuPDF وخط Unicode عند توفره",
        "engine_en": "Server-local text watermarking with PyMuPDF and a Unicode-capable font when available",
        "sample_urls": ["/static/samples/sample-a.pdf"],
        "sample_names": ["sample-a.pdf"],
        "sample_options": {"text": "CONFIDENTIAL"},
        "best_for_ar": "إضافة عبارة واضحة مثل سري أو مسودة أو نسخة مراجعة فوق صفحات PDF قبل إرسالها للآخرين. هذا مفيد عندما تريد تمييز حالة المستند بصريًا أو تقليل احتمال استخدام نسخة مراجعة كنسخة نهائية، من دون تحويل الملف إلى صور أو فتح برنامج تصميم منفصل.",
        "best_for_en": "Use this to place a visible label such as CONFIDENTIAL, DRAFT, or REVIEW COPY across every PDF page before sharing it. It is useful for clearly communicating document status without opening a design application or intentionally rasterizing the source PDF into images merely to add a mark.",
        "how_ar": "يقرأ المحرك النص الذي تكتبه، يرفض النص الفارغ أو الطويل جدًا، ثم يفتح كل صفحة ويضيف العبارة داخل صندوق مركزي كبير بشفافية منخفضة حتى تبقى الصفحة قابلة للقراءة. يحاول استخدام خط Unicode متوفر على الخادم، ثم يحفظ نسخة PDF جديدة مع تنظيف وضغط بنيوي.",
        "how_en": "The engine validates the watermark text, rejecting empty input and strings longer than the supported limit. It then opens each page and inserts the label in a large central box with restrained opacity so underlying content remains visible. A Unicode-capable server font is used when available before the new PDF is cleaned and saved.",
        "limits_ar": "العلامة المائية في المسار الحالي نصية وبموضع وتصميم ثابتين نسبيًا؛ ليست محرر تصميم كاملًا ولا تضيف شعار صورة. كما أنها وسيلة تنبيه بصري وليست DRM: الشخص الذي يملك أدوات PDF متقدمة قد يستطيع تعديل الملف، لذلك لا تعتمد عليها وحدها لحماية سرية معلومات حساسة.",
        "limits_en": "The current watermark is text-based with a deliberately constrained layout; it is not a full design editor and does not place an image logo. A watermark is also a visual notice, not DRM. Someone with advanced PDF editing tools may be able to modify the file, so do not treat it as the sole protection for sensitive data.",
        "check_ar": "افتح صفحة فاتحة وأخرى فيها صور أو نص كثيف، وتأكد أن العلامة واضحة لكن لا تمنع قراءة المحتوى. راجع الحروف العربية أو الخاصة بعناية إذا استخدمتها، ثم احتفظ بالأصل بدون علامة مائية للرجوع إليه.",
        "check_en": "Inspect both a light page and a visually busy page to ensure the mark is noticeable without making content unreadable. Check non-Latin or special characters carefully when used, and keep the unwatermarked original so the marked copy is never your only source document.",
        "faq_ar": [("هل العلامة المائية تحمي الملف من النسخ؟", "هي تنبيه بصري وليست نظام DRM؛ للحماية من الفتح استخدم تشفير PDF بكلمة مرور عند الحاجة."), ("هل تتحول الصفحات إلى صور؟", "لا. المسار يضيف نصًا فوق صفحات PDF ثم يحفظ PDF جديدًا من دون تعمد تصيير كل صفحة كصورة.")],
        "faq_en": [("Does a watermark prevent copying?", "It is a visual notice, not DRM. Use PDF password protection as well when access control is appropriate."), ("Are pages converted to images?", "No. The workflow adds text to PDF pages and saves a new PDF rather than deliberately rasterizing every page.")],
    },
    "image-strip-metadata": {
        "processing": "server_local",
        "engine_ar": "فك ترميز الصورة وإعادة حفظها كـ PNG نظيف باستخدام Pillow",
        "engine_en": "Server-local image decode and clean PNG rewrite with Pillow",
        "sample_urls": ["/static/samples/sample-image.jpg"],
        "sample_names": ["sample-image.jpg"],
        "best_for_ar": "إنشاء نسخة مشاركة من صورة شائعة من دون الاعتماد على بيانات EXIF والحقول الوصفية الموجودة في الملف الأصلي. يفيد ذلك قبل رفع صورة إلى موقع أو إرسالها عندما تريد تقليل البيانات الجانبية المرافقة للصورة مع الاحتفاظ بالبكسلات المرئية في نسخة PNG جديدة.",
        "best_for_en": "Use this when you want a shareable copy of a common image without carrying over the source file's usual EXIF or metadata fields. It is particularly useful before uploading or sending a photo when you want a clean newly encoded PNG while preserving the visible image rather than depending on the original container metadata.",
        "how_ar": "يفتح Pillow الصورة بعد اجتياز فحص الرفع، يطبق اتجاه EXIF حتى لا تنقلب الصورة بصريًا بعد إزالة البيانات، ثم يعيد ترميز البكسلات إلى ملف PNG جديد من دون نسخ بيانات EXIF الشائعة إلى الناتج. هذا إعادة إنشاء للملف المرئي وليس تعديلًا لنفس الملف في مكانه.",
        "how_en": "Pillow decodes the validated image, applies the EXIF orientation first so the visible result does not unexpectedly rotate when metadata disappears, and then writes a fresh PNG from the pixel data without copying the common EXIF payload into the result. The workflow creates a new file instead of editing the original container in place.",
        "limits_ar": "الناتج PNG حتى لو كان المصدر JPG أو WebP، لذلك قد يزيد الحجم خصوصًا للصور الفوتوغرافية. إزالة البيانات الوصفية الشائعة لا تعني إثباتًا جنائيًا بأن كل معلومة ممكنة اختفت من البكسلات نفسها؛ أي نص أو موقع ظاهر داخل الصورة يبقى ظاهرًا. احتفظ بالأصل إذا كانت بيانات EXIF مهمة للأرشفة.",
        "limits_en": "The output is PNG even when the source is JPEG or WebP, so photographic files can become larger. Metadata removal also cannot erase information that is visibly embedded in the pixels themselves, such as a photographed address or an on-image timestamp. Keep the original when EXIF, capture settings, or archival provenance matters.",
        "check_ar": "افتح الناتج وتأكد من اتجاه الصورة وأبعادها ومناطق الشفافية إن وجدت، ثم افحص خصائص الملف في نظام التشغيل إذا كانت إزالة metadata هي سبب الاستخدام. راجع الصورة بصريًا أيضًا بحثًا عن معلومات شخصية مكتوبة داخل البكسلات نفسها.",
        "check_en": "Open the result and verify orientation, dimensions, and transparency where relevant. If metadata removal is the reason for the task, inspect the new file's properties with your operating system or a metadata viewer as a second check, and remember to review the visible pixels for personal information too.",
        "faq_ar": [("هل تتغير صيغة الصورة؟", "نعم. هذا المسار يكتب نسخة PNG جديدة حتى يتم إنشاء ملف نظيف بدل نسخ حاوية المصدر كما هي."), ("هل يخفي النص أو الوجوه الظاهرة؟", "لا. إزالة metadata لا تعدل المعلومات المرئية داخل البكسلات؛ استخدم أدوات تحرير مناسبة إذا تحتاج إخفاء محتوى مرئي.")],
        "faq_en": [("Does the image format change?", "Yes. This workflow writes a fresh PNG so the result is a newly encoded file rather than a copy of the source container."), ("Does it hide visible text or faces?", "No. Removing metadata does not alter personal information that is visibly present in the pixels.")],
    },
    "image-favicon-pack": {
        "processing": "server_local",
        "engine_ar": "إنشاء حزمة أيقونات مواقع متعددة المقاسات محليًا باستخدام Pillow",
        "engine_en": "Server-local multi-size web icon pack generation with Pillow",
        "sample_urls": ["/static/samples/sample-image.png"],
        "sample_names": ["sample-image.png"],
        "best_for_ar": "إنشاء مجموعة أيقونات لموقع من صورة أو شعار واحد بدل تصغيرها يدويًا عدة مرات. الأداة مناسبة عندما تريد ملفات جاهزة بالمقاسات الشائعة داخل ZIP واحد، مع إعادة أخذ عينات عالية الجودة للصورة المصدر لتسهيل إضافة favicon وأيقونات الأجهزة للمشروع.",
        "best_for_en": "Use this to turn one square-ish logo or source image into a practical set of common web-icon sizes instead of resizing the same graphic manually. The outputs are bundled in one ZIP, making it easier to add favicon and device-icon assets to a website while keeping all generated files together.",
        "how_ar": "يفتح المحرك الصورة ويصحح اتجاهها، ثم ينشئ نسخًا بالمقاسات التي يدعمها مسار الحزمة مستخدمًا إعادة أخذ عينات عالية الجودة. تُحفظ الأيقونات الناتجة بأسماء مستقلة وتُجمع داخل ZIP واحد حتى تنزل الحزمة مرة واحدة. العملية محلية على الخادم ولا تستخدم نموذج صور مولدًا.",
        "how_en": "The engine decodes the image, normalizes its orientation, and resamples it into the icon sizes defined by the pack using a high-quality image resize. Each generated icon is written as its own asset and then bundled into a single ZIP download. This is deterministic image processing on the server, not a generative AI logo redesign.",
        "limits_ar": "الأداة لا تعيد تصميم الشعار ولا تضيف مساحة آمنة ذكية حول العناصر، لذلك صورة طويلة جدًا أو شعار يلامس الحواف قد لا يبدو مثاليًا عند الأحجام الصغيرة. ابدأ بمصدر واضح وعالي الدقة قدر الإمكان، وراجع كل أيقونة المهمة قبل نشرها في موقع إنتاجي.",
        "limits_en": "The pack generator does not redesign the logo or infer smart safe-area padding. A very wide source, tiny source, or artwork that touches the edges can look cramped at small icon sizes. Start with a clear high-resolution source and visually inspect the important generated assets before shipping them on a production site.",
        "check_ar": "بعد فك ZIP افتح أصغر أيقونة وأكبرها وتأكد أن الشعار واضح وغير مقصوص بصريًا، ثم جرّب الملفات الفعلية في المتصفح أو المشروع لأن عرض favicon الصغير قد يختلف كثيرًا عن معاينة الصورة الكبيرة.",
        "check_en": "After extracting the ZIP, inspect both the smallest and largest icon files and confirm the mark remains recognizable. Then test the actual assets in a browser or development build, because a favicon at tiny display size can reveal spacing and legibility problems that are not obvious in a large preview.",
        "faq_ar": [("هل يصمم لي شعارًا جديدًا؟", "لا. الأداة تعيد تحجيم الصورة التي ترفعها إلى حزمة أيقونات؛ لا تولد هوية أو شعارًا جديدًا."), ("ليش النتيجة ZIP؟", "لأن الحزمة تحتوي عدة ملفات ومقاسات، وZIP يجمعها في تنزيل واحد مرتب.")],
        "faq_en": [("Does it design a new logo?", "No. It resizes the source image into a web-icon pack; it does not generate a new brand identity."), ("Why is the result a ZIP?", "The pack contains multiple icon files and sizes, so ZIP keeps them together in one download.")],
    },
    "docx-to-text": {
        "processing": "server_local",
        "engine_ar": "استخراج نص DOCX محليًا باستخدام python-docx",
        "engine_en": "Server-local DOCX text extraction with python-docx",
        "sample_urls": ["/static/samples/sample-document.docx"],
        "sample_names": ["sample-document.docx"],
        "best_for_ar": "استخراج المحتوى المقروء من ملف Word حديث إلى TXT بسيط عندما يهمك النص أكثر من التنسيق، مثل تجهيز محتوى للبحث أو المراجعة أو النسخ إلى نظام لا يحتاج جداول وألوان وأنماط Word. الأداة تقرأ الفقرات وكذلك خلايا الجداول بدل الاقتصار على النص المتسلسل فقط.",
        "best_for_en": "Use this when the readable content of a modern DOCX matters more than Word formatting, for example to prepare plain text for search, review, lightweight processing, or a system that does not need document styles. The extractor includes normal paragraphs and also walks table cells so useful tabular text is not silently ignored.",
        "how_ar": "يفتح python-docx المستند بعد التحقق منه، يجمع الفقرات غير الفارغة بالترتيب، ثم يمر على الجداول ويجمع خلايا كل صف مفصولة بعلامة tab. في النهاية يكتب ملف UTF-8 نصيًا. إذا لم يجد أي نص قابل للاستخراج يوقف العملية برسالة واضحة بدل تنزيل ملف فارغ.",
        "how_en": "The validated DOCX is opened with python-docx. Infinity collects non-empty paragraphs in document order, then walks table rows and joins cell text with tab separators. The combined content is written as UTF-8 plain text. If no extractable text is found, the conversion fails clearly instead of returning a misleading empty file.",
        "limits_ar": "ملف TXT لا يحتفظ بالخطوط والألوان والصور والرؤوس والتذييلات المعقدة أو التخطيط المرئي لصفحات Word. ترتيب العناصر داخل مربعات نص أو كائنات متقدمة قد لا يمثل شكل الصفحة الأصلي. كذلك هذه الأداة لـ DOCX الحديث؛ تحويل DOC القديم يحتاج مسار LibreOffice المناسب أولًا.",
        "limits_en": "Plain text does not preserve fonts, colors, images, page layout, or rich Word styling. Content in unusual drawing objects, text boxes, headers, or other advanced structures may not follow the same visual reading order you see in Word. This extractor targets modern DOCX; legacy DOC files should use the appropriate LibreOffice-backed workflow first.",
        "check_ar": "قارن بداية النص ونهايته مع المستند الأصلي وافتح جدولًا موجودًا فيه إن وجد للتأكد أن الصفوف ظهرت بشكل مفهوم. إذا كان ترتيب بصري معين مهمًا، راجع الناتج يدويًا بدل الاعتماد على TXT كنسخة أرشيفية من Word.",
        "check_en": "Compare the beginning and end of the text with the original document and inspect at least one table when present. If visual reading order matters, review the output manually rather than treating TXT as an archival equivalent of the original Word layout.",
        "faq_ar": [("هل الصور تنتقل إلى TXT؟", "لا. TXT نص فقط؛ الصور والعناصر الرسومية لا يمكن تمثيلها بنفس الشكل في ملف نصي بسيط."), ("هل يستخرج نص الجداول؟", "نعم. التنفيذ الحالي يضيف خلايا كل صف ويفصلها بعلامات tab بعد فقرات المستند.")],
        "faq_en": [("Are images included in TXT?", "No. Plain text cannot preserve Word images or graphic objects as visual content."), ("Does it extract table text?", "Yes. The current implementation appends table rows and separates cells with tab characters.")],
    },
    "xlsx-to-csv": {
        "processing": "server_local",
        "engine_ar": "قراءة أول ورقة Excel وتصدير قيمها إلى CSV محليًا باستخدام openpyxl",
        "engine_en": "Server-local first-sheet Excel value export to CSV with openpyxl",
        "sample_urls": ["/static/samples/sample-sheet.xlsx"],
        "sample_names": ["sample-sheet.xlsx"],
        "best_for_ar": "تحويل جدول Excel إلى CSV عندما تحتاج بيانات مسطحة يمكن فتحها في أنظمة كثيرة أو استيرادها إلى قاعدة بيانات أو أداة تحليل. التنفيذ مناسب خصوصًا لملف تكون بياناته المهمة في الورقة الأولى وتريد القيم المحسوبة الظاهرة بدل الاحتفاظ بصيغ Excel وتنسيقه.",
        "best_for_en": "Use this when an Excel workbook needs to become a flat CSV for import into another service, database, script, or analysis tool. The current workflow is best for workbooks whose relevant table is on the first sheet and where exported cell values matter more than Excel formulas, styling, charts, or workbook structure.",
        "how_ar": "يفتح openpyxl الملف بوضع القراءة فقط ومع data_only حتى يقرأ القيم المخزنة الناتجة عن الصيغ عندما تكون متاحة، ثم يختار أول ورقة ويكتب كل صف إلى CSV بترميز UTF-8. الخلايا الفارغة تتحول إلى حقول فارغة، ولا يتم تشغيل Excel أو تنفيذ ماكرو داخل الملف.",
        "how_en": "openpyxl opens the validated workbook in read-only mode with data_only enabled, so cached formula results are read when the workbook contains them. Infinity selects the first worksheet and writes each row to UTF-8 CSV, turning empty cells into empty fields. Excel itself is not launched and workbook macros are not executed.",
        "limits_ar": "يتم تصدير الورقة الأولى فقط في هذا المسار، ولا تنتقل الألوان والصيغ والمخططات والصور ودمج الخلايا كتنسيق إلى CSV. إذا كانت صيغة لم تُحسب وتُحفظ نتيجتها داخل الملف قبل الرفع فقد تظهر قيمة فارغة أو قديمة لأن openpyxl لا يحسب الصيغ بنفسه.",
        "limits_en": "Only the first worksheet is exported by this workflow. CSV cannot preserve formulas, colors, charts, images, merged-cell presentation, or multiple sheets. Because openpyxl does not calculate formulas, a formula cell whose cached value was not saved by Excel or another spreadsheet app can appear blank or stale in the export.",
        "check_ar": "افتح CSV الناتج وتأكد من أسماء الأعمدة وأول وآخر عدة صفوف، ثم راجع خلايا كانت تحتوي صيغًا في Excel. إذا كان الملف يحتوي عدة أوراق مهمة فتأكد أنك تريد الأولى أو استخدم مسارًا يحافظ على بنية المصنف.",
        "check_en": "Open the CSV and verify column headings plus several rows from the beginning and end. Pay special attention to cells that contained formulas in Excel. If the workbook contains multiple important sheets, confirm that exporting only the first one matches your intended workflow.",
        "faq_ar": [("هل يحول كل أوراق Excel؟", "لا. التنفيذ الحالي يصدر الورقة الأولى إلى CSV واحد."), ("هل تبقى الصيغ؟", "CSV لا يحفظ الصيغ؛ الأداة تقرأ القيم المخزنة للصيغ عندما تكون موجودة في ملف Excel.")],
        "faq_en": [("Does it export every worksheet?", "No. The current tool exports the first worksheet into one CSV file."), ("Are formulas preserved?", "CSV does not preserve formulas. Infinity reads cached formula values when those values exist in the workbook.")],
    },
    "csv-to-json": {
        "processing": "server_local",
        "engine_ar": "تحويل CSV ذي رؤوس أعمدة إلى قائمة JSON محليًا باستخدام مكتبة csv القياسية",
        "engine_en": "Server-local header-based CSV to JSON conversion with Python's standard csv parser",
        "sample_urls": ["/static/samples/sample-data.csv"],
        "sample_names": ["sample-data.csv"],
        "best_for_ar": "تحويل جدول CSV بسيط إلى JSON عندما تحتاج قائمة كائنات يمكن استخدامها في API أو سكربت أو تطبيق ويب. الصف الأول يصبح أسماء الحقول، وكل صف بعده يصبح كائنًا مستقلًا، لذلك المسار مناسب للبيانات الجدولية الواضحة أكثر من الملفات التي تعتمد على تنسيق بصري أو أنواع بيانات معقدة.",
        "best_for_en": "Use this to turn a straightforward CSV table into a JSON array for an API, script, web application, or data pipeline. The first CSV row becomes the object keys and every later row becomes one object, making the workflow a good fit for clearly tabular data rather than files that depend on spreadsheet styling or complex typed structures.",
        "how_ar": "يفتح المحرك الملف بترميز UTF-8 مع دعم BOM ثم يستخدم DictReader لقراءة أسماء الأعمدة من الصف الأول. إذا لم توجد رؤوس يرفض الملف، وإلا يحول الصفوف إلى قائمة dictionaries ويحفظها كـ JSON منسق مع الحفاظ على الحروف العربية. القيم تبقى نصوصًا كما تأتي من CSV ولا يتم تخمين نوعها رقميًا تلقائيًا.",
        "how_en": "The converter opens the file as UTF-8 with BOM support and uses DictReader to obtain field names from the first row. A CSV without headers is rejected. Remaining rows are converted to dictionaries and written as pretty UTF-8 JSON with non-ASCII characters preserved. Values remain strings from the CSV instead of being silently guessed into numeric or date types.",
        "limits_ar": "JSON الناتج عبارة عن قائمة مسطحة من الكائنات ولا يستنتج بنية متداخلة من أسماء الأعمدة. كذلك الأرقام والتواريخ والقيم المنطقية تبقى نصوصًا، وقد تحتاج تحويل أنواع داخل تطبيقك لاحقًا. جودة الناتج تعتمد على أن CSV نفسه يستخدم delimiters واقتباسات ورؤوسًا صحيحة يمكن للمحلل قراءتها.",
        "limits_en": "The output is a flat array of objects and does not infer nested JSON from column names. Numbers, dates, and booleans are intentionally left as strings, so downstream code may need explicit type conversion. Successful parsing also depends on the CSV having valid headers, delimiters, and quoting that the standard CSV parser can interpret.",
        "check_ar": "افتح JSON وتأكد أن المفاتيح تطابق عناوين CSV وأن عدد الكائنات يساوي عدد صفوف البيانات تقريبًا، ثم افحص صفًا يحتوي فاصلة أو نصًا عربيًا أو قيمة فارغة للتأكد أن الاقتباس والترميز فُهما كما تتوقع.",
        "check_en": "Open the JSON and confirm that object keys match the CSV headers and that the object count matches the data rows. Inspect a row containing commas, non-English text, or empty cells to make sure quoting and encoding were interpreted as expected before feeding the result into another system.",
        "faq_ar": [("هل يحول الأرقام إلى نوع number في JSON؟", "لا تلقائيًا؛ قيم CSV تبقى نصوصًا حتى لا نخمن نوع بيانات قد يكون مقصودًا كسلسلة."), ("هل يحتاج CSV إلى رؤوس أعمدة؟", "نعم. الصف الأول يجب أن يوفر أسماء الحقول حتى يمكن بناء كائنات JSON مفهومة.")],
        "faq_en": [("Are numeric values converted to JSON numbers?", "Not automatically. CSV values stay strings so the converter does not guess a type that may be intentionally textual."), ("Does the CSV need headers?", "Yes. The first row supplies field names used as JSON object keys.")],
    },
}


def install() -> None:
    from core.editorial import TOOL_EDITORIAL

    overlap = set(TOOL_EDITORIAL).intersection(SCORE95_TOOL_EDITORIAL)
    if overlap:
        raise RuntimeError(f"score-95 editorial duplicates existing reviewed tools: {sorted(overlap)}")
    TOOL_EDITORIAL.update(SCORE95_TOOL_EDITORIAL)
