"""Manually curated, tool-specific editorial content for high-value indexed pages.

The goal of this module is to keep search-facing tool pages useful and honest.
Every entry is reviewed against the actual conversion handler before release.
"""
from __future__ import annotations

TOOL_EDITORIAL = {
    "pdf-merge": {
        "processing": "server_local",
        "engine_ar": "دمج PDF محلي على خادم Infinity",
        "engine_en": "Infinity server-side PDF merge",
        "sample_urls": ["/static/samples/sample-a.pdf", "/static/samples/sample-b.pdf"],
        "sample_names": ["sample-a.pdf", "sample-b.pdf"],
        "best_for_ar": "تجميع تقارير أو عقود أو واجبات متعددة في ملف PDF واحد مع الحفاظ على ترتيب الملفات الذي تختاره.",
        "best_for_en": "Combining reports, contracts, assignments, or other PDFs into one document while preserving the order you choose.",
        "how_ar": "تقرأ الأداة صفحات كل ملف PDF بالترتيب، ثم تنشئ مستندًا جديدًا وتضيف الصفحات واحدة بعد الأخرى. إذا احتوى أول ملف على بيانات وصفية صالحة، تحاول الأداة الاحتفاظ بها في الناتج. لا تعيد الأداة كتابة محتوى الصفحات أو تحويلها إلى صور.",
        "how_en": "The tool reads each PDF in the selected order, creates a new document, and appends pages one by one. If the first PDF contains usable metadata, the tool attempts to preserve it. Page content is not rasterized or rewritten into images.",
        "limits_ar": "الترتيب النهائي يعتمد على ترتيب الملفات قبل بدء الدمج. الملفات المشفرة أو التالفة قد تفشل في الفتح، لذلك احتفظ بالنسخ الأصلية. الدمج لا يصلح تخطيط الصفحة ولا يزيل الصفحات المكررة تلقائيًا.",
        "limits_en": "Final order follows the file order before processing. Encrypted or damaged PDFs may fail to open, so keep the originals. Merging does not repair page layout or automatically remove duplicate pages.",
        "check_ar": "بعد التنزيل، افتح أول صفحة وآخر صفحة ونقطة الانتقال بين كل ملفين. راجع أرقام الصفحات والفهرس إذا كان المستند رسميًا.",
        "check_en": "After download, inspect the first and last page plus every boundary between source files. Recheck page numbering and the table of contents for formal documents.",
        "faq_ar": [("هل تتغير جودة الصفحات؟", "لا تعيد الأداة تصيير الصفحات كصور؛ هي تجمع صفحات PDF نفسها في ملف جديد."), ("هل أقدر أغير الترتيب؟", "نعم. رتّب الملفات في قائمة الرفع قبل التنفيذ، وسيُستخدم هذا الترتيب في الناتج.")],
        "faq_en": [("Does merging reduce page quality?", "The pages are appended as PDF pages rather than re-rendered as images."), ("Can I control the order?", "Yes. Reorder the upload list before processing; that order is used for the output.")],
    },
    "pdf-split": {
        "processing": "server_local",
        "engine_ar": "تقسيم صفحات PDF محلي على الخادم",
        "engine_en": "Local server-side PDF page split",
        "sample_urls": ["/static/samples/sample-multipage.pdf"],
        "sample_names": ["sample-multipage.pdf"],
        "best_for_ar": "فصل كل صفحة في ملف مستقل عندما تحتاج إرسال صفحة بعينها، أرشفة نماذج منفصلة، أو توزيع أوراق طويلة على ملفات صغيرة.",
        "best_for_en": "Separating every page into its own PDF when you need to send one page, archive forms individually, or break a long packet into smaller files.",
        "how_ar": "تفتح الأداة ملف PDF وتنسخ كل صفحة إلى ملف PDF مستقل باسم مرتب رقميًا، ثم تجمع الملفات الناتجة داخل ZIP واحد لتسهيل التنزيل. لا تُحوّل الصفحات إلى صور ولا تستخدم OCR.",
        "how_en": "The tool opens the PDF, copies every page into a standalone PDF with a numbered filename, then bundles the outputs into one ZIP for convenient download. Pages are not converted to images and OCR is not used.",
        "limits_ar": "النتيجة صفحة واحدة لكل ملف. إذا كنت تريد استخراج صفحات محددة فقط فهذه أداة مختلفة. الروابط أو العناصر التي تعتمد على مستند كامل قد لا تعمل بنفس الشكل بعد الفصل.",
        "limits_en": "The result is one page per PDF. If you only need selected pages, use an extraction workflow instead. Links or document-level structures may not behave the same after splitting.",
        "check_ar": "افتح ملف ZIP وتأكد من عدد الملفات، ثم اختبر صفحة من البداية وواحدة من الوسط وواحدة من النهاية قبل حذف الأصل.",
        "check_en": "Open the ZIP, confirm the file count, and inspect a page from the beginning, middle, and end before deleting the original.",
        "faq_ar": [("ليش النتيجة ZIP؟", "لأن الأداة تنتج ملف PDF مستقل لكل صفحة، وZIP يجمعها في تنزيل واحد."), ("هل يبقى النص قابلًا للتحديد؟", "نعم إذا كان النص قابلًا للتحديد في ملف PDF الأصلي؛ الفصل لا يحوله إلى صورة.")],
        "faq_en": [("Why is the result a ZIP?", "The tool creates one PDF per page, so ZIP packages all outputs into a single download."), ("Does selectable text stay selectable?", "Yes, when it was selectable in the source PDF; splitting does not rasterize pages.")],
    },
    "pdf-compress": {
        "processing": "server_local",
        "engine_ar": "تنظيف وضغط بنية PDF محليًا",
        "engine_en": "Local structural PDF optimization",
        "sample_urls": ["/static/samples/sample-multipage.pdf"],
        "sample_names": ["sample-multipage.pdf"],
        "best_for_ar": "تقليل الحجم الناتج عن البنية والـstreams الزائدة بدون تعمد تخفيض جودة الصور أو إعادة ضغط JPEG بقوة.",
        "best_for_en": "Reducing size caused by redundant PDF structure and streams without deliberately lowering image resolution or aggressively re-encoding JPEG content.",
        "how_ar": "تستخدم الأداة تنظيف كائنات PDF وإزالة البيانات غير الضرورية وضغط الـstreams حيث يمكن، مع الحفاظ على محتوى الصفحات بصريًا. التنفيذ الحالي لا يهدف إلى تصغير أبعاد الصور أو خفض جودتها يدويًا.",
        "how_en": "The tool cleans redundant PDF objects and deflates streams where possible while preserving page content visually. The current implementation does not intentionally downsample image dimensions or manually reduce JPEG quality.",
        "limits_ar": "إذا كان معظم حجم الملف سببه صور عالية الدقة ومضغوطة أصلًا، فقد يكون الانخفاض محدودًا. الأداة ليست بديلًا عن مسار ضغط صور عدواني، وهذا مقصود لحماية الجودة.",
        "limits_en": "If most of the file size comes from already-compressed, high-resolution images, savings may be modest. This is intentionally not an aggressive image-downsampling workflow.",
        "check_ar": "قارن الحجم قبل وبعد، ثم افتح صفحة مليئة بالصور وصفحة تحتوي نصًا صغيرًا. إذا لم ينخفض الحجم كثيرًا فهذا لا يعني أن العملية فشلت؛ قد يكون الملف مضغوطًا جيدًا أصلًا.",
        "check_en": "Compare the before/after size, then inspect an image-heavy page and a page with small text. Limited savings can simply mean the original was already efficiently compressed.",
        "faq_ar": [("هل تخفّض الأداة جودة الصور؟", "التنفيذ الحالي يركز على تنظيف البنية وضغط streams ولا يعيد تصغير الصور عمدًا."), ("ليش أحيانًا ما يصغر الملف كثير؟", "بعض ملفات PDF تكون مضغوطة أصلًا أو يكون معظم حجمها في صور لا يمكن تقليلها دون إعادة ترميزها.")],
        "faq_en": [("Does this lower image quality?", "The current implementation focuses on structural cleanup and stream compression rather than intentional image downsampling."), ("Why can the reduction be small?", "Some PDFs are already compressed or dominated by image data that cannot shrink much without re-encoding.")],
    },
    "pdf-to-jpg": {
        "processing": "server_local",
        "engine_ar": "تصيير صفحات PDF إلى JPG محليًا",
        "engine_en": "Local PDF-to-JPG page rendering",
        "sample_urls": ["/static/samples/sample-multipage.pdf"],
        "sample_names": ["sample-multipage.pdf"],
        "best_for_ar": "تحويل صفحات PDF إلى صور للمعاينة أو المشاركة أو إدخالها في تصميم، عندما لا تحتاج نصًا قابلًا للتحديد داخل الصورة.",
        "best_for_en": "Turning PDF pages into images for previews, sharing, or design workflows when selectable text is not required in the image output.",
        "how_ar": "تقوم الأداة بتصيير كل صفحة من PDF كصورة JPG ثم تجمع الصور في ZIP. الناتج صورة للصفحة، لذلك النص داخلها يصبح بكسلات وليس نصًا قابلًا للتحديد.",
        "how_en": "Each PDF page is rendered into a JPG image and the images are bundled into a ZIP. Because the output is an image, page text becomes pixels rather than selectable text.",
        "limits_ar": "الصور لا تحتفظ بروابط PDF أو طبقة النص أو التعليقات التفاعلية. الملفات ذات الصفحات الكثيرة تنتج عددًا كبيرًا من الصور وقد يكون ZIP كبيرًا.",
        "limits_en": "Images do not preserve PDF links, text layers, or interactive annotations. Long PDFs produce many images and can result in a large ZIP archive.",
        "check_ar": "راجع دقة صفحة فيها نص صغير، وتأكد أن اتجاه الصفحات والألوان مناسب قبل استخدامها في الطباعة أو التصميم.",
        "check_en": "Inspect a page with small text and verify page orientation and colors before using the images for print or design work.",
        "faq_ar": [("هل النص يبقى قابلًا للنسخ؟", "لا، JPG صورة؛ إذا تحتاج نصًا استخدم PDF to Word أو OCR حسب نوع الملف."), ("ليش أحصل على ZIP؟", "لأن كل صفحة تصبح صورة مستقلة وZIP يجمعها في تنزيل واحد.")],
        "faq_en": [("Is the text still copyable?", "No. JPG is an image; use PDF to Word or OCR when you need editable text."), ("Why do I receive a ZIP?", "Each page becomes a separate image, so ZIP packages them into one download.")],
    },
    "image-to-pdf": {
        "processing": "server_local",
        "engine_ar": "تجميع الصور في PDF محليًا",
        "engine_en": "Local image-to-PDF assembly",
        "sample_urls": ["/static/samples/sample-image.png", "/static/samples/sample-image-2.png"],
        "sample_names": ["sample-image.png", "sample-image-2.png"],
        "best_for_ar": "تحويل صور إيصالات أو ملاحظات أو صفحات ممسوحة إلى مستند PDF واحد مرتب يمكن إرساله أو أرشفته.",
        "best_for_en": "Combining receipts, notes, scans, or photos into one ordered PDF that is easier to send and archive.",
        "how_ar": "تقرأ الأداة الصور المدعومة، تصحح اتجاه EXIF عند الحاجة، ثم تنشئ PDF يجمع الصور وفق ترتيب قائمة الرفع. كل صورة تصبح صفحة في المستند الناتج.",
        "how_en": "The tool reads supported images, applies EXIF orientation when needed, and builds a PDF using the upload-list order. Each source image becomes a page in the resulting document.",
        "limits_ar": "الصورة لا تتحول تلقائيًا إلى نص قابل للبحث. إذا كانت صور مستند وتحتاج بحثًا داخل النص، استخدم OCR بعد إنشاء PDF أو استخدم مسار OCR مباشرة.",
        "limits_en": "Images do not automatically become searchable text. For scanned documents that need text search, use OCR after PDF creation or start with an OCR workflow.",
        "check_ar": "تأكد من ترتيب الصور ودورانها قبل التنفيذ، ثم افتح أول وآخر صفحة في PDF الناتج وتحقق من أن القص والحواف مناسبة.",
        "check_en": "Check image order and rotation before processing, then inspect the first and last output pages for cropping and margins.",
        "faq_ar": [("هل PDF الناتج قابل للبحث؟", "ليس بسبب الصور وحدها. تحتاج OCR لإنشاء طبقة نص قابلة للبحث."), ("هل ترتيب الصور مهم؟", "نعم، ترتيب قائمة الرفع هو ترتيب الصفحات في PDF.")],
        "faq_en": [("Is the result searchable?", "Not from the images alone. OCR is required to create searchable text."), ("Does image order matter?", "Yes. Upload-list order becomes page order in the PDF.")],
    },
    "pdf-ocr": {
        "processing": "server_local",
        "engine_ar": "OCR محلي عبر Tesseract على خادم Infinity",
        "engine_en": "Server-local OCR using Tesseract",
        "sample_urls": ["/static/samples/sample-scan.pdf"],
        "sample_names": ["sample-scan.pdf"],
        "best_for_ar": "استخراج نص قابل للتحرير من ملفات PDF الممسوحة ضوئيًا عندما تكون الصفحة صورة ولا يمكن تحديد الكلمات بالماوس.",
        "best_for_en": "Extracting editable text from scanned PDFs where the page is an image and words cannot be selected normally.",
        "how_ar": "تُحوّل صفحات PDF إلى صور مناسبة للقراءة ثم يمررها المحرك إلى Tesseract باستخدام اللغة المختارة. يجمع النص المستخرج في ملف TXT. عملية OCR تخمينية بطبيعتها وقد تحتاج مراجعة بشرية.",
        "how_en": "PDF pages are rendered into images and passed to Tesseract with the selected language. Extracted text is assembled into a TXT file. OCR is inherently probabilistic and should be reviewed.",
        "limits_ar": "الصفحات المائلة أو الضبابية أو ذات الخلفية الداكنة تقلل الدقة، وكذلك الأسماء والأرقام الصغيرة. الحد التشغيلي لعدد صفحات OCR أقل من حد PDF العادي لحماية وقت المعالجة.",
        "limits_en": "Skewed, blurry, low-contrast pages reduce accuracy, especially for names and small numbers. OCR page limits are intentionally lower than general PDF limits to control processing time.",
        "check_ar": "اختبر اسمًا ورقمًا وعنوانًا من الملف الناتج. إذا ظهرت أخطاء كثيرة، حسّن جودة المسح أو جرّب لغة أدق بدل الاعتماد على النتيجة مباشرة.",
        "check_en": "Check a name, a number, and a heading in the output. If errors are frequent, improve scan quality or choose a more precise language before relying on the text.",
        "faq_ar": [("هل OCR دقيق 100%؟", "لا. الدقة تعتمد على جودة الصفحة واللغة والخط، لذلك راجع النص الناتج خصوصًا الأسماء والأرقام."), ("متى أستخدم PDF to Word بدل OCR؟", "إذا كان النص في PDF قابلًا للتحديد أصلًا، PDF to Word غالبًا أنسب من OCR.")],
        "faq_en": [("Is OCR 100% accurate?", "No. Accuracy depends on page quality, language, and typography, so review names and numbers carefully."), ("When should I use PDF to Word instead?", "If text is already selectable in the PDF, PDF to Word is usually more appropriate than OCR.")],
    },
    "image-to-png": {
        "processing": "server_local",
        "engine_ar": "تحويل صور محلي عبر Pillow",
        "engine_en": "Server-local image conversion with Pillow",
        "sample_urls": ["/static/samples/sample-image.jpg"],
        "sample_names": ["sample-image.jpg"],
        "best_for_ar": "تحويل صورة إلى PNG عندما تحتاج حواف واضحة أو صيغة واسعة الدعم أو الحفاظ على الشفافية عندما تكون موجودة في المصدر.",
        "best_for_en": "Converting an image to PNG when you need crisp edges, broad support, or preservation of transparency when the source provides it.",
        "how_ar": "تفتح الأداة الصورة، تصحح اتجاه EXIF، ثم تحفظها بصيغة PNG. التحويل يغيّر الحاوية والترميز لكنه لا يستطيع اختراع شفافية أو تفاصيل غير موجودة في المصدر.",
        "how_en": "The image is opened, EXIF orientation is normalized, and the result is saved as PNG. Conversion changes the container and encoding but cannot invent transparency or detail absent from the source.",
        "limits_ar": "PNG قد يكون أكبر بكثير من JPG للصور الفوتوغرافية. التحويل إلى PNG لا يحسن صورة منخفضة الجودة تلقائيًا ولا يعيد بناء التفاصيل المفقودة.",
        "limits_en": "PNG can be much larger than JPG for photographic content. Converting to PNG does not automatically improve a low-quality source or restore missing detail.",
        "check_ar": "قارن الحجم وشفافية الخلفية بعد التحويل. إذا كان الهدف الويب وصار PNG ضخمًا، جرّب WebP بدلًا منه.",
        "check_en": "Compare file size and transparency after conversion. If the PNG becomes very large for web use, WebP may be a better fit.",
        "faq_ar": [("هل PNG دائمًا أفضل؟", "لا. هو ممتاز للرسومات والشفافية لكنه قد يكون كبيرًا للصور الفوتوغرافية."), ("هل يحسن الجودة؟", "لا يضيف تفاصيل جديدة؛ هو يغيّر الصيغة فقط.")],
        "faq_en": [("Is PNG always better?", "No. It is strong for graphics and transparency but can be large for photos."), ("Does conversion improve quality?", "It does not create new detail; it changes the image format.")],
    },
    "image-to-webp": {
        "processing": "server_local",
        "engine_ar": "تحويل صور إلى WebP محليًا",
        "engine_en": "Server-local WebP conversion",
        "sample_urls": ["/static/samples/sample-image.png"],
        "sample_names": ["sample-image.png"],
        "best_for_ar": "تجهيز صور للويب بصيغة حديثة يمكن أن تقلل الحجم مع الحفاظ على جودة مرئية جيدة في كثير من الحالات.",
        "best_for_en": "Preparing images for the web with a modern format that can reduce file size while retaining good visible quality in many cases.",
        "how_ar": "تقرأ الأداة الصورة عبر Pillow وتعيد حفظها بصيغة WebP. النتيجة مناسبة للمتصفحات الحديثة، لكن الحجم النهائي يعتمد على محتوى الصورة وليس على الامتداد وحده.",
        "how_en": "The source image is read with Pillow and re-saved as WebP. The output is suitable for modern browsers, while final size still depends on image content rather than the extension alone.",
        "limits_ar": "بعض الأنظمة القديمة أو برامج العمل التقليدية قد لا تتعامل مع WebP بنفس سلاسة JPG/PNG. افحص متطلبات النظام الذي سيستقبل الملف قبل الاعتماد عليه.",
        "limits_en": "Some legacy systems and older workflows may not handle WebP as smoothly as JPG or PNG. Check the destination system before standardizing on it.",
        "check_ar": "قارن الحجم والجودة عند الحجم الفعلي الذي ستظهر به الصورة في الموقع، وليس عند تكبيرها بشكل مبالغ فيه.",
        "check_en": "Compare size and quality at the image's real display dimensions instead of judging only at extreme zoom.",
        "faq_ar": [("هل WebP مناسب لكل شيء؟", "هو ممتاز للويب غالبًا، لكن التوافق مع بعض البرامج القديمة يستحق التحقق."), ("هل يصغر الملف دائمًا؟", "غالبًا يكون فعالًا، لكن لا يوجد ضمان لأن النتيجة تعتمد على محتوى الصورة الأصلية.")],
        "faq_en": [("Is WebP right for every workflow?", "It is strong for the web, but older software compatibility is worth checking."), ("Will it always be smaller?", "Often, but not guaranteed; results depend on the source image.")],
    },
    "image-compress": {
        "processing": "server_local",
        "engine_ar": "ضغط صورة محلي على خادم Infinity",
        "engine_en": "Server-local image compression",
        "output_ar": "نفس صيغة المصدر (أو ZIP للدفعة)",
        "output_en": "Source format (or ZIP for batches)",
        "sample_urls": ["/static/samples/sample-image.png"],
        "sample_names": ["sample-image.png"],
        "best_for_ar": "تقليل حجم صورة للمشاركة أو الويب مع الحفاظ على صيغة المصدر قدر الإمكان والتحكم في جودة JPEG وWebP عند استخدامها.",
        "best_for_en": "Reducing an image for sharing or the web while keeping the source format where practical and controlling JPEG/WebP quality when those formats are used.",
        "how_ar": "تفتح الأداة الصورة وتصحح اتجاهها ثم تعيد حفظها بصيغة المصدر: PNG يُحسّن كـPNG، وWebP يُحفظ كـWebP، وJPEG يُحفظ كـJPEG. إعداد الجودة يؤثر مباشرةً في JPEG وWebP، بينما PNG يستخدم تحسينًا غير فقدي بدل تحويله إلى JPG.",
        "how_en": "The tool opens the image, normalizes orientation, and saves it in the source format: PNG stays PNG, WebP stays WebP, and JPEG stays JPEG. The quality control directly affects JPEG/WebP, while PNG uses lossless optimization instead of being converted to JPG.",
        "limits_ar": "النتيجة تعتمد على نوع الصورة وصيغتها؛ PNG الرسومي قد يستفيد من التحسين أكثر أو أقل من صورة فوتوغرافية. ضغط JPEG/WebP بقيمة منخفضة قد يضيف آثارًا بصرية حول النصوص والحواف.",
        "limits_en": "Results depend on the image and its format; a graphic PNG may respond differently from a photograph. Low JPEG/WebP quality values can introduce visible artifacts around text and edges.",
        "check_ar": "قارن الامتداد والحجم قبل وبعد، وافتح الصورة عند حجم العرض الحقيقي. راجع النصوص والحواف والشفافية في PNG قبل اعتماد النتيجة.",
        "check_en": "Compare the extension and size before and after, then view the image at its real display size. Check text, edges, and PNG transparency before relying on the result.",
        "faq_ar": [("هل تتغير الصيغة؟", "لا في المسار المعتاد؛ PNG وWebP وJPEG تُحفظ كل منها بصيغتها المناسبة بدل فرض JPG على الجميع."), ("وش أفضل رقم للجودة؟", "لا يوجد رقم واحد مثالي لـJPEG وWebP؛ ابدأ بقيمة متوسطة ثم قارن الحجم والشكل. PNG يعتمد تحسينًا غير فقدي.")],
        "faq_en": [("Does the format change?", "Not in the normal path: PNG, WebP, and JPEG are each saved in their corresponding format instead of forcing every image to JPG."), ("What quality value should I use?", "There is no universal best value for JPEG/WebP; start in the middle and compare size versus appearance. PNG uses lossless optimization.")],
    },
    "word-to-pdf": {
        "processing": "server_local",
        "engine_ar": "تحويل عبر LibreOffice داخل خادم Infinity",
        "engine_en": "Server-local conversion through LibreOffice",
        "sample_urls": ["/static/samples/sample-document.docx"],
        "sample_names": ["sample-document.docx"],
        "best_for_ar": "إنشاء PDF ثابت من DOC أو DOCX للتسليم الأكاديمي أو المشاركة أو الأرشفة عندما تريد الحفاظ على شكل الصفحات قدر الإمكان.",
        "best_for_en": "Creating a fixed PDF from DOC or DOCX for academic submission, sharing, or archiving when you want page layout preserved as closely as practical.",
        "how_ar": "يرسل الملف إلى LibreOffice المثبت على الخادم ويُفتح في وضع غير تفاعلي ثم يُصدّر إلى PDF. النتيجة تعتمد على الخطوط والبنية الموجودة في المستند الأصلي.",
        "how_en": "The document is opened by the server's LibreOffice installation in headless mode and exported to PDF. Output depends on the fonts and document structures available in the source.",
        "limits_ar": "الخطوط غير المثبتة أو الكائنات المعقدة جدًا قد تؤدي إلى اختلافات في توزيع السطور أو الجداول. الملفات القديمة بصيغة DOC مدعومة لكن تستحق مراجعة إضافية بعد التحويل.",
        "limits_en": "Missing fonts or highly complex objects can change line breaks or table layout. Legacy DOC files are supported but deserve an extra visual review after conversion.",
        "check_ar": "راجع أول وآخر صفحة والجداول والرؤوس والتذييلات وأرقام الصفحات. إذا كان الملف رسميًا، افتحه على جهاز آخر قبل الإرسال.",
        "check_en": "Check the first and last page, tables, headers, footers, and page numbers. For important documents, open the PDF on another device before sending it.",
        "faq_ar": [("هل يدعم DOC القديم؟", "نعم، المسار يقبل DOC وDOCX ويحوّلهما عبر LibreOffice."), ("ليش يتغير خط أحيانًا؟", "إذا كان الخط الأصلي غير متوفر على الخادم، قد يستخدم LibreOffice خطًا بديلًا.")],
        "faq_en": [("Does it support old DOC files?", "Yes. Both DOC and DOCX are accepted and converted through LibreOffice."), ("Why can a font change?", "If the original font is unavailable on the server, LibreOffice may substitute another font.")],
    },
    "zip-create": {
        "processing": "server_local",
        "engine_ar": "إنشاء ZIP محلي على الخادم",
        "engine_en": "Server-local ZIP creation",
        "sample_urls": ["/static/samples/sample-note.txt", "/static/samples/sample-image.png"],
        "sample_names": ["sample-note.txt", "sample-image.png"],
        "best_for_ar": "جمع ملفات متعددة في أرشيف واحد لسهولة النقل أو التسليم بدون تغيير محتوى الملفات الأصلية.",
        "best_for_en": "Bundling multiple files into one archive for easier transfer or submission without changing the original file contents.",
        "how_ar": "تنشئ الأداة أرشيف ZIP وتضيف الملفات المختارة بأسمائها الآمنة. الهدف هنا التجميع والضغط القياسي، وليس تحويل أنواع الملفات داخل الأرشيف.",
        "how_en": "The tool creates a ZIP archive and adds the selected files using safe filenames. The purpose is packaging and standard compression, not converting the files inside the archive.",
        "limits_ar": "بعض الملفات مثل JPG وPDF تكون مضغوطة أصلًا، لذلك قد لا ينخفض الحجم كثيرًا. ZIP لا يوفر تشفير كلمة مرور في هذا المسار الحالي.",
        "limits_en": "Some formats such as JPG and PDF are already compressed, so size savings may be small. This current ZIP workflow does not add password encryption.",
        "check_ar": "بعد التنزيل، افتح الأرشيف وتأكد من عدد الملفات وأسمائها وافتح ملفًا واحدًا على الأقل قبل حذف النسخ الأصلية.",
        "check_en": "After download, open the archive, verify file count and names, and extract at least one file before deleting originals.",
        "faq_ar": [("هل ZIP يصغّر كل الملفات؟", "لا. الملفات المضغوطة أصلًا قد لا تستفيد كثيرًا من ضغط ZIP."), ("هل يضيف كلمة مرور؟", "ليس في هذا المسار الحالي؛ هو مخصص للتجميع والضغط القياسي.")],
        "faq_en": [("Will ZIP shrink every file?", "No. Formats that are already compressed may see little additional reduction."), ("Does this add a password?", "Not in the current workflow; it is designed for standard packaging and compression.")],
    },
    "pdf-password-protect": {
        "processing": "server_local",
        "sample_options": {"password": "Infinity-Demo-2026!"},
        "engine_ar": "تشفير PDF محلي على الخادم",
        "engine_en": "Server-local PDF encryption",
        "sample_urls": ["/static/samples/sample-a.pdf"],
        "sample_names": ["sample-a.pdf"],
        "best_for_ar": "إضافة كلمة مرور فتح إلى PDF قبل مشاركته عندما تريد منع الفتح العرضي من شخص لا يملك كلمة المرور.",
        "best_for_en": "Adding an open password to a PDF before sharing when you want to prevent casual access by someone who does not know the password.",
        "how_ar": "تقرأ الأداة ملف PDF وتكتب نسخة مشفرة جديدة باستخدام كلمة المرور التي تدخلها. كلمة المرور تُرسل ضمن طلب المعالجة ولا تُعرض في الصفحة بعد الإرسال.",
        "how_en": "The tool reads the PDF and writes a new encrypted copy using the password you provide. The password is sent as part of the processing request and is not displayed in the page afterward.",
        "limits_ar": "كلمة المرور ليست بديلًا عن التحكم بالوصول أو إدارة الحقوق، ومن يملك كلمة المرور يستطيع فتح الملف. لا تستخدم كلمة مرور يسهل تخمينها، واحتفظ بها في مكان منفصل وآمن.",
        "limits_en": "A password is not a substitute for full access control or rights management, and anyone who knows it can open the file. Use a strong password and store it separately.",
        "check_ar": "افتح النسخة الناتجة في قارئ PDF مستقل وتأكد أنه يطلب كلمة المرور قبل إرسالها. لا تحذف الأصل حتى تتأكد أن كلمة المرور محفوظة لديك.",
        "check_en": "Open the result in a separate PDF reader and confirm that it asks for the password before sharing it. Keep the original until the password is safely stored.",
        "faq_ar": [("هل تحتفظون بكلمة المرور؟", "لا تُعرض الكلمة بعد الطلب، وتُستخدم ضمن مساحة المعالجة المؤقتة فقط."), ("هل التشفير يمنع النسخ 100%؟", "هو يحمي فتح الملف، لكنه ليس نظام DRM كاملًا ولا يمنع كل أشكال النسخ بعد فتحه.")],
        "faq_en": [("Do you keep the password?", "It is not displayed after submission and is used only within the temporary processing request."), ("Does encryption prevent copying completely?", "It protects file opening, but it is not a full DRM system and cannot prevent all copying after the file is opened.")],
    },
    "ocr-pdf-to-searchable": {
        "processing": "server_local",
        "engine_ar": "OCR محلي وإعادة بناء PDF قابل للبحث",
        "engine_en": "Server-local OCR and searchable PDF rebuild",
        "sample_urls": ["/static/samples/sample-scan.pdf"],
        "sample_names": ["sample-scan.pdf"],
        "best_for_ar": "جعل PDF الممسوح قابلًا للبحث والنسخ مع الحفاظ على شكل الصفحة كصورة قدر الإمكان.",
        "best_for_en": "Making a scanned PDF searchable and copyable while keeping the page's scanned appearance as closely as practical.",
        "how_ar": "تستخدم الأداة OCR لقراءة النص من صفحات المسح ثم تعيد بناء PDF يحتوي على المظهر المرئي وطبقة نص قابلة للبحث. جودة طبقة النص تعتمد على وضوح المسح واللغة.",
        "how_en": "OCR reads text from scanned pages and the tool rebuilds a PDF that retains the visual page while adding searchable text. Text-layer quality depends on scan clarity and language.",
        "limits_ar": "OCR قد يخطئ في الحروف المتشابهة والأرقام والجداول، خصوصًا مع المسح المائل أو منخفض الدقة. لا تعتبر طبقة النص الناتجة نسخة قانونية من النص الأصلي بدون مراجعة.",
        "limits_en": "OCR can misread similar characters, numbers, and tables, especially on skewed or low-resolution scans. Do not treat the generated text layer as authoritative without review.",
        "check_ar": "ابحث داخل PDF الناتج عن اسم ورقم وتاريخ معروفين من المستند. جرّب تحديد سطر ونسخه للتأكد أن الطبقة النصية موجودة.",
        "check_en": "Search the output for a known name, number, and date. Select and copy a line to confirm that the text layer is present.",
        "faq_ar": [("هل شكل الصفحة يتغير؟", "الهدف هو الحفاظ على المظهر المرئي وإضافة طبقة نص، لكن بعض الملفات المعقدة تستحق مراجعة."), ("هل يدعم العربية؟", "نعم، يمكنك اختيار العربية أو الإنجليزية أو الاثنين معًا.")],
        "faq_en": [("Does page appearance change?", "The goal is to retain the visual scan while adding a text layer, though complex files should still be reviewed."), ("Does it support Arabic?", "Yes. Arabic, English, or a combined language mode can be selected.")],
    },
    "pdf-to-docx": {
        "processing": "server_local",
        "engine_ar": "استخراج نص PDF وبناء DOCX محليًا",
        "engine_en": "Local PDF text extraction and DOCX rebuild",
        "sample_urls": ["/static/samples/sample-text.pdf"],
        "sample_names": ["sample-text.pdf"],
        "best_for_ar": "استعادة نص PDF قابل للتحديد في مستند Word قابل للتحرير عندما تكون الأولوية للمحتوى النصي أكثر من التطابق البصري التام.",
        "best_for_en": "Recovering selectable PDF text into an editable Word document when editable content matters more than pixel-perfect visual reproduction.",
        "how_ar": "تستخرج الأداة النص من كل صفحة PDF عبر PyMuPDF وتضعه في مستند DOCX، مع فاصل صفحات بين صفحات المصدر. هذا مسار إعادة بناء نصي وليس محركًا يعيد إنشاء كل عناصر التخطيط المعقدة.",
        "how_en": "The tool extracts text from each PDF page with PyMuPDF and places it into a DOCX, inserting page breaks between source pages. This is a text-rebuild workflow rather than a layout-reconstruction engine.",
        "limits_ar": "الجداول متعددة الأعمدة، الصناديق، الرسومات، وتوزيع النص المعقد قد لا تتحول إلى نفس تخطيط Word. إذا كان PDF صورة ممسوحة فلن يظهر نص مفيد بدون OCR أولًا.",
        "limits_en": "Complex tables, multi-column layouts, positioned boxes, and graphics may not reproduce as Word structures. Image-only scans need OCR before useful text can be recovered.",
        "check_ar": "افتح DOCX وراجع ترتيب الفقرات والعناوين والعربية والجداول. إذا كان المطلوب نسخة مطابقة بصريًا، الاحتفاظ بـPDF قد يكون أفضل من التحويل.",
        "check_en": "Open the DOCX and review paragraph order, headings, Arabic direction, and tables. If exact visual fidelity is the priority, keeping the PDF may be preferable.",
        "faq_ar": [("هل يحافظ على التصميم 100%؟", "لا. الأداة تركز على استخراج النص القابل للتحرير ولا تعيد بناء كل عناصر تخطيط PDF."), ("هل يعمل على PDF الممسوح؟", "إذا كان الملف صورة فقط، استخدم OCR أولًا ثم انتقل إلى مسار التحرير.")],
        "faq_en": [("Does it preserve layout perfectly?", "No. The workflow prioritizes editable text and does not reconstruct every PDF layout element."), ("Does it work on scanned PDFs?", "Image-only scans should go through OCR first before an editable-text workflow.")],
    },
    "pdf-compare": {
        "processing": "server_local",
        "engine_ar": "مقارنة نصية محلية بين ملفي PDF",
        "engine_en": "Server-local text comparison between two PDFs",
        "sample_urls": ["/static/samples/sample-a.pdf", "/static/samples/sample-b.pdf"],
        "sample_names": ["sample-a.pdf", "sample-b.pdf"],
        "best_for_ar": "مراجعة تغييرات النص بين نسختين من PDF مثل عقد أو تقرير أو سياسة، عندما تكون الفروقات النصية هي الأهم.",
        "best_for_en": "Reviewing text changes between two PDF versions, such as a contract, report, or policy, when textual differences matter most.",
        "how_ar": "تستخرج الأداة النص من الملفين ثم تنشئ مقارنة موحدة سطرًا بسطر. النتيجة تقرير TXT يوضح الإضافات والحذف. المقارنة ليست مقارنة بصرية للبكسلات أو مواضع العناصر.",
        "how_en": "Text is extracted from both PDFs and compared line by line with a unified diff. The result is a TXT report showing additions and removals. This is not a pixel-level visual comparison.",
        "limits_ar": "تغيير ترتيب النص داخل PDF أو اختلاف استخراج الأعمدة قد يظهر كفرق حتى لو بدت الصفحات متشابهة بصريًا. PDF الممسوح يحتاج OCR قبل مقارنة النص.",
        "limits_en": "Different text extraction order or column structure can appear as differences even when pages look visually similar. Scanned PDFs require OCR before meaningful text comparison.",
        "check_ar": "استخدم التقرير لتحديد مواضع التغيير، ثم افتح الملفين يدويًا للتحقق من الفقرة الأصلية إذا كان التغيير حساسًا أو قانونيًا.",
        "check_en": "Use the report to locate changes, then inspect the original passages manually when the difference is sensitive or legally important.",
        "faq_ar": [("هل يقارن التصميم؟", "لا، المقارنة الحالية نصية وليست مقارنة صور أو مواضع."), ("وش يصير إذا الملفان متطابقان؟", "يصدر تقريرًا واضحًا يخبرك أن النصين متطابقان بدل ملف فارغ.")],
        "faq_en": [("Does it compare visual layout?", "No. The current comparison is text-based rather than pixel- or position-based."), ("What if both files match?", "The report explicitly says no text differences were found instead of returning an empty file.")],
    },
    "pdf-redact": {
        "processing": "server_local",
        "sample_param": "CONFIDENTIAL",
        "engine_ar": "تنقيح PDF حقيقي محليًا عبر PyMuPDF",
        "engine_en": "Server-local true PDF redaction with PyMuPDF",
        "sample_urls": ["/static/samples/sample-sensitive.pdf"],
        "sample_names": ["sample-sensitive.pdf"],
        "best_for_ar": "إزالة كلمات أو أرقام حساسة متكررة من PDF نصي قبل مشاركة نسخة من المستند.",
        "best_for_en": "Removing repeated sensitive words or numbers from a text-based PDF before sharing a sanitized copy.",
        "how_ar": "تبحث الأداة عن العبارات التي تكتبها، تضيف علامات تنقيح على مواضعها، ثم تطبق التنقيح فعليًا وتكتب نسخة PDF جديدة. هذا يختلف عن رسم مستطيل أسود فوق النص بدون حذفه.",
        "how_en": "The tool searches for the terms you provide, adds redaction annotations at the matched locations, applies the redactions, and writes a new PDF. This is different from merely drawing a black rectangle over hidden text.",
        "limits_ar": "البحث يعتمد على النص القابل للاستخراج؛ الكلمات داخل صورة أو مسح ضوئي لن تُكتشف بدون OCR. المطابقة تعتمد على العبارة كما تظهر في طبقة النص، لذلك راجع الناتج يدويًا دائمًا.",
        "limits_en": "Search relies on extractable text; words inside images or scans are not found without OCR. Matching depends on the PDF text layer, so the result must always be reviewed manually.",
        "check_ar": "بعد التنقيح، ابحث عن كل كلمة حساسة في PDF الناتج وحاول نسخ النص من المنطقة المنقحة. إذا كان المستند حساسًا جدًا، نفّذ مراجعة بشرية صفحة صفحة.",
        "check_en": "After redaction, search the result for every sensitive term and try copying text from each redacted area. For highly sensitive documents, review every page manually.",
        "faq_ar": [("هل هو مجرد مربع أسود؟", "لا. المحرك يطبق PDF redactions على المطابقات قبل حفظ النسخة الجديدة."), ("هل ينقح النص داخل الصور؟", "لا تلقائيًا؛ الصور تحتاج OCR أو معالجة مختلفة قبل البحث النصي.")],
        "faq_en": [("Is this just a black box overlay?", "No. The engine applies PDF redactions to matched text before saving the new copy."), ("Does it redact text inside images?", "Not automatically. Image content requires OCR or another workflow before text matching.")],
    },
    "image-upscale": {
        "processing": "server_local",
        "engine_ar": "تكبير محلي بخوارزمية LANCZOS",
        "engine_en": "Server-local LANCZOS image upscaling",
        "sample_urls": ["/static/samples/sample-image-small.png"],
        "sample_names": ["sample-image-small.png"],
        "best_for_ar": "تكبير أبعاد صورة 2× إلى 4× عندما تحتاج مساحة أكبر للعرض أو التحرير، مع إعادة أخذ عينات عالية الجودة بدل تكبير بكسلات بسيط.",
        "best_for_en": "Increasing image dimensions by 2× to 4× when you need a larger canvas, using high-quality resampling rather than simple nearest-neighbor enlargement.",
        "how_ar": "تستخدم الأداة Pillow مع LANCZOS لإعادة حساب البكسلات بأبعاد أكبر وتحفظ الناتج PNG. هذه تقنية إعادة أخذ عينات وليست نموذج ذكاء اصطناعي يعيد اختراع تفاصيل الوجه أو النص.",
        "how_en": "The tool uses Pillow with LANCZOS resampling to calculate a larger pixel grid and saves the result as PNG. This is resampling, not a generative AI model that invents new facial or text detail.",
        "limits_ar": "الصورة الضبابية أو الصغيرة جدًا لن تصبح حادة فجأة. التكبير يزيد الأبعاد ويقلل التعرج مقارنة بتكبير بسيط لكنه لا يستعيد تفاصيل مفقودة من المصدر.",
        "limits_en": "A tiny or blurry source does not suddenly become truly detailed. Upscaling increases dimensions and smooths interpolation but cannot restore information that was never present.",
        "check_ar": "قارن الصورة عند 100%، خصوصًا النصوص والحواف والوجوه. إذا كان هدفك طباعة كبيرة، اختبر الدقة الفعلية بدل الاعتماد على عدد البكسلات وحده.",
        "check_en": "Compare the result at 100%, especially text, edges, and faces. For large print, evaluate real print resolution rather than pixel count alone.",
        "faq_ar": [("هل يستخدم AI؟", "لا. هذه الأداة تستخدم LANCZOS عالي الجودة، وليس نموذج توليدي لإضافة تفاصيل جديدة."), ("كم أكبر الصورة؟", "العامل الحالي من 2× إلى 4× حسب اختيارك.")],
        "faq_en": [("Does this use AI?", "No. It uses high-quality LANCZOS resampling rather than a generative model."), ("How much can I enlarge?", "The current scale factor is 2× to 4×.")],
    },
    "image-watermark": {
        "processing": "server_local",
        "engine_ar": "إضافة علامة مائية محليًا عبر Pillow",
        "engine_en": "Server-local watermark rendering with Pillow",
        "sample_urls": ["/static/samples/sample-image.png"],
        "sample_names": ["sample-image.png"],
        "best_for_ar": "إضافة اسم أو عبارة قصيرة كعلامة مائية واضحة قبل نشر صورة أو إرسال نسخة معاينة.",
        "best_for_en": "Adding a short name or phrase as a visible watermark before publishing an image or sending a preview copy.",
        "how_ar": "تنشئ الأداة طبقة شفافة فوق الصورة وتضع النص قرب الزاوية السفلية داخل خلفية داكنة شبه شفافة، ثم تحفظ الناتج PNG. النص يندمج في البكسلات النهائية.",
        "how_en": "A transparent overlay is created above the source image, the text is drawn near the lower corner on a translucent dark backing, and the final image is saved as PNG. The watermark becomes part of the output pixels.",
        "limits_ar": "العلامة المائية المرئية لا تمنع القص أو التحرير المتقدم، ولا تعتبر نظام حماية حقوق رقمية. النص الطويل جدًا قد يكون غير مناسب للصورة الصغيرة.",
        "limits_en": "A visible watermark does not prevent cropping or advanced editing and is not DRM. Very long text can be unsuitable for small images.",
        "check_ar": "راجع التباين في المناطق الفاتحة والداكنة وتأكد أن العلامة لا تغطي جزءًا مهمًا من الصورة قبل النشر.",
        "check_en": "Check contrast over both bright and dark areas and make sure the mark does not cover important content before publishing.",
        "faq_ar": [("هل يمنع سرقة الصورة؟", "هو علامة بصرية وردع بسيط، وليس حماية تقنية تمنع نسخ الصورة."), ("وش صيغة الناتج؟", "الناتج PNG للحفاظ على جودة الطبقة المرسومة.")],
        "faq_en": [("Does it stop image theft?", "It is a visible deterrent, not a technical system that prevents copying."), ("What is the output format?", "The result is PNG to preserve the rendered overlay cleanly.")],
    },
    "xlsx-to-html": {
        "processing": "server_local",
        "engine_ar": "قراءة Excel وبناء HTML محليًا",
        "engine_en": "Server-local Excel read and HTML generation",
        "sample_urls": ["/static/samples/sample-sheet.xlsx"],
        "sample_names": ["sample-sheet.xlsx"],
        "best_for_ar": "تحويل بيانات ورقة Excel إلى جدول HTML يمكن معاينته أو تضمينه كنقطة بداية في صفحة ويب.",
        "best_for_en": "Turning spreadsheet data into HTML tables that can be previewed or used as a starting point for a web page.",
        "how_ar": "تفتح الأداة ملف XLSX عبر openpyxl وتقرأ قيم الخلايا ثم تولد HTML يمثل البيانات. الهدف نقل المحتوى الجدولي، وليس محاكاة كل تنسيق Excel أو وحدات الماكرو.",
        "how_en": "The XLSX is opened with openpyxl, cell values are read, and HTML is generated to represent the tabular content. The goal is data transfer rather than reproducing every Excel style or macro.",
        "limits_ar": "المعادلات قد تظهر كقيم أو نصوص حسب الملف، والتنسيقات المتقدمة والمخططات ووحدات الماكرو لا تتحول إلى تطبيق ويب كامل. راجع HTML قبل نشره.",
        "limits_en": "Formulas may surface as values or text depending on the workbook, and advanced styling, charts, or macros are not converted into a full web application. Review the HTML before publishing.",
        "check_ar": "افتح الناتج في المتصفح وراجع رؤوس الأعمدة والخلايا الفارغة والأرقام والتواريخ، ثم طبّق CSS مناسب إذا كنت ستنشره للجمهور.",
        "check_en": "Open the result in a browser and check headers, empty cells, numbers, and dates. Add appropriate CSS before publishing it publicly.",
        "faq_ar": [("هل يحتفظ بتنسيق Excel كامل؟", "لا. يركز المسار على بنية البيانات الجدولية أكثر من محاكاة كل تنسيق."), ("هل يشغّل الماكرو؟", "لا. ملفات XLSX تُقرأ كبيانات ولا يتم تشغيل ماكرو أو كود داخل المصنف.")],
        "faq_en": [("Does it preserve every Excel style?", "No. The workflow focuses on tabular data structure rather than full visual emulation."), ("Does it run macros?", "No. Workbook data is read without executing macros or embedded code.")],
    },
    "ocr-image-to-markdown": {
        "processing": "server_local",
        "engine_ar": "OCR محلي ثم إخراج Markdown",
        "engine_en": "Server-local OCR with Markdown output",
        "sample_urls": ["/static/samples/sample-scan.png"],
        "sample_names": ["sample-scan.png"],
        "best_for_ar": "تحويل صورة صفحة أو ملاحظات مطبوعة إلى نص Markdown سهل التحرير والنقل إلى أنظمة التوثيق.",
        "best_for_en": "Turning a photographed or scanned page into editable Markdown that is easy to clean up and move into documentation systems.",
        "how_ar": "يمرر المحرك الصورة إلى Tesseract باللغة المحددة، ثم يكتب النص الناتج داخل ملف Markdown بسيط. الأداة لا تستنتج بنية معقدة مثل الجداول أو مستويات العناوين بدقة مضمونة.",
        "how_en": "The image is passed to Tesseract with the selected language and the recognized text is written to a simple Markdown file. Complex table structure and heading levels are not inferred with guaranteed accuracy.",
        "limits_ar": "الخط اليدوي، الميل، الظلال، الجداول، والنصوص الصغيرة تقلل الدقة. Markdown الناتج نقطة بداية للتحرير وليس نسخة منشورة جاهزة دائمًا.",
        "limits_en": "Handwriting, skew, shadows, tables, and very small text reduce accuracy. The Markdown output is a starting point for editing rather than always being publication-ready.",
        "check_ar": "راجع الأرقام والأسماء وعلامات الترقيم، ثم أعد تنسيق العناوين والقوائم يدويًا إذا كان المستند يحتاج بنية نظيفة.",
        "check_en": "Review numbers, names, and punctuation, then manually fix headings and lists when the document needs a clean structure.",
        "faq_ar": [("هل يحافظ على الجداول كجداول Markdown؟", "ليس بشكل مضمون؛ OCR يركز على النص ويحتاج المحتوى المنظم إلى مراجعة."), ("هل يدعم العربي والإنجليزي؟", "نعم، مع إمكانية اختيار اللغة المناسبة لمسار OCR.")],
        "faq_en": [("Does it preserve tables as Markdown tables?", "Not reliably. OCR prioritizes text recognition, so structured content needs review."), ("Does it support Arabic and English?", "Yes. The OCR language can be selected to match the document.")],
    },
    "tar-gzip-create": {
        "processing": "server_local",
        "engine_ar": "إنشاء TAR.GZ محلي عبر Python",
        "engine_en": "Server-local TAR.GZ creation with Python",
        "sample_urls": ["/static/samples/sample-note.txt", "/static/samples/sample-sheet.xlsx"],
        "sample_names": ["sample-note.txt", "sample-sheet.xlsx"],
        "best_for_ar": "تجميع ملفات متعددة في أرشيف TAR ثم ضغطه بـGZIP، وهو تنسيق شائع في أنظمة Linux والنقل التقني والنسخ الاحتياطية الصغيرة.",
        "best_for_en": "Bundling multiple files into a TAR archive and compressing it with GZIP, a common format in Linux, technical transfer, and small backup workflows.",
        "how_ar": "تنشئ الأداة أرشيف TAR.GZ وتضيف الملفات المختارة بأسماء آمنة. TAR يجمع الملفات، وGZIP يضغط الأرشيف الناتج. لا تعدل محتوى الملفات الموجودة داخله.",
        "how_en": "The tool creates a TAR.GZ archive and adds the selected files with safe names. TAR packages the files and GZIP compresses the archive. File contents are not converted or rewritten.",
        "limits_ar": "TAR.GZ أقل شيوعًا لدى المستخدمين على Windows من ZIP، وبعض المستلمين قد يحتاجون برنامجًا يدعمه. الملفات المضغوطة أصلًا قد لا تنخفض أحجامها كثيرًا.",
        "limits_en": "TAR.GZ is less familiar to some Windows users than ZIP and may require compatible extraction software. Already-compressed files may not shrink much further.",
        "check_ar": "فك الأرشيف محليًا وتأكد من الأسماء وعدد الملفات قبل الاعتماد عليه لنسخة احتياطية أو تسليم تقني.",
        "check_en": "Extract the archive locally and verify filenames and file count before relying on it for backup or technical delivery.",
        "faq_ar": [("وش الفرق عن ZIP؟", "TAR يجمع الملفات ثم GZIP يضغط الأرشيف؛ ZIP يجمع ويضغط ضمن تنسيق واحد أكثر شيوعًا للمستخدم العادي."), ("هل يغير الملفات؟", "لا. الملفات تُضاف إلى الأرشيف كما هي ضمن حدود التحقق الأمني.")],
        "faq_en": [("How is it different from ZIP?", "TAR packages files and GZIP compresses the package, while ZIP combines packaging and compression in a format more familiar to general users."), ("Does it modify the files?", "No. Files are archived as-is after security validation.")],
    },
}


def get_tool_editorial(tool_id: str):
    return TOOL_EDITORIAL.get(tool_id)


def reviewed_tool_ids() -> set[str]:
    return set(TOOL_EDITORIAL)
