"""Additional implementation-reviewed tool content for the score-90 sprint.

Kept separate from the historical editorial module so new search-facing pages can be
reviewed and rolled back as one unit.  ``install()`` mutates the canonical registry
before page blueprints are imported.
"""
from __future__ import annotations


SCORE90_TOOL_EDITORIAL = {
    "pdf-repair": {
        "processing": "server_local",
        "engine_ar": "إعادة كتابة وتنظيف بنية PDF محليًا باستخدام PyMuPDF",
        "engine_en": "Local PDF structure rewrite and cleanup with PyMuPDF",
        "sample_urls": ["/static/samples/sample-a.pdf"],
        "sample_names": ["sample-a.pdf"],
        "best_for_ar": "إعادة حفظ ملف PDF يفتح بصعوبة أو يحتوي بنية داخلية غير مرتبة، عندما تريد محاولة تنظيف الكائنات الزائدة وإعادة كتابة الملف قبل تجربة التحويل أو المشاركة من جديد. الأداة مناسبة للإصلاح البنيوي الخفيف وليست وسيلة لاسترجاع محتوى مفقود من ملف محطم بالكامل.",
        "best_for_en": "Best for a PDF that opens inconsistently or appears to contain messy internal structure and you want a clean rewrite before converting or sharing it again. The tool is useful for light structural repair: it rewrites the document, cleans redundant objects, and deflates streams. It is not a forensic recovery system and cannot recreate pages or content that are already missing from a severely corrupted source file.",
        "how_ar": "يفتح المحرك ملف PDF ثم يحفظ نسخة جديدة مع تنظيف قوي للكائنات غير المستخدمة، ضغط الـstreams وتنظيف البنية. لا يحول الصفحات إلى صور ولا يعيد OCR للنص، لذلك الهدف هو إصلاح الحاوية والبنية قدر الإمكان مع إبقاء محتوى الصفحات كما يستطيع المحرك قراءته.",
        "how_en": "The engine opens the PDF with PyMuPDF and writes a new PDF using garbage cleanup, stream deflation, and structural cleaning. It does not rasterize pages, run OCR, or intentionally redesign the document. That means selectable text and vector content can remain intact when the source is readable, while malformed or redundant internal objects are discarded during the rewrite.",
        "limits_ar": "إذا كان الملف لا يمكن فتحه أصلًا، أو كانت صفحات داخله ناقصة، أو كانت البيانات نفسها تالفة، فقد لا يمكن إصلاحه. كذلك قد تتغير بعض الخصائص المتقدمة المرتبطة ببنية الملف عند إعادة الكتابة، لذلك لا تستخدم الناتج بدل النسخة الأصلية قبل المراجعة.",
        "limits_en": "Repair is best effort. A file that cannot be parsed at all, has missing page data, or contains irrecoverably damaged streams may still fail. A structural rewrite can also affect unusual document-level features, so the repaired file should be treated as a new copy rather than a replacement for the only original you have.",
        "check_ar": "افتح الناتج وانتقل لأول صفحة ووسط الملف وآخر صفحة، ثم جرّب البحث وتحديد النص وفتح أي روابط مهمة. إذا كان الملف رسميًا، قارن عدد الصفحات والحجم مع الأصل قبل الاعتماد على النسخة الجديدة.",
        "check_en": "Open the repaired result and inspect the first, middle, and last pages. Test text selection, search, and any important links or annotations you rely on. For formal documents, compare the page count and visible content against the original before deleting anything; successful download only proves the rewritten PDF passed Infinity's output checks.",
        "faq_ar": [("هل يعيد إنشاء الصفحات المفقودة؟", "لا. الأداة تنظف وتعيد كتابة ما يستطيع محرك PDF قراءته، لكنها لا تستطيع اختراع محتوى غير موجود."), ("هل يحول PDF إلى صور؟", "لا. مسار الإصلاح يعيد حفظ بنية PDF ولا يتعمد تصيير الصفحات كصور.")],
        "faq_en": [("Can it restore missing pages?", "No. It rewrites content the PDF engine can read; it cannot reconstruct data that is no longer present."), ("Does repair turn pages into images?", "No. This workflow rewrites the PDF structure rather than deliberately rasterizing every page.")],
    },
    "pdf-to-png": {
        "processing": "server_local",
        "engine_ar": "تصيير كل صفحة PDF إلى PNG محليًا بدقة ثابتة",
        "engine_en": "Local PDF page rendering to PNG at a fixed practical resolution",
        "sample_urls": ["/static/samples/sample-multipage.pdf"],
        "sample_names": ["sample-multipage.pdf"],
        "best_for_ar": "تحويل صفحات PDF إلى صور PNG عندما تحتاج نسخة بكسلية واضحة للعرض داخل تصميم أو منصة لا تتعامل جيدًا مع PDF. PNG مناسب خصوصًا للرسومات ولقطات الشاشة والنصوص الحادة، لكن الناتج لم يعد مستند PDF قابلًا للبحث أو التحديد.",
        "best_for_en": "Best when each PDF page needs to become a standalone PNG for a design workflow, preview system, presentation, or service that does not accept PDF. PNG is lossless and can keep sharp interface graphics and text-looking pixels cleaner than JPEG, but the output is still an image: it no longer contains the original selectable PDF text layer, links, or document structure.",
        "how_ar": "يفتح المحرك PDF ويصيّر كل صفحة إلى bitmap باستخدام PyMuPDF عند دقة عملية تقارب 150 DPI، ثم يحفظ كل صفحة PNG مستقلة. إذا كان الملف متعدد الصفحات، يجمع المحرك الصور الناتجة داخل ZIP واحد لتسهيل التنزيل بدل بدء تنزيل منفصل لكل صفحة.",
        "how_en": "Infinity opens the PDF with PyMuPDF, renders each page to a bitmap at a practical 150-DPI scale, and writes one PNG per page. Multi-page documents therefore create multiple output files, which the conversion engine packages into a single ZIP. No OCR step is added during this conversion, and interactive PDF features do not survive the page render.",
        "limits_ar": "ملفات PDF الطويلة قد تنتج ZIP كبيرًا لأن PNG لا يستخدم ضغطًا ضياعيًا. الروابط والتعليقات وطبقة النص لا تنتقل إلى الصور، كما أن الدقة محددة لمسار الويب وليست بديلًا عن تصدير طباعة احترافي بدقة عالية جدًا.",
        "limits_en": "Long documents can produce a large ZIP because PNG uses lossless compression. Hyperlinks, form controls, annotations, and the selectable text layer are not preserved. The renderer uses a practical web-oriented resolution rather than an unlimited print-production DPI, so inspect fine print before using the images for high-resolution commercial printing.",
        "check_ar": "بعد فك ZIP افتح صفحة فيها أصغر نص أو خطوط رفيعة وكبّرها، ثم راجع اتجاه الصفحة والألوان وعدد الصور الناتجة. يجب أن يساوي عدد صور PNG عدد صفحات PDF التي تمت معالجتها.",
        "check_en": "After opening the ZIP, inspect the page with the smallest text or thinnest lines at zoom, verify orientation and colors, and confirm that the PNG count matches the processed PDF page count. If you need copyable text rather than pixels, switch to PDF-to-Word or an OCR workflow instead.",
        "faq_ar": [("ليش النتيجة ZIP؟", "لأن كل صفحة تصبح ملف PNG مستقلًا، وZIP يجمعها في تنزيل واحد."), ("هل النص يبقى قابلًا للنسخ؟", "لا. PNG صورة؛ استخدم مسار نص أو OCR إذا كان هدفك تحرير النص.")],
        "faq_en": [("Why is the result a ZIP?", "Each page becomes a separate PNG, so Infinity bundles the page images into one download."), ("Is the text still selectable?", "No. PNG stores pixels; use a text extraction, Word, or OCR workflow when you need editable text.")],
    },
    "image-to-jpg": {
        "processing": "server_local",
        "engine_ar": "تحويل صور محلي باستخدام Pillow مع تصحيح اتجاه EXIF",
        "engine_en": "Local Pillow image conversion with EXIF orientation correction",
        "sample_urls": ["/static/samples/sample-image.png"],
        "sample_names": ["sample-image.png"],
        "best_for_ar": "تحويل PNG أو WebP أو صور شائعة أخرى إلى JPG عندما تحتاج توافقًا واسعًا وحجمًا مناسبًا للمشاركة. المسار مفيد للصور الفوتوغرافية، لكنه ليس مناسبًا إذا كنت تحتاج شفافية لأن JPEG لا يدعم قناة alpha.",
        "best_for_en": "Best for converting PNG, WebP, TIFF, BMP, or another supported image into widely compatible JPEG for sharing, uploading, or older applications. The encoder uses a practical high-quality setting and corrects EXIF orientation first. JPEG is usually a good fit for photographs, but it is not the right choice when you must preserve transparent pixels or lossless source data.",
        "how_ar": "يفتح Pillow الصورة ويتحقق من اتجاه EXIF ويطبقه، ثم يحولها إلى RGB. إذا كانت الصورة تحتوي شفافية، توضع فوق خلفية بيضاء قبل حفظ JPG، وبعدها يستخدم المحرك جودة 92 مع optimize وprogressive للحصول على ملف عملي للويب.",
        "how_en": "Pillow decodes the validated image, applies EXIF orientation, and converts the result to RGB. Sources with transparency are composited onto a white background because JPEG has no alpha channel. Infinity then saves a JPEG at quality 92 with optimization and progressive encoding. The conversion changes the encoding format; it does not run AI enhancement or invent missing detail.",
        "limits_ar": "الشفافية تتحول إلى أبيض، وJPEG ضغط ضياعي لذلك قد تتغير بعض البكسلات حتى عند جودة عالية. كما أن البيانات الوصفية ليست هدفًا للحفظ في هذا المسار؛ إذا كانت EXIF مهمة لك احتفظ بالأصل ولا تعتبر JPG الجديد أرشيفًا مطابقًا.",
        "limits_en": "Transparency becomes white and JPEG is a lossy format, so pixel values can change even at high quality. This workflow also does not promise preservation of every metadata field from the original file. Keep the source if EXIF, transparency, layers, or exact lossless pixels are important to your archival workflow.",
        "check_ar": "راجع المناطق التي كانت شفافة، الحواف الدقيقة والنصوص الصغيرة، ثم قارن الأبعاد مع الأصل. إذا كان هدفك شعارًا بخلفية شفافة فاختر PNG بدل JPG.",
        "check_en": "Inspect formerly transparent areas, sharp edges, and small text, then confirm that the dimensions match the source. If the result is a logo, icon, or graphic that depends on transparency, choose PNG instead of JPEG; for photographs, compare file size and visible artifacts at normal viewing size.",
        "faq_ar": [("وش يصير للخلفية الشفافة؟", "JPEG لا يدعم الشفافية، لذلك يضع هذا المسار الصورة فوق خلفية بيضاء."), ("هل يحسن جودة الصورة بالذكاء؟", "لا. هذه أداة تحويل صيغة وليست أداة توليد أو تحسين تفاصيل بالذكاء الاصطناعي.")],
        "faq_en": [("What happens to transparency?", "JPEG has no alpha channel, so transparent source pixels are composited onto white."), ("Does this use AI to improve the image?", "No. It is a deterministic format conversion, not an AI detail-generation workflow.")],
    },
    "image-resize": {
        "processing": "server_local",
        "engine_ar": "تغيير أبعاد محلي باستخدام Pillow مع الحفاظ على النسبة",
        "engine_en": "Local Pillow resize that preserves aspect ratio",
        "sample_urls": ["/static/samples/sample-image.png"],
        "sample_names": ["sample-image.png"],
        "sample_param": "800",
        "best_for_ar": "تقليل أبعاد صورة كبيرة قبل رفعها لموقع أو إرسالها أو إدخالها في مستند، مع الحفاظ على نسبة العرض إلى الارتفاع. أنت تحدد أقصى بعد، والأداة تصغّر الصورة لتدخل داخل هذا الحد بدون تمديدها أو تشويهها.",
        "best_for_en": "Best for reducing a large image before a website upload, email, document, or LMS submission while keeping the original aspect ratio. You choose one maximum dimension and Infinity fits the image inside that width-and-height box. This avoids stretching and is intentionally a downsize workflow rather than a canvas editor where width and height are forced independently.",
        "how_ar": "بعد تصحيح اتجاه EXIF، يستخدم Pillow thumbnail مع إعادة أخذ عينات LANCZOS ويضع حدًا واحدًا للعرض والارتفاع. لا يتم تكبير الصورة الصغيرة لتصل للحد؛ يتم التصغير فقط عند الحاجة. الناتج JPG بجودة عالية عملية، لذلك ملفات PNG ذات الشفافية تفقد الشفافية في هذا المسار.",
        "how_en": "After EXIF orientation is normalized, Pillow uses a LANCZOS thumbnail operation with your chosen maximum width/height. Smaller images are not unnecessarily enlarged. The current public contract writes the resized result as JPEG using Infinity's output encoder, so transparent input pixels are flattened and exact source metadata is not the goal of this workflow.",
        "limits_ar": "الحد الحالي للأبعاد المطلوبة بين 16 و8000 بكسل. الأداة تحافظ على النسبة لكنها لا تسمح بفرض عرض وارتفاع مختلفين، ولا تنشئ تفاصيل جديدة عند تكبير صورة صغيرة. إذا كنت تحتاج PNG شفافًا استخدم مسارًا يحافظ على PNG.",
        "limits_en": "The requested maximum dimension must be between 16 and 8000 pixels. The tool preserves aspect ratio rather than forcing two independent dimensions, and it does not synthesize new detail. The output is JPEG, so it is not suitable when the resized copy must preserve alpha transparency or remain lossless.",
        "check_ar": "افتح الناتج وتأكد أن العرض والارتفاع لم يتجاوزا الرقم الذي اخترته وأن النسبة تبدو طبيعية. افحص النص الصغير والحواف، وراقب الخلفية إذا كان الأصل PNG شفافًا.",
        "check_en": "Check the downloaded width and height and confirm neither exceeds the chosen maximum. Make sure the aspect ratio still looks natural, then inspect small text, thin edges, and any area that used to be transparent. If quality matters more than file size, compare the resized JPEG against the original at 100% view.",
        "faq_ar": [("هل يغير النسبة؟", "لا. thumbnail يحافظ على نسبة العرض إلى الارتفاع داخل الحد الذي تختاره."), ("هل يكبر صورة صغيرة؟", "لا يتعمد المسار تكبير صورة أصغر من الحد؛ هدفه الأساسي التصغير العملي.")],
        "faq_en": [("Does it distort the aspect ratio?", "No. The thumbnail operation preserves aspect ratio inside the selected maximum dimension."), ("Will it upscale a small image?", "No unnecessary enlargement is performed; this workflow is primarily designed for practical downsizing.")],
    },
    "image-ocr": {
        "processing": "server_local",
        "engine_ar": "OCR محلي على الخادم باستخدام Tesseract بعد تحقق الصورة",
        "engine_en": "Local server-side OCR with Tesseract after image validation",
        "sample_urls": ["/static/samples/sample-scan.png"],
        "sample_names": ["sample-scan.png"],
        "best_for_ar": "استخراج نص قابل للنسخ من صورة مستند أو لقطة شاشة أو صفحة ممسوحة عندما تكون الحروف داخل البكسلات وليست نصًا حقيقيًا. يدعم المسار اللغة المحددة في إعداد OCR، ويكون أفضل مع الصور المستقيمة والواضحة والتباين الجيد.",
        "best_for_en": "Best for extracting copyable text from a scan, screenshot, photographed page, or other image where the visible letters are pixels rather than a text layer. The OCR engine runs locally on Infinity's server using Tesseract and the requested language setting. Clean, straight, high-contrast documents generally produce more useful text than blurred, skewed, decorative, or very low-resolution images.",
        "how_ar": "بعد اجتياز فحص نوع الصورة والبكسلات، يشغّل Infinity Tesseract بمهلة زمنية محددة ويكتب النص الذي تعرف عليه داخل ملف TXT. الإعداد الافتراضي مخصص للعربية والإنجليزية عند توفر حزم اللغات، ولا يتم إرسال محتوى الصورة إلى مزود AI خارجي كجزء من OCR.",
        "how_en": "After the upload passes image signature, decode, and pixel-limit checks, Infinity runs Tesseract with a bounded timeout and writes recognized text to a plain TXT result. The default language profile is designed for Arabic plus English in the production image. OCR is deterministic document recognition here; the image content is not automatically sent to the optional external Infinity AI provider.",
        "limits_ar": "OCR ليس نسخًا مثاليًا دائمًا. الجداول المعقدة، الخط اليدوي، الصور المائلة، الخلفية المزدحمة والأرقام الصغيرة قد تنتج أخطاء. الناتج TXT لا يحافظ على التخطيط البصري الأصلي، لذلك راجع الأسماء والأرقام والبيانات الحساسة قبل استخدامها.",
        "limits_en": "OCR is not guaranteed transcription. Handwriting, complex tables, unusual fonts, rotated pages, noisy backgrounds, and tiny characters can produce recognition errors. The TXT output also does not preserve the visual layout of the original image. Names, IDs, totals, dates, and other high-impact values should always be checked against the source.",
        "check_ar": "قارن بضعة أسطر من البداية والوسط والنهاية مع الصورة، وركز على الأرقام والحروف المتشابهة. إذا كانت النتيجة ضعيفة، حسّن استقامة الصورة أو التباين أو استخدم نسخة بدقة أعلى ثم أعد المحاولة.",
        "check_en": "Compare several lines from different parts of the image with the source, especially digits and visually similar characters. If recognition is weak, retry with a straighter, sharper, higher-contrast image or the correct OCR language. Do not treat an OCR result as verified legal, financial, or academic transcription without review.",
        "faq_ar": [("هل يرسل الصورة للذكاء الاصطناعي؟", "مسار OCR نفسه يستخدم Tesseract محليًا على خادم Infinity ولا يرفق الملف تلقائيًا بمزود AI الخارجي."), ("ليش يخطئ في بعض الكلمات؟", "OCR يعتمد على وضوح البكسلات والخط واللغة والتباين؛ الصور الضعيفة أو المعقدة تقلل الدقة.")],
        "faq_en": [("Is the image sent to external AI for OCR?", "No. This OCR workflow uses local Tesseract processing on the Infinity server; file contents are not automatically attached to the optional AI provider."), ("Why can some words be wrong?", "Recognition depends on resolution, contrast, font, language, skew, and image noise, so difficult images need manual review.")],
    },
    "csv-to-xlsx": {
        "processing": "server_local",
        "engine_ar": "تحويل CSV إلى Excel محليًا باستخدام openpyxl مع حماية من الصيغ",
        "engine_en": "Local CSV-to-Excel conversion with openpyxl and formula-injection neutralization",
        "sample_urls": ["/static/samples/sample-data.csv"],
        "sample_names": ["sample-data.csv"],
        "best_for_ar": "تحويل جدول CSV إلى ملف XLSX أسهل للفتح في Excel أو Numbers مع الحفاظ على الصفوف والأعمدة كنص وبيانات جدولية. المسار مفيد للتقارير والتصديرات البسيطة عندما تريد ملف عمل حقيقي بدل CSV خام.",
        "best_for_en": "Best for turning a normal CSV export into an XLSX workbook that opens cleanly in Excel-compatible software. Rows and columns are transferred into a worksheet rather than embedded as a screenshot. Infinity also neutralizes cells that begin like spreadsheet formulas, reducing the risk that an untrusted CSV value executes as a formula when the resulting workbook is opened.",
        "how_ar": "يقرأ المحرك CSV بترميز UTF-8 مع دعم BOM ويستخدم csv.reader ثم ينشئ Workbook جديدًا. كل خلية تبدأ بـ = أو + أو - أو @ تُسبق بعلامة اقتباس مفردة قبل كتابتها، وبعدها يحفظ openpyxl ملف XLSX حقيقيًا يمكن فتحه كجدول.",
        "how_en": "The converter reads UTF-8 CSV data with BOM support, parses rows through Python's CSV reader, and creates a real openpyxl workbook. Values beginning with =, +, -, or @ are prefixed with an apostrophe before insertion so imported data is not interpreted as an active spreadsheet formula. The workbook is then saved as a standard XLSX file.",
        "limits_ar": "CSV لا يحمل تنسيق Excel الأصلي أو ألوانًا أو صيغًا أو أنواع بيانات غنية، لذلك الأداة لا تستطيع اختراعها. الفواصل والاقتباسات غير الصالحة أو ملفات CSV بترميز غير متوقع قد تحتاج تنظيفًا قبل التحويل، والقيم تُعامل بطريقة آمنة بدل تنفيذها كصيغ.",
        "limits_en": "CSV itself does not contain Excel styling, multiple worksheets, formulas, charts, or rich cell types, so the converter cannot recreate features that were never present. Malformed delimiters, unusual encodings, or inconsistent row structure can still require cleanup. Formula-looking values are intentionally treated as data for safety rather than being executed.",
        "check_ar": "افتح XLSX وراجع الصف الأول وعدد الأعمدة وبضعة صفوف من المنتصف والنهاية. تأكد أن الأرقام والنصوص الطويلة ظهرت في الأعمدة الصحيحة، ولاحظ أن القيم التي تشبه الصيغ يجب أن تبقى بيانات لا أوامر قابلة للتنفيذ.",
        "check_en": "Open the XLSX and inspect the header row, column count, and a few records from the middle and end. Verify that commas and quoted values landed in the correct cells. If the source contained values starting with spreadsheet formula characters, confirm they remain visible data rather than active formulas before distributing the workbook.",
        "faq_ar": [("هل ينقل تنسيق Excel؟", "CSV لا يحتوي أصلًا على تنسيق Excel؛ الناتج ينقل البيانات إلى Workbook جديد بدون اختراع تنسيق مفقود."), ("ليش بعض القيم تبدأ بعلامة اقتباس؟", "لحماية الملف من CSV formula injection عندما تبدأ قيمة برمز يمكن لـExcel تفسيره كصيغة.")],
        "faq_en": [("Does it preserve Excel formatting?", "CSV has no Excel formatting to preserve; the tool moves the tabular data into a new workbook."), ("Why are formula-looking values neutralized?", "It is a safety measure against CSV formula injection when a value begins with a character spreadsheet software may execute.")],
    },
    "markdown-to-pdf": {
        "processing": "server_local",
        "engine_ar": "Markdown إلى HTML منقّى ثم PDF داخل LibreOffice معزول",
        "engine_en": "Sanitized Markdown-to-HTML followed by isolated LibreOffice PDF rendering",
        "sample_urls": ["/static/samples/sample-markdown.md"],
        "sample_names": ["sample-markdown.md"],
        "best_for_ar": "تحويل ملاحظات أو README أو مستند Markdown بسيط إلى PDF قابل للمشاركة بدون نسخ المحتوى يدويًا إلى محرر مكتبي. المسار مناسب للعناوين والقوائم والفقرات والجداول البسيطة، مع أولوية للأمان والاستقرار بدل دعم HTML خارجي معقد.",
        "best_for_en": "Best for turning notes, README-style documents, technical instructions, or other Markdown into a shareable PDF without manually rebuilding the document in a word processor. The workflow handles common Markdown structure such as headings, lists, paragraphs, and simple tables, while deliberately favoring safe local rendering over unrestricted remote HTML, scripts, or external web assets.",
        "how_ar": "يحوّل Infinity Markdown إلى HTML باستخدام مكتبة Markdown، ثم يفحص HTML ويرفض الروابط أو الموارد البعيدة غير المسموحة. بعدها يشغّل LibreOffice في ملف تعريف مؤقت ومعزول مع إعدادات تمنع الماكرو وتقلل البيئة الموروثة، ثم يحفظ الناتج PDF داخل مساحة الطلب المؤقتة.",
        "how_en": "Infinity first renders Markdown to HTML, then validates that HTML before office rendering. Remote resource URLs and unsafe constructs are rejected instead of being fetched. The sanitized document is passed to LibreOffice using an isolated temporary profile, restricted environment, macro security settings, process-group timeout handling, and the request's private workspace before the final PDF is validated.",
        "limits_ar": "CSS المتقدم، JavaScript، الخطوط أو الصور البعيدة ومزايا Markdown الخاصة جدًا قد لا تظهر كما تتوقع. النتيجة تعتمد على محرك HTML/LibreOffice المحلي وليس متصفح Chrome كامل، لذلك راجع الجداول الطويلة والصفحات والفواصل قبل إرسال مستند رسمي.",
        "limits_en": "Advanced CSS, JavaScript, remote fonts/images, and flavor-specific Markdown extensions are not guaranteed. Rendering is performed by the local document pipeline rather than a full browser engine, so complex page breaks, wide tables, or custom styling can differ from a GitHub or browser preview. Keep the Markdown source as the editable original.",
        "check_ar": "راجع العناوين والقوائم والروابط والجداول، ثم افتح أول وآخر صفحة وتأكد أن فواصل الصفحات معقولة. إذا كان المستند يحتوي كودًا أو جدولًا عريضًا، افحص هذا الجزء تحديدًا قبل مشاركة PDF.",
        "check_en": "Inspect headings, lists, links, code blocks, and tables, then check the first and last pages for sensible page breaks. Pay special attention to wide tables and long code lines because those are most likely to expose layout differences. Keep the source Markdown so you can adjust structure and regenerate the PDF if needed.",
        "faq_ar": [("هل يجلب صورًا من الإنترنت؟", "المسار يمنع الموارد البعيدة في HTML بدل السماح للمحوّل بجلب محتوى غير موثوق من الشبكة."), ("هل يشغّل JavaScript؟", "لا يعتمد هذا المسار على JavaScript؛ الهدف تحويل Markdown آمن إلى مستند PDF محلي.")],
        "faq_en": [("Will it fetch remote images from the internet?", "No. The HTML validation layer rejects remote resources instead of allowing the document renderer to fetch untrusted network content."), ("Does it execute JavaScript?", "No. This workflow is a local Markdown/document conversion path, not a browser JavaScript execution environment.")],
    },
    "pdf-watermark-text": {
        "processing": "server_local",
        "engine_ar": "إضافة نص مائي محلي فوق كل صفحة PDF باستخدام PyMuPDF",
        "engine_en": "Local PyMuPDF text watermark overlay on every PDF page",
        "sample_urls": ["/static/samples/sample-a.pdf"],
        "sample_names": ["sample-a.pdf"],
        "sample_options": {"text": "CONFIDENTIAL"},
        "best_for_ar": "إضافة عبارة واضحة مثل سري أو DRAFT أو اسم جهة فوق صفحات PDF قبل إرسال نسخة للمراجعة. الأداة مفيدة كإشارة بصرية متكررة على كل صفحة، لكنها ليست نظام DRM ولا تمنع شخصًا يملك أدوات PDF متقدمة من تعديل الملف لاحقًا.",
        "best_for_en": "Best for placing a visible phrase such as CONFIDENTIAL, DRAFT, REVIEW COPY, or an organization label across every page before sharing a PDF. It creates a repeated visual cue inside the document and can help distinguish review copies. A watermark is not DRM, encryption, or access control, so it should not be presented as a guarantee that the document cannot be edited.",
        "how_ar": "يفتح المحرك PDF ويضيف textbox شبه شفاف فوق كل صفحة بحجم خط يتكيف مع عرض الصفحة. يحاول استخدام خط Unicode مثبت على الخادم عند توفره لدعم نصوص أوسع، ثم يحفظ نسخة PDF جديدة مع تنظيف وضغط البنية. النص المطلوب محدود إلى 120 حرفًا.",
        "how_en": "PyMuPDF opens the validated PDF and overlays a semi-transparent text box on every page. Font size is scaled to the page width, a Unicode-capable installed font is used when available, and the output is saved as a new cleaned/deflated PDF. The public handler limits watermark text to 120 characters to keep the operation bounded and predictable.",
        "limits_ar": "الموضع والشفافية والحجم محددة حاليًا بواسطة التصميم الداخلي ولا توفر الأداة محرر سحب حر. النص المائي لا يشفر الملف، وقد يغطي جزءًا من محتوى الصفحة إذا كان التصميم مزدحمًا جدًا، لذلك يجب مراجعة أكثر الصفحات كثافة بعد التنفيذ.",
        "limits_en": "Position, opacity, and sizing follow the current fixed design rather than a freeform drag-and-drop editor. The watermark does not encrypt or lock the PDF. Very dense pages can place the overlay near important content, and unusual fonts or scripts may render differently depending on the server's available Unicode font support.",
        "check_ar": "افتح صفحة فاتحة وصفحة مزدحمة وتأكد أن العلامة مقروءة بدون إخفاء معلومات مهمة، ثم راجع العربية أو الرموز الخاصة إن استخدمتها. إذا كان الهدف حماية وصول حقيقية استخدم كلمة مرور أو صلاحيات مشاركة بالإضافة للعلامة البصرية.",
        "check_en": "Inspect both a sparse page and the busiest page to make sure the watermark is visible without obscuring critical information. Verify non-Latin text or special characters if you use them. If you need actual access restriction, combine the visual watermark with appropriate password or sharing controls rather than relying on the overlay alone.",
        "faq_ar": [("هل العلامة تمنع تعديل PDF؟", "لا. هي طبقة بصرية وليست تشفيرًا أو DRM."), ("هل تضاف لكل الصفحات؟", "نعم، التنفيذ الحالي يضع النص المائي على كل صفحة في الملف الناتج.")],
        "faq_en": [("Does a watermark stop PDF editing?", "No. It is a visual overlay, not encryption or DRM."), ("Is it added to every page?", "Yes. The current implementation overlays the watermark text on every page in the generated PDF.")],
    },
}


def install() -> None:
    """Install reviewed entries into the canonical editorial registry once."""
    from core import editorial

    collisions = set(SCORE90_TOOL_EDITORIAL) & set(editorial.TOOL_EDITORIAL)
    if collisions:
        raise RuntimeError(f"Score-90 editorial IDs already exist: {sorted(collisions)}")
    editorial.TOOL_EDITORIAL.update(SCORE90_TOOL_EDITORIAL)
