#!/usr/bin/env bash
# Reproducible, production-parity, offline converter output acceptance.
# No user documents, cloud secrets, real database, or production deployment.
set -Eeuo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
command -v docker >/dev/null || { echo "Docker is required" >&2; exit 2; }
docker info >/dev/null || { echo "Docker daemon is unavailable" >&2; exit 2; }
EXPECTED_SHA="$(git rev-parse HEAD)"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
REPORTS="${IC_QUALITY_REPORT_DIR:-$ROOT/quality-reports/$STAMP}"
mkdir -p "$REPORTS"
chmod 777 "$REPORTS" # throwaway test output for non-root container account
IMAGE="infinity-quality:${EXPECTED_SHA:0:12}"
printf 'source_commit=%s\nimage=%s\nstarted_utc=%s\n' "$EXPECTED_SHA" "$IMAGE" "$STAMP" > "$REPORTS/provenance.txt"
on_exit() {
  code=$?
  echo "exit_code=$code" >> "$REPORTS/provenance.txt"
  if (( code != 0 )); then
    echo "QUALITY BLOCKED: at least one actual test failed or did not run. Reports: $REPORTS" >&2
  fi
}
trap on_exit EXIT

echo "Building the exact production Dockerfile with native tools and pytest."
docker build --progress=plain -t "$IMAGE" . 2>&1 | tee "$REPORTS/docker-build.log"
docker run --rm --network none "$IMAGE" python -m pip check \
  2>&1 | tee "$REPORTS/dependency-check.log"
docker run --rm --network none "$IMAGE" sh -c \
  'python --version; libreoffice --version; tesseract --version; fc-match "Noto Sans Arabic"' \
  2>&1 | tee "$REPORTS/native-tools.log"

# A clean container and fresh temporary fixtures are used for each pass. Never
# use a real service URL or forward environment variables from the host.
run_audit() {
  local profile="$1" round="$2" report="$REPORTS/$round-$profile.json"
  echo "SEMANTIC: round=$round corpus=$profile"
  docker run --rm --network none --memory "${IC_TEST_MEMORY:-2g}" \
    --cpus "${IC_TEST_CPUS:-2}" --pids-limit 512 \
    -v "$REPORTS:/quality-report" \
    -e "IC_TEST_FIXTURE_PROFILE=$profile" \
    -e "IC_SEMANTIC_REPORT=/quality-report/$round-$profile.json" \
    "$IMAGE" python scripts/semantic_output_audit.py \
    2>&1 | tee "$REPORTS/$round-$profile.log"
  python3 - "$report" <<'PY'
import json, sys
from pathlib import Path
p = Path(sys.argv[1])
data = json.loads(p.read_text(encoding="utf-8"))
verified = data.get("verifications", {})
failures = data.get("semantic_failures", [])
missing = data.get("unverified", [])
total = data.get("total", 0)
print(f"{p.name}: {len(verified)}/{total}; failures={len(failures)}; uncovered={len(missing)}")
if not total or len(verified) != total or data.get("semantic_verified") != total or failures or missing or not data.get("quality_complete", False):
    raise SystemExit("BLOCK RELEASE: actual source-to-output audit incomplete")
PY
}
# The language-specific complex Word/Excel fixtures are generated by pytest.
# These test the text extracted from converted PDFs, not just file existence.
docker run --rm --network none --memory "${IC_TEST_MEMORY:-2g}" \
  --cpus "${IC_TEST_CPUS:-2}" --pids-limit 512 \
  "$IMAGE" python -m pytest -q tests/test_multilingual_complex_office_outputs.py \
  2>&1 | tee "$REPORTS/large-multilingual-office.log"
for profile in baseline mixed dense; do
  run_audit "$profile" first
done
docker run --rm --network none --memory "${IC_TEST_MEMORY:-2g}" \
  --cpus "${IC_TEST_CPUS:-2}" --pids-limit 512 \
  "$IMAGE" python scripts/full_operation_smoke.py \
  2>&1 | tee "$REPORTS/full-engine-smoke.log"
docker run --rm --network none --memory "${IC_TEST_MEMORY:-2g}" \
  --cpus "${IC_TEST_CPUS:-2}" --pids-limit 512 \
  "$IMAGE" python scripts/api_operation_smoke.py \
  2>&1 | tee "$REPORTS/full-http-smoke.log"
# Independent final confirmation, in new containers with new temporary fixtures.
for profile in baseline mixed dense; do
  run_audit "$profile" replay
done
python3 - "$REPORTS" "$EXPECTED_SHA" <<'PY'
import json, sys
from pathlib import Path
directory, sha = Path(sys.argv[1]), sys.argv[2]
names = [f"{stage}-{profile}" for stage in ("first", "replay")
         for profile in ("baseline", "mixed", "dense")]
reports = [json.loads((directory / f"{name}.json").read_text(encoding="utf-8"))
           for name in names]
ids = [set(report["verifications"]) for report in reports]
if len(ids[0]) != 162 or any(x != ids[0] for x in ids):
    raise SystemExit("BLOCK RELEASE: tool registry coverage changed between rounds")
summary = {"commit": sha, "corpora": names, "tool_count": len(ids[0]),
           "all_six_semantic_rounds_passed": True}
(directory / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
print("QUALITY SEMANTIC ROUNDS COMPLETE", summary)
PY
echo "OFFLINE QUALITY ACCEPTANCE COMPLETED; browser rendering and live production still require separate checks."
