from __future__ import annotations

TOOL_META = {'pdf-merge': {'slug': 'merge-pdf', 'keywords': 'اجمع دمج ملفات pdf combine merge', 'popular': True, 'sort': 1},
 'pdf-split': {'slug': 'split-pdf', 'keywords': 'قسم تقسيم ملف pdf split pages', 'popular': True, 'sort': 2},
 'pdf-extract-pages': {'slug': 'extract-pdf-pages',
                       'keywords': 'استخراج صفحات pdf extract pages',
                       'popular': False,
                       'sort': 3},
 'pdf-delete-pages': {'slug': 'delete-pdf-pages',
                      'keywords': 'حذف صفحات pdf delete pages remove',
                      'popular': False,
                      'sort': 4},
 'pdf-rotate': {'slug': 'rotate-pdf', 'keywords': 'تدوير pdf rotate', 'popular': False, 'sort': 5},
 'pdf-compress': {'slug': 'compress-pdf', 'keywords': 'ضغط تصغير pdf compress reduce size', 'popular': True, 'sort': 6},
 'pdf-to-jpg': {'slug': 'pdf-to-jpg', 'keywords': 'pdf jpg صورة تحويل convert image', 'popular': True, 'sort': 7},
 'pdf-to-png': {'slug': 'pdf-to-png', 'keywords': 'pdf png صورة تحويل convert image', 'popular': False, 'sort': 8},
 'image-to-pdf': {'slug': 'jpg-to-pdf',
                  'keywords': 'jpg png webp pdf صورة تحويل image to pdf',
                  'popular': True,
                  'sort': 9},
 'pdf-to-text': {'slug': 'pdf-to-text', 'keywords': 'pdf نص استخراج text extract', 'popular': False, 'sort': 10},
 'pdf-to-html': {'slug': 'pdf-to-html', 'keywords': 'pdf html تحويل convert', 'popular': False, 'sort': 11},
 'pdf-metadata': {'slug': 'pdf-metadata', 'keywords': 'pdf بيانات وصفية metadata info', 'popular': False, 'sort': 12},
 'pdf-ocr': {'slug': 'pdf-ocr', 'keywords': 'pdf ocr نص استخراج ممسوح scanned', 'popular': True, 'sort': 13},
 'pdf-booklet': {'slug': 'pdf-booklet-maker',
                 'keywords': 'pdf كتيب booklet 2-up 4-up طباعة',
                 'popular': False,
                 'sort': 14},
 'lms-pdf-size-optimizer': {'slug': 'lms-pdf-size-optimizer',
                            'keywords': 'lms pdf ضغط حجم رفع منصة تعليمية',
                            'popular': False,
                            'sort': 15},
 'assignment-cover-page': {'slug': 'assignment-cover-page',
                           'keywords': 'واجب غلاف assignment cover page pdf',
                           'popular': False,
                           'sort': 16},
 'omr-bubble-sheet': {'slug': 'omr-bubble-sheet',
                      'keywords': 'omr bubble answer sheet ورقة إجابة',
                      'popular': False,
                      'sort': 17},
 'image-to-jpg': {'slug': 'image-to-jpg', 'keywords': 'صورة jpg تحويل image convert', 'popular': False, 'sort': 14},
 'image-to-png': {'slug': 'image-to-png', 'keywords': 'صورة png تحويل image convert', 'popular': True, 'sort': 15},
 'image-to-webp': {'slug': 'image-to-webp', 'keywords': 'صورة webp تحويل image convert', 'popular': False, 'sort': 16},
 'image-resize': {'slug': 'resize-image',
                  'keywords': 'تغيير حجم أبعاد صورة resize image dimensions',
                  'popular': False,
                  'sort': 17},
 'image-compress': {'slug': 'compress-image',
                    'keywords': 'ضغط تصغير صورة compress image size',
                    'popular': True,
                    'sort': 18},
 'image-rotate': {'slug': 'rotate-image', 'keywords': 'تدوير صورة rotate image', 'popular': False, 'sort': 19},
 'image-ocr': {'slug': 'image-ocr', 'keywords': 'صورة ocr نص استخراج image text', 'popular': False, 'sort': 20},
 'social-media-image-resizer': {'slug': 'social-media-image-resizer',
                                'keywords': 'social media instagram linkedin image resize صورة سوشيال',
                                'popular': False,
                                'sort': 21},
 'quote-social-graphic': {'slug': 'quote-to-social-graphic',
                          'keywords': 'quote اقتباس social graphic صورة',
                          'popular': False,
                          'sort': 22},
 'word-to-pdf': {'slug': 'word-to-pdf', 'keywords': 'وورد word مستند pdf تحويل', 'popular': True, 'sort': 21},
 'excel-to-pdf': {'slug': 'excel-to-pdf', 'keywords': 'اكسل excel جدول pdf تحويل', 'popular': False, 'sort': 22},
 'ppt-to-pdf': {'slug': 'powerpoint-to-pdf',
                'keywords': 'باوربوينت powerpoint عرض شرائح pdf تحويل',
                'popular': False,
                'sort': 23},
 'txt-to-pdf': {'slug': 'txt-to-pdf', 'keywords': 'نص txt pdf تحويل text', 'popular': False, 'sort': 24},
 'html-to-pdf': {'slug': 'html-to-pdf', 'keywords': 'html pdf تحويل صفحة', 'popular': False, 'sort': 25},
 'markdown-to-html': {'slug': 'markdown-to-html',
                      'keywords': 'ماركداون markdown html تحويل',
                      'popular': False,
                      'sort': 26},
 'markdown-to-pdf': {'slug': 'markdown-to-pdf',
                     'keywords': 'ماركداون markdown pdf تحويل',
                     'popular': False,
                     'sort': 27},
 'csv-to-xlsx': {'slug': 'csv-to-excel', 'keywords': 'csv اكسل excel جدول تحويل', 'popular': False, 'sort': 28},
 'csv-to-pdf': {'slug': 'csv-to-pdf', 'keywords': 'csv pdf جدول تحويل', 'popular': False, 'sort': 29},
 'bulk-certificate-maker': {'slug': 'bulk-certificate-maker',
                            'keywords': 'شهادات certificates csv pdf zip جماعية',
                            'popular': False,
                            'sort': 30},
 'csv-merge-deduplicate': {'slug': 'csv-merge-deduplicate',
                           'keywords': 'csv merge دمج حذف تكرار deduplicate',
                           'popular': False,
                           'sort': 31},
 'lms-question-bank-formatter': {'slug': 'lms-question-bank-formatter',
                                 'keywords': 'lms gift question bank أسئلة بنك',
                                 'popular': False,
                                 'sort': 32},
 'zip-create': {'slug': 'create-zip', 'keywords': 'ضغط أرشيف zip إنشاء archive create', 'popular': False, 'sort': 30},
 'zip-extract': {'slug': 'extract-zip',
                 'keywords': 'فك ضغط أرشيف zip استخراج archive extract',
                 'popular': False,
                 'sort': 31},
 'file-hash': {'slug': 'file-hash', 'keywords': 'بصمة hash sha256 md5 تحقق', 'popular': False, 'sort': 33},
 'file-info': {'slug': 'file-info', 'keywords': 'معلومات ملف تحليل info analyzer', 'popular': False, 'sort': 34},
 'pdf-reorder-pages': {'slug': 'pdf-reorder-pages',
                       'keywords': 'إعادة ترتيب صفحات PDF Reorder PDF Pages PDF PDF',
                       'popular': False,
                       'sort': 1042},
 'pdf-rotate-selected': {'slug': 'pdf-rotate-selected',
                         'keywords': 'تدوير صفحات محددة في PDF Rotate Selected PDF Pages PDF PDF',
                         'popular': False,
                         'sort': 1043},
 'pdf-page-numbers': {'slug': 'pdf-page-numbers',
                      'keywords': 'إضافة أرقام الصفحات إلى PDF Add PDF Page Numbers PDF PDF',
                      'popular': False,
                      'sort': 1044},
 'pdf-watermark-text': {'slug': 'pdf-watermark-text',
                        'keywords': 'علامة مائية نصية لـ PDF PDF Text Watermark PDF PDF',
                        'popular': False,
                        'sort': 1045},
 'pdf-grayscale': {'slug': 'pdf-grayscale',
                   'keywords': 'تحويل PDF إلى أبيض وأسود Grayscale PDF PDF PDF',
                   'popular': False,
                   'sort': 1046},
 'pdf-remove-blank-pages': {'slug': 'pdf-remove-blank-pages',
                            'keywords': 'حذف الصفحات الفارغة من PDF Remove Blank PDF Pages PDF PDF',
                            'popular': False,
                            'sort': 1047},
 'pdf-crop-margins': {'slug': 'pdf-crop-margins',
                      'keywords': 'قص هوامش PDF Crop PDF Margins PDF PDF',
                      'popular': False,
                      'sort': 1048},
 'pdf-poster-split': {'slug': 'pdf-poster-split',
                      'keywords': 'تقسيم PDF إلى بلاطات للطباعة PDF Poster Tiler PDF PDF',
                      'popular': False,
                      'sort': 1049},
 'pdf-contact-sheet': {'slug': 'pdf-contact-sheet',
                       'keywords': 'إنشاء ورقة معاينة PDF PDF Contact Sheet PDF PDF',
                       'popular': False,
                       'sort': 1050},
 'pdf-password-protect': {'slug': 'pdf-password-protect',
                          'keywords': 'حماية PDF بكلمة مرور Password Protect PDF PDF PDF',
                          'popular': False,
                          'sort': 1051},
 'image-crop': {'slug': 'image-crop',
                'keywords': 'قص الصورة بإحداثيات دقيقة Crop Image الصور Images',
                'popular': False,
                'sort': 1052},
 'image-flip': {'slug': 'image-flip', 'keywords': 'قلب الصورة Flip Image الصور Images', 'popular': False, 'sort': 1053},
 'image-grayscale': {'slug': 'image-grayscale',
                     'keywords': 'تحويل الصورة إلى تدرج رمادي Grayscale Image الصور Images',
                     'popular': False,
                     'sort': 1054},
 'image-sharpen': {'slug': 'image-sharpen',
                   'keywords': 'زيادة حدة الصورة Sharpen Image الصور Images',
                   'popular': False,
                   'sort': 1055},
 'image-auto-contrast': {'slug': 'image-auto-contrast',
                         'keywords': 'تحسين تباين الصورة تلقائيًا Auto Contrast Image الصور Images',
                         'popular': False,
                         'sort': 1056},
 'image-sepia': {'slug': 'image-sepia',
                 'keywords': 'تأثير سيبيا للصورة Sepia Image الصور Images',
                 'popular': False,
                 'sort': 1057},
 'image-strip-metadata': {'slug': 'image-strip-metadata',
                          'keywords': 'إزالة بيانات الصورة الوصفية Remove Image Metadata الصور Images',
                          'popular': False,
                          'sort': 1058},
 'image-favicon-pack': {'slug': 'image-favicon-pack',
                        'keywords': 'حزمة Favicon كاملة Favicon Pack Generator الصور Images',
                        'popular': False,
                        'sort': 1059},
 'image-contact-sheet': {'slug': 'image-contact-sheet',
                         'keywords': 'ورقة معاينة للصورة Image Contact Sheet الصور Images',
                         'popular': False,
                         'sort': 1060},
 'image-set-dpi': {'slug': 'image-set-dpi',
                   'keywords': 'تعيين دقة DPI للصورة Set Image DPI الصور Images',
                   'popular': False,
                   'sort': 1061},
 'docx-to-text': {'slug': 'docx-to-text',
                  'keywords': 'تحويل Word إلى TXT Word to Text المستندات Documents',
                  'popular': False,
                  'sort': 1062},
 'docx-to-html': {'slug': 'docx-to-html',
                  'keywords': 'تحويل Word إلى HTML Word to HTML المستندات Documents',
                  'popular': False,
                  'sort': 1063},
 'xlsx-to-csv': {'slug': 'xlsx-to-csv',
                 'keywords': 'تحويل Excel إلى CSV Excel to CSV Excel Excel',
                 'popular': False,
                 'sort': 1064},
 'xlsx-to-json': {'slug': 'xlsx-to-json',
                  'keywords': 'تحويل Excel إلى JSON Excel to JSON Excel Excel',
                  'popular': False,
                  'sort': 1065},
 'pptx-to-text': {'slug': 'pptx-to-text',
                  'keywords': 'تحويل PowerPoint إلى TXT PowerPoint to Text المستندات Documents',
                  'popular': False,
                  'sort': 1066},
 'csv-to-json': {'slug': 'csv-to-json',
                 'keywords': 'تحويل CSV إلى JSON CSV to JSON البيانات Data',
                 'popular': False,
                 'sort': 1067},
 'json-to-csv': {'slug': 'json-to-csv',
                 'keywords': 'تحويل JSON إلى CSV JSON to CSV البيانات Data',
                 'popular': False,
                 'sort': 1068},
 'json-to-xlsx': {'slug': 'json-to-xlsx',
                  'keywords': 'تحويل JSON إلى Excel JSON to Excel البيانات Data',
                  'popular': False,
                  'sort': 1069},
 'xml-to-json': {'slug': 'xml-to-json',
                 'keywords': 'تحويل XML إلى JSON XML to JSON البيانات Data',
                 'popular': False,
                 'sort': 1070},
 'text-to-json': {'slug': 'text-to-json',
                  'keywords': 'تحويل TXT إلى JSON Text to JSON المستندات Documents',
                  'popular': False,
                  'sort': 1071},
 'ocr-image-to-pdf': {'slug': 'ocr-image-to-pdf',
                      'keywords': 'صورة إلى PDF قابل للبحث OCR Image to Searchable PDF OCR OCR',
                      'popular': False,
                      'sort': 1072},
 'ocr-pdf-to-searchable': {'slug': 'ocr-pdf-to-searchable',
                           'keywords': 'PDF ممسوح إلى PDF قابل للبحث OCR PDF to Searchable PDF OCR OCR',
                           'popular': False,
                           'sort': 1073},
 'ocr-image-to-json': {'slug': 'ocr-image-to-json',
                       'keywords': 'OCR الصورة إلى JSON OCR Image to JSON OCR OCR',
                       'popular': False,
                       'sort': 1074},
 'ocr-pdf-to-json': {'slug': 'ocr-pdf-to-json',
                     'keywords': 'OCR PDF إلى JSON OCR PDF to JSON OCR OCR',
                     'popular': False,
                     'sort': 1075},
 'ocr-pdf-page-texts': {'slug': 'ocr-pdf-page-texts',
                        'keywords': 'نصوص صفحات PDF عبر OCR OCR PDF Pages to Texts OCR OCR',
                        'popular': False,
                        'sort': 1076},
 'ocr-image-numbers': {'slug': 'ocr-image-numbers',
                       'keywords': 'استخراج الأرقام من الصورة عبر OCR OCR Number Extractor OCR OCR',
                       'popular': False,
                       'sort': 1077},
 'ocr-image-emails': {'slug': 'ocr-image-emails',
                      'keywords': 'استخراج البريد الإلكتروني من الصورة OCR Email Extractor OCR OCR',
                      'popular': False,
                      'sort': 1078},
 'ocr-image-urls': {'slug': 'ocr-image-urls',
                    'keywords': 'استخراج الروابط من الصورة OCR URL Extractor OCR OCR',
                    'popular': False,
                    'sort': 1079},
 'ocr-image-table-csv': {'slug': 'ocr-image-table-csv',
                         'keywords': 'تحويل جدول الصورة إلى CSV OCR Table to CSV OCR OCR',
                         'popular': False,
                         'sort': 1080},
 'ocr-image-clean-text': {'slug': 'ocr-image-clean-text',
                          'keywords': 'OCR وتنظيف النص OCR Clean Text OCR OCR',
                          'popular': False,
                          'sort': 1081},
 'tar-create': {'slug': 'tar-create',
                'keywords': 'إنشاء TAR Create TAR Archive الأرشيف Archive',
                'popular': False,
                'sort': 1082},
 'tar-extract': {'slug': 'tar-extract',
                 'keywords': 'استخراج TAR Extract TAR Archive الأرشيف Archive',
                 'popular': False,
                 'sort': 1083},
 'gzip-compress': {'slug': 'gzip-compress',
                   'keywords': 'ضغط GZIP GZIP Compress الأرشيف Archive',
                   'popular': False,
                   'sort': 1084},
 'gzip-decompress': {'slug': 'gzip-decompress',
                     'keywords': 'فك ضغط GZIP كنص GZIP Decompress to Text الأرشيف Archive',
                     'popular': False,
                     'sort': 1085},
 'zip-list': {'slug': 'zip-list',
              'keywords': 'قائمة محتويات ZIP ZIP Contents Report الأرشيف Archive',
              'popular': False,
              'sort': 1086},
 'zip-integrity': {'slug': 'zip-integrity',
                   'keywords': 'فحص سلامة ZIP ZIP Integrity Check الأرشيف Archive',
                   'popular': False,
                   'sort': 1087},
 'zip-flatten': {'slug': 'zip-flatten',
                 'keywords': 'تبسيط بنية ZIP Flatten ZIP الأرشيف Archive',
                 'popular': False,
                 'sort': 1088},
 'tar-list': {'slug': 'tar-list',
              'keywords': 'قائمة محتويات TAR TAR Contents Report الأرشيف Archive',
              'popular': False,
              'sort': 1089},
 'gzip-info': {'slug': 'gzip-info',
               'keywords': 'معلومات GZIP GZIP Information الأرشيف Archive',
               'popular': False,
               'sort': 1090},
 'zip-to-tar': {'slug': 'zip-to-tar',
                'keywords': 'تحويل ZIP إلى TAR ZIP to TAR الأرشيف Archive',
                'popular': False,
                'sort': 1091},
 'file-mime-report': {'slug': 'file-mime-report',
                      'keywords': 'كاشف نوع الملف File MIME Report الأدوات المساعدة Utilities',
                      'popular': False,
                      'sort': 1092},
 'text-statistics': {'slug': 'text-statistics',
                     'keywords': 'إحصائيات النص Text Statistics الأدوات المساعدة Utilities',
                     'popular': False,
                     'sort': 1093},
 'text-clean': {'slug': 'text-clean',
                'keywords': 'تنظيف النص Text Cleaner الأدوات المساعدة Utilities',
                'popular': False,
                'sort': 1094},
 'text-deduplicate': {'slug': 'text-deduplicate',
                      'keywords': 'حذف الأسطر المكررة Text Line Deduplicator الأدوات المساعدة Utilities',
                      'popular': False,
                      'sort': 1095},
 'text-sort': {'slug': 'text-sort',
               'keywords': 'ترتيب أسطر النص Text Line Sorter الأدوات المساعدة Utilities',
               'popular': False,
               'sort': 1096},
 'filename-normalizer': {'slug': 'filename-normalizer',
                         'keywords': 'تنظيف اسم الملف Filename Normalizer الأدوات المساعدة Utilities',
                         'popular': False,
                         'sort': 1097},
 'csv-validator': {'slug': 'csv-validator',
                   'keywords': 'مدقق CSV CSV Validator الأدوات المساعدة Utilities',
                   'popular': False,
                   'sort': 1098},
 'json-validator': {'slug': 'json-validator',
                    'keywords': 'مدقق JSON JSON Validator الأدوات المساعدة Utilities',
                    'popular': False,
                    'sort': 1099},
 'number-list-analyzer': {'slug': 'number-list-analyzer',
                          'keywords': 'محلل قائمة الأرقام Number List Analyzer الأدوات المساعدة Utilities',
                          'popular': False,
                          'sort': 1100},
 'text-to-base64': {'slug': 'text-to-base64',
                    'keywords': 'ترميز TXT إلى Base64 Text to Base64 الأدوات المساعدة Utilities',
                    'popular': False,
                    'sort': 1101},
 'pdf-to-docx': {'slug': 'pdf-to-docx', 'keywords': 'PDF إلى Word PDF to Word PDF PDF', 'popular': True, 'sort': 542},
 'pdf-to-markdown': {'slug': 'pdf-to-markdown',
                     'keywords': 'PDF إلى Markdown PDF to Markdown PDF PDF',
                     'popular': False,
                     'sort': 543},
 'pdf-compare': {'slug': 'pdf-compare',
                 'keywords': 'مقارنة ملفي PDF Compare PDFs PDF PDF',
                 'popular': True,
                 'sort': 544},
 'pdf-repair': {'slug': 'pdf-repair', 'keywords': 'إصلاح PDF Repair PDF PDF PDF', 'popular': False, 'sort': 545},
 'pdf-image-extract': {'slug': 'pdf-image-extract',
                       'keywords': 'استخراج صور PDF Extract PDF Images PDF PDF',
                       'popular': False,
                       'sort': 546},
 'pdf-links-report': {'slug': 'pdf-links-report',
                      'keywords': 'تقرير روابط PDF PDF Link Report PDF PDF',
                      'popular': False,
                      'sort': 547},
 'pdf-annotations-report': {'slug': 'pdf-annotations-report',
                            'keywords': 'تقرير تعليقات PDF PDF Annotation Report PDF PDF',
                            'popular': False,
                            'sort': 548},
 'pdf-page-size-report': {'slug': 'pdf-page-size-report',
                          'keywords': 'مقاسات صفحات PDF PDF Page Size Report PDF PDF',
                          'popular': False,
                          'sort': 549},
 'pdf-redact': {'slug': 'pdf-redact', 'keywords': 'تنقيح PDF Redact PDF PDF PDF', 'popular': True, 'sort': 550},
 'pdf-unlock': {'slug': 'pdf-unlock',
                'keywords': 'إزالة كلمة مرور PDF Unlock PDF PDF PDF',
                'popular': False,
                'sort': 551},
 'image-upscale': {'slug': 'image-upscale',
                   'keywords': 'تكبير الصورة Upscale Image الصور Images',
                   'popular': True,
                   'sort': 552},
 'image-blur': {'slug': 'image-blur',
                'keywords': 'تمويه الصورة Blur Image الصور Images',
                'popular': False,
                'sort': 553},
 'image-pixelate': {'slug': 'image-pixelate',
                    'keywords': 'بكسلة الصورة Pixelate Image الصور Images',
                    'popular': False,
                    'sort': 554},
 'image-invert': {'slug': 'image-invert',
                  'keywords': 'عكس ألوان الصورة Invert Colors الصور Images',
                  'popular': False,
                  'sort': 555},
 'image-posterize': {'slug': 'image-posterize',
                     'keywords': 'تسطيح ألوان الصورة Posterize Image الصور Images',
                     'popular': False,
                     'sort': 556},
 'image-color-palette': {'slug': 'image-color-palette',
                         'keywords': 'استخراج لوحة الألوان Color Palette Extractor الصور Images',
                         'popular': False,
                         'sort': 557},
 'image-watermark': {'slug': 'image-watermark',
                     'keywords': 'علامة مائية للصورة Image Watermark الصور Images',
                     'popular': True,
                     'sort': 558},
 'image-background-cleaner': {'slug': 'image-background-cleaner',
                              'keywords': 'تنظيف الخلفية البيضاء White Background Cleaner الصور Images',
                              'popular': False,
                              'sort': 559},
 'image-auto-orient': {'slug': 'image-auto-orient',
                       'keywords': 'تصحيح اتجاه الصورة Auto Orient Image الصور Images',
                       'popular': False,
                       'sort': 560},
 'image-round-corners': {'slug': 'image-round-corners',
                         'keywords': 'زوايا دائرية للصورة Round Image Corners الصور Images',
                         'popular': False,
                         'sort': 561},
 'docx-to-markdown': {'slug': 'docx-to-markdown',
                      'keywords': 'Word إلى Markdown DOCX to Markdown المستندات والبيانات Office & Data',
                      'popular': False,
                      'sort': 562},
 'docx-table-to-csv': {'slug': 'docx-table-to-csv',
                       'keywords': 'جداول Word إلى CSV DOCX Tables to CSV المستندات والبيانات Office & Data',
                       'popular': False,
                       'sort': 563},
 'xlsx-to-html': {'slug': 'xlsx-to-html',
                  'keywords': 'Excel إلى HTML Excel to HTML المستندات والبيانات Office & Data',
                  'popular': True,
                  'sort': 564},
 'xlsx-summary': {'slug': 'xlsx-summary',
                  'keywords': 'ملخص ملف Excel Excel Summary المستندات والبيانات Office & Data',
                  'popular': False,
                  'sort': 565},
 'csv-to-markdown': {'slug': 'csv-to-markdown',
                     'keywords': 'CSV إلى Markdown CSV to Markdown المستندات والبيانات Office & Data',
                     'popular': False,
                     'sort': 566},
 'csv-statistics': {'slug': 'csv-statistics',
                    'keywords': 'إحصائيات CSV CSV Statistics المستندات والبيانات Office & Data',
                    'popular': False,
                    'sort': 567},
 'json-to-html': {'slug': 'json-to-html',
                  'keywords': 'JSON إلى HTML JSON to HTML المستندات والبيانات Office & Data',
                  'popular': False,
                  'sort': 568},
 'html-to-text': {'slug': 'html-to-text',
                  'keywords': 'HTML إلى نص HTML to Text المستندات والبيانات Office & Data',
                  'popular': False,
                  'sort': 569},
 'markdown-to-text': {'slug': 'markdown-to-text',
                      'keywords': 'Markdown إلى نص Markdown to Text المستندات والبيانات Office & Data',
                      'popular': False,
                      'sort': 570},
 'pptx-to-markdown': {'slug': 'pptx-to-markdown',
                      'keywords': 'PowerPoint إلى Markdown PPTX to Markdown المستندات والبيانات Office & Data',
                      'popular': False,
                      'sort': 571},
 'ocr-image-to-html': {'slug': 'ocr-image-to-html',
                       'keywords': 'OCR الصورة إلى HTML OCR Image to HTML OCR OCR',
                       'popular': False,
                       'sort': 572},
 'ocr-image-to-markdown': {'slug': 'ocr-image-to-markdown',
                           'keywords': 'OCR الصورة إلى Markdown OCR Image to Markdown OCR OCR',
                           'popular': True,
                           'sort': 573},
 'ocr-pdf-to-markdown': {'slug': 'ocr-pdf-to-markdown',
                         'keywords': 'OCR PDF إلى Markdown OCR PDF to Markdown OCR OCR',
                         'popular': False,
                         'sort': 574},
 'ocr-pdf-to-csv': {'slug': 'ocr-pdf-to-csv',
                    'keywords': 'OCR PDF إلى CSV OCR PDF to CSV OCR OCR',
                    'popular': False,
                    'sort': 575},
 'ocr-image-to-csv': {'slug': 'ocr-image-to-csv',
                      'keywords': 'OCR الصورة إلى CSV OCR Image to CSV OCR OCR',
                      'popular': False,
                      'sort': 576},
 'ocr-receipt-fields': {'slug': 'ocr-receipt-fields',
                        'keywords': 'استخراج حقول الإيصال Receipt OCR Fields OCR OCR',
                        'popular': False,
                        'sort': 577},
 'ocr-invoice-fields': {'slug': 'ocr-invoice-fields',
                        'keywords': 'حقول الفاتورة بالـOCR Invoice OCR Fields OCR OCR',
                        'popular': False,
                        'sort': 578},
 'ocr-text-deduplicate': {'slug': 'ocr-text-deduplicate',
                          'keywords': 'تنظيف تكرار OCR OCR Deduplicator OCR OCR',
                          'popular': False,
                          'sort': 579},
 'ocr-entities': {'slug': 'ocr-entities', 'keywords': 'كيانات OCR OCR Entities OCR OCR', 'popular': False, 'sort': 580},
 'ocr-language-report': {'slug': 'ocr-language-report',
                         'keywords': 'تقرير لغة OCR OCR Language Report OCR OCR',
                         'popular': False,
                         'sort': 581},
 'bzip2-compress': {'slug': 'bzip2-compress',
                    'keywords': 'ضغط BZIP2 BZIP2 Compress الأرشيف Archive',
                    'popular': False,
                    'sort': 582},
 'bzip2-decompress': {'slug': 'bzip2-decompress',
                      'keywords': 'فك BZIP2 BZIP2 Decompress الأرشيف Archive',
                      'popular': False,
                      'sort': 583},
 'xz-compress': {'slug': 'xz-compress',
                 'keywords': 'ضغط XZ XZ Compress الأرشيف Archive',
                 'popular': False,
                 'sort': 584},
 'xz-decompress': {'slug': 'xz-decompress',
                   'keywords': 'فك XZ XZ Decompress الأرشيف Archive',
                   'popular': False,
                   'sort': 585},
 'tar-gzip-create': {'slug': 'tar-gzip-create',
                     'keywords': 'إنشاء TAR.GZ Create TAR.GZ الأرشيف Archive',
                     'popular': True,
                     'sort': 586},
 'tar-gzip-extract': {'slug': 'tar-gzip-extract',
                      'keywords': 'فك TAR.GZ Extract TAR.GZ الأرشيف Archive',
                      'popular': False,
                      'sort': 587},
 'zip-duplicate-report': {'slug': 'zip-duplicate-report',
                          'keywords': 'تكرار ملفات ZIP ZIP Duplicate Report الأرشيف Archive',
                          'popular': False,
                          'sort': 588},
 'tar-integrity': {'slug': 'tar-integrity',
                   'keywords': 'سلامة TAR TAR Integrity Report الأرشيف Archive',
                   'popular': False,
                   'sort': 589},
 'tar-bzip2-create': {'slug': 'tar-bzip2-create',
                      'keywords': 'إنشاء TAR.BZ2 Create TAR.BZ2 الأرشيف Archive',
                      'popular': False,
                      'sort': 590},
 'tar-bzip2-extract': {'slug': 'tar-bzip2-extract',
                       'keywords': 'فك TAR.BZ2 Extract TAR.BZ2 الأرشيف Archive',
                       'popular': False,
                       'sort': 591},
 'base64-decode': {'slug': 'base64-decode',
                   'keywords': 'فك Base64 Base64 Decode الأدوات المساعدة Utilities',
                   'popular': False,
                   'sort': 592},
 'url-encode': {'slug': 'url-encode',
                'keywords': 'ترميز URL URL Encode الأدوات المساعدة Utilities',
                'popular': False,
                'sort': 593},
 'url-decode': {'slug': 'url-decode',
                'keywords': 'فك ترميز URL URL Decode الأدوات المساعدة Utilities',
                'popular': False,
                'sort': 594},
 'json-minify': {'slug': 'json-minify',
                 'keywords': 'تصغير JSON JSON Minify الأدوات المساعدة Utilities',
                 'popular': True,
                 'sort': 595},
 'text-diff': {'slug': 'text-diff',
               'keywords': 'مقارنة نصين Text Diff الأدوات المساعدة Utilities',
               'popular': True,
               'sort': 596},
 'checksum-compare': {'slug': 'checksum-compare',
                      'keywords': 'مقارنة البصمة Checksum Compare الأدوات المساعدة Utilities',
                      'popular': False,
                      'sort': 597},
 'uuid-list-generator': {'slug': 'uuid-list-generator',
                         'keywords': 'مولد UUID دفعة واحدة UUID Batch Generator الأدوات المساعدة Utilities',
                         'popular': False,
                         'sort': 598},
 'regex-extract': {'slug': 'regex-extract',
                   'keywords': 'استخراج Regex Regex Extractor الأدوات المساعدة Utilities',
                   'popular': False,
                   'sort': 599},
 'file-extension-report': {'slug': 'file-extension-report',
                           'keywords': 'تقرير امتداد الملف File Extension Report الأدوات المساعدة Utilities',
                           'popular': False,
                           'sort': 600},
 'hex-encode': {'slug': 'hex-encode',
                'keywords': 'ترميز HEX Hex Encode الأدوات المساعدة Utilities',
                'popular': False,
                'sort': 601}}

AUDIENCE_COLLECTIONS = {'students': {'title_ar': 'للطلاب',
              'title_en': 'For Students',
              'description_ar': 'رتب محاضراتك وواجباتك وملفاتك الدراسية بسرعة.',
              'description_en': 'Organize lecture notes, assignments, and study files quickly.',
              'tool_ids': ('pdf-merge',
                           'pdf-split',
                           'pdf-compress',
                           'pdf-to-text',
                           'pdf-ocr',
                           'pdf-to-docx',
                           'pdf-to-markdown',
                           'image-to-pdf',
                           'image-upscale',
                           'word-to-pdf',
                           'ppt-to-pdf',
                           'assignment-cover-page',
                           'lms-pdf-size-optimizer',
                           'omr-bubble-sheet',
                           'ocr-pdf-to-markdown',
                           'lms-question-bank-formatter')},
 'educators': {'title_ar': 'للمعلمين والدكاترة',
               'title_en': 'For Educators',
               'description_ar': 'جهز موادك التعليمية وشارك المستندات بوضوح.',
               'description_en': 'Prepare teaching materials and share documents with clarity.',
               'tool_ids': ('pdf-merge',
                            'pdf-extract-pages',
                            'pdf-delete-pages',
                            'pdf-redact',
                            'pdf-ocr',
                            'pdf-to-docx',
                            'word-to-pdf',
                            'ppt-to-pdf',
                            'image-to-pdf',
                            'image-watermark',
                            'zip-create',
                            'bulk-certificate-maker',
                            'omr-bubble-sheet',
                            'lms-question-bank-formatter')},
 'developers': {'title_ar': 'للمطورين',
                'title_en': 'For Developers',
                'description_ar': 'أدوات ملفات عملية للمواصفات والتوثيق والتحقق.',
                'description_en': 'Practical file tools for documentation, data, and verification.',
                'tool_ids': ('markdown-to-html',
                             'html-to-pdf',
                             'csv-to-xlsx',
                             'file-hash',
                             'file-info',
                             'json-minify',
                             'text-diff',
                             'checksum-compare',
                             'zip-create',
                             'zip-extract',
                             'pdf-to-text',
                             'csv-merge-deduplicate')},
 'business': {'title_ar': 'للأعمال',
              'title_en': 'For Business',
              'description_ar': 'حوّل وشارك المستندات والفواتير والملفات اليومية.',
              'description_en': 'Convert and share documents, invoices, and everyday files.',
              'tool_ids': ('excel-to-pdf',
                           'csv-to-xlsx',
                           'csv-to-pdf',
                           'xlsx-to-html',
                           'csv-statistics',
                           'pdf-compress',
                           'pdf-merge',
                           'pdf-redact',
                           'image-to-pdf',
                           'image-watermark',
                           'zip-create',
                           'file-info',
                           'bulk-certificate-maker',
                           'csv-merge-deduplicate')},
 'everyday': {'title_ar': 'للاستخدام اليومي',
              'title_en': 'Everyday Tools',
              'description_ar': 'أدوات سريعة للصور وملفات PDF والمهام اليومية.',
              'description_en': 'Fast tools for images, PDFs, and everyday tasks.',
              'tool_ids': ('image-to-jpg',
                           'image-to-png',
                           'image-to-webp',
                           'image-resize',
                           'image-compress',
                           'image-upscale',
                           'image-background-cleaner',
                           'image-rotate',
                           'image-to-pdf',
                           'pdf-compress',
                           'social-media-image-resizer',
                           'quote-social-graphic',
                           'pdf-booklet')}}

DEVELOPER_TOOLS = {'json-formatter': {'name_ar': 'منسق JSON',
                    'name_en': 'JSON Formatter',
                    'description_ar': 'نسّق وتحقق من JSON محليًا في متصفحك.',
                    'description_en': 'Format and validate JSON locally in your browser.',
                    'icon': '{}'},
 'base64': {'name_ar': 'Base64 تشفير وفك',
            'name_en': 'Base64 Encode / Decode',
            'description_ar': 'شفّر النص أو فك Base64 دون إرسال المحتوى.',
            'description_en': 'Encode text or decode Base64 without sending its contents.',
            'icon': '64'},
 'url-encoder': {'name_ar': 'تشفير URL',
                 'name_en': 'URL Encoder',
                 'description_ar': 'شفّر أو فك مكونات الروابط محليًا.',
                 'description_en': 'Encode or decode URL components locally.',
                 'icon': 'URL'},
 'uuid-generator': {'name_ar': 'مولد UUID',
                    'name_en': 'UUID Generator',
                    'description_ar': 'ولّد UUID v4 عشوائيًا محليًا.',
                    'description_en': 'Generate random UUID v4 values locally.',
                    'icon': 'ID'},
 'hash-generator': {'name_ar': 'مولد SHA-256',
                    'name_en': 'SHA-256 Generator',
                    'description_ar': 'احسب بصمة SHA-256 للنص محليًا.',
                    'description_en': 'Calculate a SHA-256 text hash locally.',
                    'icon': 'SHA'},
 'timestamp-converter': {'name_ar': 'محول التوقيت',
                         'name_en': 'Timestamp Converter',
                         'description_ar': 'حوّل Unix timestamp إلى تاريخ عالمي والعكس.',
                         'description_en': 'Convert Unix timestamps to global dates and back.',
                         'icon': 'UTC'}}

PREMIUM_TOOL_IDS = frozenset({'assignment-cover-page',
 'bulk-certificate-maker',
 'csv-merge-deduplicate',
 'lms-pdf-size-optimizer',
 'lms-question-bank-formatter',
 'omr-bubble-sheet',
 'pdf-booklet',
 'quote-social-graphic',
 'social-media-image-resizer'})

RELATED_OVERRIDES = {'word-to-pdf': ('pdf-compress', 'pdf-ocr', 'pdf-merge', 'pdf-split'),
 'excel-to-pdf': ('pdf-compress', 'pdf-merge', 'csv-to-xlsx'),
 'ppt-to-pdf': ('pdf-compress', 'pdf-to-jpg', 'pdf-merge'),
 'pdf-to-jpg': ('image-compress', 'image-resize', 'pdf-compress'),
 'pdf-to-png': ('image-compress', 'image-resize', 'pdf-compress'),
 'image-to-pdf': ('pdf-compress', 'pdf-merge', 'pdf-to-jpg'),
 'pdf-merge': ('pdf-compress', 'pdf-split', 'pdf-rotate'),
 'pdf-split': ('pdf-merge', 'pdf-extract-pages', 'pdf-compress'),
 'pdf-compress': ('pdf-merge', 'pdf-split', 'pdf-to-jpg', 'pdf-remove-blank-pages', 'pdf-grayscale'),
 'pdf-reorder-pages': ('pdf-rotate-selected', 'pdf-extract-pages', 'pdf-delete-pages'),
 'pdf-password-protect': ('pdf-watermark-text', 'pdf-metadata', 'pdf-compress'),
 'pdf-ocr': ('pdf-to-text', 'pdf-compress', 'pdf-merge'),
 'image-ocr': ('image-compress', 'image-to-pdf'),
 'image-compress': ('image-resize', 'image-to-pdf', 'image-to-webp'),
 'image-resize': ('image-compress', 'image-to-webp'),
 'zip-extract': ('file-info', 'file-hash'),
 'zip-create': ('zip-extract',)}
